---
title: "KNFILD"
---

Code filière indemnisation théorique : code filière de l'article 27 de l'annexe au règlement à la Convention du 1/01/94 avant comparaison de            capitaux. Filière relative au droit consommé.                      


**01**. 4 MOIS SOIT 122 JOURS OU 676 HEURES DANS LES 8 MOIS<br> 01/08/1992 Durée d'indemnisation : 122 jours à taux minoré (-25%)<br> 01/08/1993 Durée d'indemnisation : 122 jours à taux minoré (-25%)<br> 01/01/1997 Durée d'indemnisation : 122 jours à taux plein<br> 122 JOURS DANS LES 18 MOIS<br> 01/01/2001 Durée d'indemnisation : 122 jours à taux plein<br>

**02**. 6 MOIS SOIT 182 JOURS OU 1014 HEURES DANS LES 12 MOIS<br> 01/08/1992 Durée d'indemnisation : 122 jours à taux plein et 91 jours à -- 15%<br> 01/08/1993 Durée d'indemnisation : 122 jours à taux plein et 91 jours à -- 15%<br> 01/01/1997 Durée d'indemnisation : 122 jours à taux plein et 91 jours à -- 15%<br> 01/01/2001 Durée d'indemnisation : 213 jours à taux plein<br>

**03**. 8 MOIS SOIT 243 JOURS OU 1352 HEURES DANS LES 12 MOIS ET MOINS DE 50 ANS<br> 01/08/1992 Durée d'indemnisation : 152 jours à taux plein et 304 jours à taux dégressif à raison de - 17% tous les 4 mois<br> 01/08/1993 Durée d'indemnisation : 122 jours à taux plein et 334 jours à taux dégressif à raison de - 17% tous les 4 mois<br> 01/01/1997 Durée d'indemnisation : 122 jours à taux plein et 334 jours à taux dégressif à raison de - 15% tous les 6 mois<br> 01/01/2001 Durée d'indemnisation : 456 jours à taux plein<br>

**04**. 8 MOIS SOIT 243 JOURS OU 1352 HEURES DANS LES 12 MOIS ET 50 ANS ET PLUS<br> 01/08/1992 Durée d'indemnisation : 243 jours à taux plein et 396 jours à taux dégressif à raison de - 15% tous les 4 mois<br> 01/08/1993 Durée d'indemnisation : 213 jours à taux plein et 426 jours à taux dégressif à raison de - 15% tous les 4 mois<br> 01/01/1997 Durée d'indemnisation : 213 jours à taux plein et 426 jours à taux dégressif à raison de - 15% tous les 6 mois<br> 01/01/2001 Durée d'indemnisation : 639 jours à taux plein<br>

**05**. 14 MOIS SOIT 426 JOURS OU 2366 HEURES DANS LES 24 MOIS ET MOINS DE 25 ANS<br> 01/08/1992 Durée d'indemnisation : 274 jours à taux plein et 638 jours à taux dégressif à raison de - 17% tous les 4 mois<br> 01/08/1993 Durée d'indemnisation : 213 jours à taux plein et 699 jours à taux dégressif à raison de - 17% tous les 4 mois<br> 01/01/1997 Filière supprimée<br>

**06**. 14 MOIS SOIT 426 JOURS OU 2366 HEURES DANS LES 24 MOIS<br> ENTRE 25 ANS ET MOINS DE 50 ANS<br> 01/08/1992 Durée d'indemnisation : 365 jours à taux plein et 547 jours à taux dégressif à raison de - 17% tous les 4 mois<br> 01/08/1993 Durée d'indemnisation : 274 jours à taux plein et 638 jours à taux dégressif à raison de - 17% tous les 4 mois<br> MOINS DE 50 ANS<br> 01/01/1997 Durée d'indemnisation : 274 jours à taux plein et 638 jours à taux dégressif à raison de - 17% tous les 6 mois<br> 01/01/2001 Durée d'indemnisation : 912 jours à taux plein<br>

**07**. 14 MOIS SOIT 426 JOURS OU 2366 HEURES DANS LES 24 MOIS ET 50 ANS ET PLUS<br> 01/08/1992 Durée d'indemnisation : 517 jours à taux plein et 852 jours à taux dégressif à raison de - 15% tous les 4 mois<br> 01/08/1993 Durée d'indemnisation : 456 jours à taux plein et 913 jours à taux dégressif à raison de - 15% tous les 4 mois<br> 01/01/1997 Durée d'indemnisation : 456 jours à taux plein et 913 jours à taux dégressif à raison de - 15% tous les 6 mois<br> 01/01/2001 Durée d'indemnisation : 1369 jours à taux plein<br>

**08**. 27 MOIS SOIT 821 JOURS OU 4563 HEURS DANS LES 36 MOIS ET ENTRE 50 ANS ET MOINS DE 55 ANS<br> 01/08/1992 Durée d'indemnisation : 609 jours à taux plein et 760 jours à taux dégressif à raison de - 15% tous les 4 mois<br> 01/08/1993 Durée d'indemnisation : 609 jours à taux plein et 760 jours à taux dégressif à raison de - 15% tous les 4 mois<br> 01/01/1997 Durée d'indemnisation : 609 jours à taux plein et 760 jours à taux dégressif à raison de - 15% tous les 6 mois<br> 01/01/2001 Durée d'indemnisation : 1369 jours à taux plein<br>

**09**. 27 MOIS SOIT 821 JOURS OU 4563 HEURES DANS LES 36 MOIS<br> 55 ANS ET PLUS<br> 01/08/1992 Durée d'indemnisation : 821 jours à taux plein et 1004 jours à taux dégressif à raison de - 8% tous les 4 mois<br> 01/08/1993 Durée d'indemnisation : 821 jours à taux plein et 1004 jours à taux dégressif à raison de - 8% tous les 4 mois<br> 01/01/1997 Durée d'indemnisation : 821 jours à taux plein et 1004 jours à taux dégressif à raison de - 8% tous les 6 mois<br> 01/01/2001 Durée d'indemnisation : 1825 jours à taux plein<br> 55 ANS ET PLUS ET 100 TRIMESTRES<br> 01/07/2002 Durée d'indemnisation : 1825 jours à taux plein<br>

**99**. SANS OBJET<br>

**A**. 6 MOIS SOIT 182 JOURS OU 910 HEURES DANS LES 22 MOIS<br> 01/01/2003 Durée d'indemnisation : 213 jours à taux plein<br>

**B**. 14 MOIS SOIT 426 JOURS OU 2123 HEURES DANS LES 24 MOIS<br> 01/01/2003 Durée d'indemnisation : 700 jours à taux plein<br>

**C**. 27 MOIS SOIT 821 JOURS OU 4095 HEURES DANS LES 36 MOIS ET 50 ANS OU +<br> 01/01/2003 Durée d'indemnisation : 1095 jours à taux plein<br>

**D**. 27 MOIS SOIT 821 JOURS OU 4095 HEURES DANS LES 36 MOIS ET 57 ANS ET 100 TRIMESTRES<br> 01/01/2003 Durée d'indemnisation 1277 jours à taux plein<br>

**E**. 426 JOURS OU 2366 HEURES DANS LES 24 MOIS ET 50 ANS OU PLUS ET DONT L A DATE DE PROCEDURE DE LICENCIEMENT \<= 31/12/2002<br> 01/01/2003 Durée d'indemnisation 1369 jours<br>

**F**. 821 JOURS OU 4653 HEURES DANS LES 36 MOIS ET 55 ANS OU PLUS ET DONT L A DATE DE PROCEDURE DE LICENCIEMENT \<= 31/12/2002<br> 01/01/2003 Durée d'indemnisation 1825 jours<br>

**A6**. 6 MOIS SOIT 182 JOURS ou 910 HEURES DANS LES 22 MOIS<br> 18/01/2006 Durée d'indemnisation : 213 jours à taux plein soit 7 mois<br>

**B6**. 12 MOIS SOIT 365 JOURS OU 1820 HEURES DANS LES 20 MOIS<br> 18/01/2006 Durée d'indemnisation : 365 jours à taux plein soit 12 mois<br>

**C6**. 16 MOIS SOIT 487 JOURS OU 2426 HEURES DANS LES 26 MOIS<br> 18/01/2006 Durée d'indemnisation : 700 jours à taux plein soit 23 mois<br>

**D6**. 27 MOIS SOIT 821 JOURS OU 4095 HEURES DANS LES 36 MOIS ET 50 ANS OU PLUS<br> 18/01/2006 Durée d'indemnisation : 1095 jours à taux plein soit 36 mois
