---
title: "Dictionnaire des variables"
---

| <br>Variables | <br>Libellé                                               | <br>Modalités / Commentaires                                                                                                                                                                                                                                                                 |
|---------------|-----------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <br>BNI       | <br>Identifiant unique du demandeur                       | <br>Le code BNI est l'identifiant national du<br> demandeur. Dans la région d'arrivée, dans <br>la mesure où le demandeur a bien<br> été reconnu, son code BNI d'origine <br>lui est réaffecté. Le code BNI permet <br>ainsi d'identifier le demandeur dans <br>toutes les bases régionales. |
| <br>CODPAR    | <br>Code partenaire pour une <br>prestation               | <br>                                                                                                                                                                                                                                                                                         |
| <br>CODSTATU  | <br>CODE STATUT                                           | <br>C. Conseillée<br> <br>E. Absence excusée<br> <br>H. N'adhère pas<br> <br>I. Inscription<br> <br>N. Abandon<br> <br>R. Réalisation<br> <br>S. Suppression                                                                                                                                 |
| <br>DATDEB    | <br>Date de début de la prestation                        | <br>                                                                                                                                                                                                                                                                                         |
| <br>DATINSAC  | <br>Date d'inscription de l'action                        | <br>                                                                                                                                                                                                                                                                                         |
| <br>DATMAJAC  | <br>Date de mise à jour du statut                         | <br>                                                                                                                                                                                                                                                                                         |
| <br>DATPRECO  | <br>Date de préconisation                                 | <br>                                                                                                                                                                                                                                                                                         |
| <br>DATSTAT   | <br>Mois statistique                                      | <br>                                                                                                                                                                                                                                                                                         |
| <br>NUMAIS    | <br>Numéro d'AIS (Attestation <br>d'inscription au stage) | <br>                                                                                                                                                                                                                                                                                         |
| <br>NUMALE    | <br>UNITE ALE DE L'ACTION                                 | <br>Attention à ne pas confondre <br>avec la variable ALE dans la table <br>DE, qui correspond à l'ALE <br>d'inscription du demandeur.                                                                                                                                                       |
| <br>NUMPRES   | <br>NUMERO DE PRESTATION                                  | <br>Très peu renseignée                                                                                                                                                                                                                                                                      |
