---
title: "Dictionnaire des variables"
editor: 
  markdown: 
    wrap: 72
---

| <br>Variables | <br>Libellé | <br>Modalités | <br>Commentaires |
|:-------------:|:-------------:|:--------------:|:------------------------:|
| <br>MOISTA | <br>Mois concerné | <br> | <br> |
| <br>CATCALCULEE | <br>Catégorie calculée | <br> | <br>La modalité "9" correspond à la catégorie F. La catégorie G comprend les modalités "101" et "102" (cf. [Fiche](../../../Fiches/Catégories_FHS.html)) |
| <br>DEBCAT | <br>Début de l'inscription |  |  |
| <br>FINCAT | <br>Fin de l'inscription |  |  |
| <br>DEBCAT_MOIS | <br>Date de début de période d’inscription bornée sur le mois concerné MOISTA |  | <br>Pour une période d’inscription commençant le 10 avril 2025 (DEBCAT), si l’on regarde la ligne pour le mois de mai 2025 (MOISTA = 202505), la date DEBCAT_MOIS vaudra 1er mai 2025 (si toujours en cours en mai) |
| <br>FINCAT_MOIS | <br>Date de fin de période d’inscription bornée sur le mois concerné MOISTA |  | <br>Pour une période d’inscription se finissant le 25 juillet 2025 (et commençant en juin ou avant), la ligne concernant juin 2025 (MOISTA = 202506) indiquera le 31 juin 2025. |
| <br>FINMOIS | <br>Indicatrice de présence en fin de mois |  | <br>Cela permet, lors de l’utilisation des dates tronquées, lorsque la date FINCAT_MOIS est égale au dernier jour du mois, de distinguer une période qui se termine le dernier jour du mois (FINMOIS = 0) d’une période toujours en cours en fin de mois (FINMOIS = 1) ainsi que d’identifier facilement les personnes présentes en fin de mois (au sens de la STMT). |
| <br>TYPSTRUCTACNLPE | <br>Type de structure accompagnatrice de l’usager | <br>CD. Conseil départemental<br>CE. Cap emploi<br>FT. France Travail<br>IND. Indéterminé<br>ML. Missions locales |  |
