---
title: "CODACT"
---

**AAC.** AUTRE ACTION CAP EMPLOI

**AAD.** EXPE LYON VALENCE ST ETIENNE

**AAM.** AUTRE ACTION MISSION LOCALE

**AAO.** AUTRE ACTION OFFRE

**AAP.** AUTRE ACTION PROJET

**AAR.** AUTRE ACTION RECHERCHE

**ABA.** BILAN AFPA MI CARRIERE (BAMC)

**ABP.** EXPE AVIGNON MARSEILLE

**ACA.** ENVOI APEC

**ACE.** ENVOI CAP EMPLOI

**ACI.** ACCOMPAGNEMENT INTENSIF

**ACR.** ACCOMPAGNEMENT RENFORCE

**ACS.** ACCOMPAGNEMENT CADRES SENIORS

**ADM.** PARCOURS 2

**ADR.** PARCOURS 3

**ADS.** PARCOURS 1

**AIG.** PRESTATION ACCOMPAGNEMENT SPEC

**AIP.** INDISPONIBILITE PARTIELLE

**AIT.** INDISPONIBILITE TOTALE

**AML.** ENVOI MISSIONS LOCALES

**AOR.** M.E.R. SUR AUTRE ORGANISME

**ARC.** ACCOMPAGNEMENT REPRENEUR CREAT

**ATD.** EXPE TOULON CAGNES SOFIA

**A00.** ATELIER

**A01.** CV

**A02.** ENTRETIEN EMBAUCHE

**A03.** CIBLER

**A04.** RELATION

**A05.** REPONDRE P.A

**A06.** CANDIDATURE

**A07.** SAVOIR FAIRE

**A08.** UTILISER P.A

**A09.** ORGANISER

**A10.** TELEPHONE

**A11.** LOOK

**A12.** ESSAI

**A13.** TEST

**A14.** RECHERCHE D'EMPLOI PAR INTERNE

**A15.** TRAVAIL A L'ETRANGER

**A16.** S'ORGANISER POUR TRAVAIL A L'E

**A17.** PREPARER VALIDATION ACQUIS DE

**A18.** DECOUVRIR LE MARCHE DU TRAVAIL

**A19.** TROUVER DES OFFRES

**A20.** FAIRE LE POINT

**A21.** FORMATION

**A22.** ATOUTS

**A23.** INFORMATION

**A24.** VERIFIER

**A25.** PLAN

**A26.** CREATION

**A27.** MON CV-PUBLIC SPECIFIQUE

**A28.** JE TROUVE UNE OFFRE

**A29.** ORGANISER DEPLACEMENTS / MARCHE DU TRAVAIL

**A30.** TRAVAILLER AU ROYAUME-UNI

**A31.** TRAVAILLER EN ALLEMAGNE

**A32.** TRAVAILLER EN ESPAGNE

**A33.** TRAVAILLER AU CANADA

**A34.** TRAVAILLER EN ITALIE

**A40.** SIMULER UN ENTRETIENT D'EMBAUCHE

**A41.** DECIDER DE SE FORMER

**BCA.** BILAN DE COMPETENCES APPROFOND

**CAD.** ATOUT CADRE

**CEN.** CREATION OU REPRISE D'ENTREPRI

**CIB.** CIBLE EMPLOI

**CIV.** CONTRAT D'INSERTION DANS LA VI

**CVE.** ACCOMPAGNEMENT CAP ENTREPRISE

**C30.** SENSIB CREA ENTREPR

**C91.** SPEC REGION C1

**C92.** SPEC REGION C2

**C93.** SPEC REGION C3

**DAP.** DIAGNOSTIC APPROFONDI

**DPO.** DIAGNOSTIC DE POSITIONNEMENT

**ECA.** Évaluation des Compétences et Capa Prof AFPA

**ECE.** EMT CAP VERS L'ENTREPRISE

**EFA.** MER SUR FORMATION AFPA

**EFO.** MISE EN RELATION FORMATION

**EJZ.** EMT RENFORCEE JEUNES ZUS

**ENE.** ENTRETIEN D'EVALUATION

**ENI.** ENTRETIEN D'INFORMATION

**ENO.** ENTRETIEN D'ORIENTATION

**EUR.** ACTION FINANCEE PAR EUR

**EPS.** EVALUATION EN MILIEU DE TRAVAIL PLAN SENIOR

**E20.** EPCRE

**E30.** ENCP

**E31.** ENCP 1

**E32.** ENCP 2

**E33.** ENCP 3

**E40.** EMT STANDARD

**E41.** EMT 1

**E42.** EMT 2

**E43.** EMT 3

**E50.** ENAP STANDARD

**E51.** ENAP 1

**E52.** ENAP 2

**E53.** ENAP 3

**E60.** CAD"IDENT POTENTIEL"

**E70.** BILAN PROJET ET METHODES RECHE

**E80.** EVAL PREALABLE AU RECRUTEMENT

**E90.** EVAL COMPETENCES ET CAPACITES

**E91.** SPEC REGIONALE EV 1

**E92.** SPEC REGIONALE EV 2

**E93.** SPEC REGIONALE EV 3

**HAB.** EVALUATION DES HABILETES PAR S

**I30.** INFO COLL A THEME

**I40.** INFO COLL PAP

**I50.** INFO COLL PLAN 50000 JEUNES

**I91.** SPEC REGION INF 1

**I92.** SPEC REGION INF 2

**I93.** SPEC REGION INF 3

**LEC.** Licencié Economique OPP

**MEA.** MISE RELATION OFFRE ACTIVITE

**MET.** MISE RELATION CONTRAT TRAVAIL

**ME0.** M.E.R SUR CONTRAT INITIATIVE L

**ME1.** M.E.R CONTRAT TRAVAIL NORMAL

**ME2.** M.E.R CONTRAT D'APPRENTISSAGE

**ME3.** M.E.R APEJ

**ME4.** M.E.R CONTRAT ORIENTATION

**ME5.** M.E.R CONTRAT QUALIFICATION

**ME6.** M.E.R CONTRAT D'ADAPTATION

**ME7.** M.E.R CONTRAT POINT OPERATIONN

**ME8.** M.E.R SUR CAE DOM

**ME9.** M.E.R SUR CES HORS CADRE INSER

**MF2.** M.E.R SUR CONTRAT INITIATIVE E

**MF3.** M.E.R SUR CONVENTION DE COOPER

**MF4.** M.E.R SUR EMPLOI VILLE

**MF5.** M.E.R SUR CONTRAT EMPLOI JEUNE

**MF6.** M.E.R SUR CEC HORS CADRE INSER

**MF7.** M.E.R SUR CONTRAT DE QUALIF. A

**MI1.** M.E.R SUR CONTRAT INSERTION EC

**MI2.** M.E.R SUR CONTRAT G.E.I.Q

**MI3.** M.E.R SUR CES/CEC INSERTION PA

**MOB.** MOBILISATION VERS L'EMPLOI

**MOV.** MOBILISATION VERS L'EMPLOI (nouveaux marchés 2010)

**NET.** INITIATION À L'UTILISATION D'I

**OED.** OBJECTIF EMPLOI DURABLE

**OEN.** OBJECTIF ENTREPRISE

**OPL.** OBJECTIF PLACEMENT

**OPS.** Orientation Professionnelle Spécialisée (2010 04)

**OPU.** OPERATEURS PRIVES UNEDIC

**OSA.** OFFRE SPECIFIQUE RSA

**O20.** ACCOMPAGNEMENT INDIV. OBJECTIF

**O21.** ACCOMPAGNEMENT GROUPE OBJECTIF

**O30.** SOA STANDARD

**O31.** SOA 1

**O32.** SOA 2

**O33.** SOA 3

**O40.** MOA STANDARD

**O41.** MOA 1

**O42.** MOA 2

**O43.** MOA 3

**O50.** DU DIPLOME A L'EMPLOI

**O51.** DU DIPLOME A L'EMPLOI 1

**O52.** DU DIPLOME A L'EMPLOI 2

**O53.** DU DIPLOME A L'EMPLOI 3

**O60.** BILAN DE COMPETENCES

**O61.** CHEQ BIL COMP CADRES

**O91.** SPEC REGION OR 1

**O92.** SPEC REGION OR 2

**O93.** SPEC REGION OR 3

**PAD.** ACCOMPAGNEMENT EMPLOI

**PAS.** PRESTATION D'APPUI SOCIAL

**PIJ.** PROJET INITIATIVE JEUNE

**PPE.** UN PROJET POUR UN EMPLOI

**PRC.** PRESTATION CREATION ENTREPRISE GUADELOU

**PRE.** PRESTATION D'EVALUATION

**PRI.** PRESTATION D'INFORMATION

**PRO.** PRESTATION D'ORIENTATION

**PRR.** PRESTATION DE RECHERCHE EMPLOI

**P10.** PROGRAMME ACCES EMPLOI JEUNES

**P20.** PLAN LOCAL POUR INSERTION ET E

**P30.** INSERTION PAR ACTIVITE ECONOMI

**P40.** ACCOMPAGNEMENT DURANT CES

**P50.** ACCOMPAGNEMENT INDIVIDUALISE

**RCE.** OBJECTIF EMPLOI CAP VERS L'ENT

**R20.** ACCOMPAGNEMENT INDIV. OBJECTIF

**R21.** ACCOMPAGNEMENT GROUPE OBJECTIF

**R30.** STRE STANDARD

**R31.** STRE 1

**R32.** STRE 2

**R33.** STRE 3

**R40.** ARE STANDARD

**R41.** ARE 1

**R42.** ARE 2

**R43.** ARE 3

**R50.** CRDE ACTIVE

**R51.** CRDE ACTIVE 1

**R52.** CRDE ACTIVE 2

**R53.** CRDE ACTIVE 3

**R60.** APE STANDARD

**R61.** APE 1

**R62.** APE 2

**R63.** APE 3

**R70.** MARKETING EMPLOI

**R71.** MARKETING EMPLOI 1

**R72.** MARKETING EMPLOI 2

**R73.** MARKETING EMPLOI 3

**R80.** CLUB DE CHERCHEURS

**R81.** CLUB DE CHERCHEURS 1

**R82.** CLUB DE CHERCHEURS 2

**R83.** CLUB DE CHERCHEURS 3

**R90.** RENFORCER ET ACCOMPAGNER RECHE

**R91.** SPEC REGION RE 1

**R92.** SPEC REGION RE 2

**R93.** SPEC REGION RE 3

**SAI.** ACCOMPAGNEMENT CHOMAGE SAISONNIER OPP

**SCO.** SUIVI COTRAITANT

**SPN.** SUIVI PARTENAIRE NON INFORMATISE

**STR.** STRATEGIE DE RECHERCHE EMPLOI

**S20.** PARCOURS FORMATION AFPA (2010 04 : arrêt -\>OPS)

**TIC.** ACCOMPAGNEMENT CADRES A DISTAN

**TRA.** Trajectoire Emploi OPP

**T01.** APPUI À LA DEMARCHE DE RECH. D

**T02.** ENTRAINEMENT AUX ENTRETIENS (O

**T03.** BILAN DE COMPETENCES (OPP)

**T04.** DEFINITION DE PROJET (OPP)

**T05.** PROPOSITION D'OFFRE D'EMPLOI (

**T06.** FORMATION COURTE (5 JOURS OU M

**T07.** FORMATION LONGUE (6 JOURS OU P

**T08.** MISE EN SITUATION PROFESSIONNE

**T09.** AUTRE (OPP)

**VAF.** VAE MINISTERE TRAVAIL AFPA

**VAG.** ACCOMPMT PARCOURS de VAE GUADELOUPE

**VAO.** VAE AUTRE ORGANISME

**VOC.** EVAL SUR PLATE-FORME DE VOCATI

**V01.** ANCIEN VAE
