project:
  type: website

website:
  title: "Documentation MiDAS"
  navbar:
    search: true
    left:
      - text: "MiDAS"
        href: Presentation/présentation.qmd
      - text: "FHS"
        href: FHS/FHS_presentation.qmd
      - text: "FNA"
        href: FNA/FNA_presentation.qmd
      - text: "Allstat-FR6"
        href: Allstat_FR6/Allstat_FR6_presentation.qmd
      - text: "DSN"
        href: DSN/DSN_presentation.qmd
      - text: "Fiches"
        href: Fiches/Fiches_presentation.qmd
      - text: "Codes"
        href: Codes/codes_presentation.qmd
      - about.qmd
      
  sidebar: 
    - title: "MiDAS"
      style: "docked"
      background: light
      contents:
        - href: Presentation/présentation.qmd
        - href: Presentation/presentation1.qmd
        - href: Presentation/presentation2.qmd
        
        
    - title: "FHS"
      style: "docked"
      background: light
      contents:
        - section: "Présentation"
          contents: 
            - FHS/FHS_presentation.qmd
        - section: "DE"
          contents: 
            - href: FHS/DE/DE_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FHS/DE/Dico_FHS_DE/DE_dictionnaire.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/MOTANN.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/MOTANN_a.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/MOTINS.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/MOTINS_a.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/NATION.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/OBLIGEM.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/SITPAR.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/SITPAR_a.qmd
              - href: FHS/DE/Dico_FHS_DE/FHS_DE_variables/REGION.qmd
        - section: "E0"
          contents: 
            - href: FHS/E0/E0_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FHS/E0/Dico_FHS_E0/E0_dictionnaire.qmd
        - section: "P2"
          contents: 
            - href: FHS/P2/P2_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FHS/P2/Dico_FHS_P2/P2_dictionnaire.qmd
              - href: FHS/P2/Dico_FHS_P2/FHS_P2_variables/CATFIN.qmd
              - href: FHS/P2/Dico_FHS_P2/FHS_P2_variables/FORMACOD.qmd
              - href: FHS/P2/Dico_FHS_P2/FHS_P2_variables/ORGCAT.qmd
        - section: "Parcours"
          contents: 
            - href: FHS/Parcours/Parcours_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FHS/Parcours/Dico_FHS_Parcours/Parcours_dictionnaire.qmd
        - section: "D2"
          contents: 
            - href: FHS/D2/D2_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FHS/D2/Dico_FHS_D2/D2_dictionnaire.qmd
              - href: FHS/D2/Dico_FHS_D2/FHS_D2_variables/INDEM.qmd
        - section: "E3"
          contents: 
            - href: FHS/E3/E3_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FHS/E3/Dico_FHS_E3/E3_dictionnaire.qmd
              - href: FHS/E3/Dico_FHS_E3/FHS_E3_variables/CODACT.qmd
        - section: "E3_Cons"
          contents: 
            - href: FHS/E3_Cons/E3_Cons_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FHS/E3/Dico_FHS_E3/E3_dictionnaire.qmd        
            
    - title: "FNA"
      style: "docked"
      background: light
      contents:
        - section: "Présentation"
          contents: 
            - FNA/FNA_presentation.qmd
        - section: "PJC"
          contents: 
            - href: FNA/PJC/PJC_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FNA/PJC/Dico_FNA_PJC/PJC_dictionnaire.qmd
              - href: FNA/PJC/Dico_FNA_PJC/FNA_PJC_variables/KCALF.qmd
              - href: FNA/PJC/Dico_FNA_PJC/FNA_PJC_variables/KCMNI.qmd
        - section: "ODD"
          contents: 
            - href: FNA/ODD/ODD_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FNA/ODD/Dico_FNA_ODD/ODD_dictionnaire.qmd
              - href: FNA/ODD/Dico_FNA_ODD/FNA_ODD_variables/KCAAJ.qmd
              - href: FNA/ODD/Dico_FNA_ODD/FNA_ODD_variables/KCRD.qmd
              - href: FNA/ODD/Dico_FNA_ODD/FNA_ODD_variables/KNFILD.qmd
        - section: "DAL"
          contents: 
            - href: FNA/DAL/DAL_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FNA/DAL/Dico_FNA_DAL/DAL_dictionnaire.qmd
              - href: FNA/DAL/Dico_FNA_DAL/FNA_DAL_variables/KCDAL.qmd
              - href: FNA/DAL/Dico_FNA_DAL/FNA_DAL_variables/KCNDDA.qmd
        - section: "PAF"
          contents: 
            - href: FNA/PAF/PAF_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FNA/PAF/Dico_FNA_PAF/PAF_dictionnaire.qmd
              - href: FNA/PAF/Dico_FNA_PAF/FNA_PAF_variables/KCNPL.qmd
        - section: "CDT"
          contents: 
            - href: FNA/CDT/CDT_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FNA/CDT/Dico_FNA_CDT/CDT_dictionnaire.qmd
              - href: FNA/CDT/Dico_FNA_CDT/FNA_CDT_variables/KCMCA.qmd
              - href: FNA/CDT/Dico_FNA_CDT/FNA_CDT_variables/KCMET.qmd
        - section: "PAR"
          contents: 
            - href: FNA/PAR/PAR_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FNA/PAR/Dico_FNA_PAR/PAR_dictionnaire.qmd
        - section: "IND"
          contents: 
            - href: FNA/IND/IND_presentation.qmd
        - section: "PRM"
          contents: 
            - href: FNA/PRM/PRM_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: FNA/PRM/Dico_FNA_PRM/PRM_dictionnaire.qmd
  

            
    - title: "Allstat-FR6"
      style: "docked"
      background: light
      contents: 
        - section: "Présentation"
          contents: 
            - Allstat_FR6/Allstat_FR6_presentation.qmd
        - section: "Prestations"
          contents: 
            - href: Allstat_FR6/Prestations/prestations_presentation.qmd
            - section: "Dictionnaire"
              contents: 
              - href: Allstat_FR6/Prestations/Dico_allstat_minima/prestations_dictionnaire.qmd
              - href: Allstat_FR6/Prestations/Dico_allstat_minima/allstat_minima_variables/rsocclog.qmd
        - section: "Ménages"
          contents:
            - href: Allstat_FR6/Menages/menages_presentation.qmd
            - section: "Dictionnaire"
              contents:
              - href: Allstat_FR6/Menages/Dico_allstat_foyers/menages_dictionnaire.qmd
              - href: Allstat_FR6/Menages/Dico_allstat_foyers/allstat_foyers_variables/actrespd.qmd
              - href: Allstat_FR6/Menages/Dico_allstat_foyers/allstat_foyers_variables/regrespd.qmd


    - title: "DSN"
      style: "docked"
      background: light
      contents: 
        - section: "Présentation"
          contents: 
            - DSN/DSN_presentation.qmd
            
        - section: "MMO"
          contents: 
            - href: DSN/MMO/mmo_presentation.qmd
            - section: "Dictionnaire"
              contents: 
                - href: DSN/MMO/Dico_mmo/mmo_dictionnaire.qmd
                - href: DSN/MMO/Dico_mmo/mmo_variables/MotifRecours.qmd
                - href: DSN/MMO/Dico_mmo/mmo_variables/MotifRupture.qmd
                - href: DSN/MMO/Dico_mmo/mmo_variables/Nature.qmd
                - href: DSN/MMO/Dico_mmo/mmo_variables/SalaireBase.qmd
        - section: "BTS"
          contents:
            - href: DSN/BTS/BTS_presentation.qmd
            - section: "Dictionnaire"
              contents:
              - href: DSN/BTS/Dico_BTS/BTS_dictionnaire.qmd
          
    - title : "Fiches"
      style: "docked"
      background: light
      contents:
          - href: Fiches/Fiches_presentation.qmd
          - href: Fiches/Cluster_spark.qmd
          - href: Fiches/Retour_emploi_rsa.qmd
          - href: Fiches/Maintien_de_droits.qmd
          - href: Fiches/Allocations_regimes.qmd
          - href: Fiches/Parcours_indemnisation.qmd
          - href: Fiches/Differe_indemnisation.qmd
          - href: Fiches/Activité réduite.qmd
          - href: Fiches/Foyers_BRSA.qmd
          - href: Fiches/Cumul_AC_MS.qmd
            


format:
  html:
    theme: pulse
    toc: true

editor: visual

