---
title: "Dictionnaire des variables"
---

| <br>Variables | <br>Libellé                                                                                                                                                                   | <br>Modalités                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | <br>Commentaires                                                                                                                                |
|---------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------|
| <br>D2STATUT  | <br>Indicateur du niveau de consolidation <br>de l'information portant sur <br>l'indemnisabilité du demandeur                                                                 | <br>C. Information consolidée <br>à 12 mois<br> <br>P. Information consolidée <br>à 3 mois, dite provisoire                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | <br>                                                                                                                                            |
| <br>FILINDEM  | <br>Identifie les conditions d'indemnisation <br>(durée, taux) en fonction des conditions <br>d'affiliation (durée, convention et âge <br>à la rupture du contrat de travail) | <br>1. 122j d'indemnisation 27A<br> <br>2. 182j d'indemnisation 27B<br> <br>3. 243j d'indemnisation 27C <br>moins de 50 ans<br> <br>4. 243j d'indemnisation 27C <br>50 ans et plus<br> <br>5. 426j d'indemnisation 27D <br>moins de 25 ans<br> <br>6. 426j d'indemnisation 27D <br>entre 25 et 50 ans<br> <br>7. 426j d'indemnisation 27D <br>50 ans et plus<br> <br>8. 821j d'indemnisation 27E <br>entre 50 et 55 ans<br> <br>9. 821j d'indemnisation 27E <br>55 ans et plus<br> <br>99. Sans objet<br> <br>A-F. Filière ARE 2003<br> <br>G.<br> <br>H.<br> <br>I.<br> <br>J. | <br>                                                                                                                                            |
| <br>JOURDV    | <br>Jour de début de validité                                                                                                                                                 | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | <br>                                                                                                                                            |
| <br>JOURFV    | <br>Jour de fin de validité                                                                                                                                                   | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | <br>                                                                                                                                            |
| <br>NDEM      | <br>Numéro de la demande                                                                                                                                                      | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | <br>Numéroté de la plus récente <br>à la plus ancienne (la demande <br>n°1 est la demande la plus <br>récente à la date statistique <br>du FHS) |
| <br>ODDDMAX   | <br>Durée maximale d'indemnisation                                                                                                                                            | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | <br>                                                                                                                                            |
| <br>REGIME    | <br>Régime particulier                                                                                                                                                        | <br>0. Indéterminé<br> <br>1. Régime général<br> <br>2. Intermittents du spectacle<br> <br>3. Autres intermittents et <br>intérimaires<br> <br>4. Autres régimes                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                            |
| <br>REGIND    | <br>Régime d'indemnisation                                                                                                                                                    | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | <br>                                                                                                                                            |
| <br>REGION    | <br>                                                                                                                                                                          | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | <br>                                                                                                                                            |
| <br>TYPEPOP   | <br>Type de population                                                                                                                                                        | <br>0. Non renseigné<br> <br>1. Ancien emploi jeune                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | <br>                                                                                                                                            |
| <br>indem     | <br> Code de l'allocation du demandeur <br> d'emploi indemnisable                                                                                                             | <br>Les modalités sont disponibles dans la [section détaillée](FHS_D2_variables/INDEM.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                 |
