---
title: "Dictionnaire des variables"
---

+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>Variables | <br>Libellé                                                           | <br>Modalités                                                                                                                                                                                                                                                                                                                                                           |
+===============+=======================================================================+=========================================================================================================================================================================================================================================================================================================================================================================+
| <br>CATFIN    | <br>Catégorie de financement de la formation                          | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_P2_variables/CATFIN.qmd).                                                                                                                                                                                                                                                                           |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>COUTGLO   | <br>Coût global de la formation                                       | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>COUTSTA   | <br>Coût stagiaire de la formation                                    | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>DATSTAT   | <br>Mois statistique                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>DECAFFD   | <br>Décision AFFD (Allocation de Fin de <br>Formation Dérogatoire)    | <br>O. Oui<br> <br>N. Non                                                                                                                                                                                                                                                                                                                                               |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>FORMACOD  | <br>Besoin en formation - domaine                                     | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_P2_variables/FORMACOD.qmd).                                                                                                                                                                                                                                                                         |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>FORTYPE1  | <br>Type de formation PARE (Plan d'aide <br>au retour à l'emploi)     | <br>C. Conventionnée<br> <br>P. Homologuée prioritaire<br> <br>H. Homologuée par défaut<br> <br>N. Non homologuée<br> <br>A. Convention AFPE<br> <br>X. Non renseigné                                                                                                                                                                                                   |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>NUMAIS    | <br>Numéro d'Attestation d'inscription \*<br>en stage (AIS)           | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>OBJFORM   | <br>OBJECTIF DE LA FORMATION <br>(qualification, perfectionnement...) | <br>0. Non concerné<br>                                                                                                                                                                                                                                                                                                                                                 |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>1. Qualification<br>                                                                                                                                                                                                                                                                                                                                                |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>2. Perfectionnement<br>                                                                                                                                                                                                                                                                                                                                             |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>3. Élargissement des compétences<br>                                                                                                                                                                                                                                                                                                                                |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>4. Création d'entreprise<br>                                                                                                                                                                                                                                                                                                                                        |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>5. Remise à niveau<br>                                                                                                                                                                                                                                                                                                                                              |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>6. Mobilisation sur un projet<br>                                                                                                                                                                                                                                                                                                                                   |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>7. Préqualification<br>                                                                                                                                                                                                                                                                                                                                             |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>9. Non précisé<br>                                                                                                                                                                                                                                                                                                                                                  |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>A. Certification<br>                                                                                                                                                                                                                                                                                                                                                |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>B. Professionnalisation<br>                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>C. Préparation à la qualification<br>                                                                                                                                                                                                                                                                                                                               |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>D. Remise à niveau, maîtrise des savoirs<br>                                                                                                                                                                                                                                                                                                                        |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>E. Mobilisation, aide à l'élaboration de projet<br>                                                                                                                                                                                                                                                                                                                 |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>F. PERFECTIONNEMENT, ELARGISS. CO<br>                                                                                                                                                                                                                                                                                                                               |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>G. Création d'entreprise<br>                                                                                                                                                                                                                                                                                                                                        |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>X. Non précisé<br>                                                                                                                                                                                                                                                                                                                                                  |
|               |                                                                       |                                                                                                                                                                                                                                                                                                                                                                         |
|               |                                                                       | <br>Z. Non concerné<br>                                                                                                                                                                                                                                                                                                                                                 |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>ORGCAT    | <br>Catégorie de l'organisme de formation                             | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_P2_variables/ORGCAT.qmd).                                                                                                                                                                                                                                                                           |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>P2DATDEB  | <br>Date de début                                                     | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>P2DATFIN  | <br>Date de fin                                                       | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>P2NBHEUR  | <br>Nombre d'heures total                                             | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>P2NIVFOR  | <br>Niveau de la formation                                            | <br>0. Inconnu ou non renseigné<br> <br>1. Supérieur à BAC+2<br> <br>2. De niveau BAC+2 à BAC+2<br> <br>3. De niveau BAC, BP, BM à BAC<br> <br>4. De CAP, BEP à 1ère achevé<br> <br>5. De premier cycle <br>professionnel, BEPC 3ème achevé<br> <br>6. De sans formation, primaire <br>à 4ème achevé                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>PERENTRE  | <br>Période passée en entreprise lors <br>de la formation             | <br>O. Le demandeur a effectué <br>a travaillé en entreprise<br> <br>N. Le demandeur n'a <br>pas travaillé en entreprise                                                                                                                                                                                                                                                |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>PERETRAN  | <br>Période passé à l'étranger lors <br>de la formation               | <br>O. Le demandeur a effectué <br>un séjour à l'étranger<br> <br>N. Le demandeur n'a pas <br>effectué de séjour à l'étranger                                                                                                                                                                                                                                           |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>REGION    | <br>                                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>SIRET     | <br>SIRET DE L'ORGANISME REALISANT <br>LA PRESTATION                  | <br>                                                                                                                                                                                                                                                                                                                                                                    |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>TYPVALID  | <br>TYPE DE VALIDATION                                                | <br>0. NON PREVU<br> <br>1. DIPL. TECHN. EDUC. NATIONALE<br> <br>2. DIPL. TECHN. TRAVAIL<br> <br>3. DIPL. TECHN. AGRICULTURE<br> <br>4. DIPL. TECHN. JEUNES. ET SPORTS<br> <br>5. DIPL. TECHN. AUTRES<br> <br>6. TITRE OU DIPLOME HOMOLOGUE<br> <br>7. QUALIF. RECONNUE CONV. COLLECT<br> <br>8. QUALIF. RECONNUE COMM. PARIT.<br> <br>9. TITRE OU DIPL. EN ELABORATION |
+---------------+-----------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
