---
title: "Dictionnaire des variables"
---

|    <br>Nom Oracle (SAS)    | <br>Nom segment |                                                     <br>Libellé                                                     |                                                                                                                                                                                                                                                                                                                                          <br>Description                                                                                                                                                                                                                                                                                                                                          | <br>Modalités                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|:----------:|:----------:|:-------------:|:---------------------:|---------------------|
|         <br>KCCT1          |   <br>ODDID1    |                                       <br>IDENTIFIANT PERIODE FAIT GENERATEUR                                       |                                                                                                                                                                                                                                                                                                        <br>Identifiant du fait générateur, permettant la jonction avec KCCT du segment CDT                                                                                                                                                                                                                                                                                                        | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         <br>KCRGC          |   <br>ODDREG    |                                                 <br>CODE REGIME OD                                                  |                                                                                                                                                                                                                                                                                                                             <br>Code Régime de l'ouverture de droit.                                                                                                                                                                                                                                                                                                                              | <br>1. RAC<br> 2. RSN<br> 3. PRERETRAITE<br> 4. ASC<br> 5. RSP<br> 6. FSP<br> X. Valeur hors table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|         <br>KCRRD          |  <br>ODDDFLAG   |                                <br>INDICATEUR DE READMISSION OU NOUVEAUX TYPES D'ODD                                |                                                                                                                                                                                                                                                                 <br>Flag de réadmission, calculé à partir des règles de réadmission de la Convention 2006. Cette rubrique permet le suivi et l'analyse des droits en réadmission.                                                                                                                                                                                                                                                                 | <br>0. Pas de nouvelle réadmission<br> 1. Réadmission de l'ancien droit (capital et montant)<br> 2. Droit courant retenu (capital et montant)<br> 3. Réadmission avec capital de l'OD courante et montant du droit précédent<br> 4. Réadmission avec capital de l'OD précédente et montant du droit courant<br> 5. OD suite à Rechargement avec condition minimale (AC 2014)<br> 6. OD suite à perte d'une activité conservée (AC 2014)<br> 7. OD suite à Rechargement de droit commun pour les apprentis (Avenants AC 2014)<br> 8. OD suite à Rechargement de droit commun hors apprentis (Avenants AC 2014 droit d'option élargi) |
|         <br>KCTPP          |   <br>ODDTPAR   |                                       <br>COEFFICIENT REDUCTION TEMPS PARTIEL                                       | <br>Cette rubrique décrit le coefficient réducteur calculé en fonction de l'horaire de travail pratiqué par l'individu.<br> Il servira à réduire la partie fixe. Selon le régime applicable, ce coefficient sera calculé de la façon suivante :<br> Del 27 du régime général : ce coefficient est égal au rapport des heures de travail correspondant à l'horaire de l'individu pendant la période servant au calcul du salaire de référence sur l'horaire légal ou horaire de la convention ou de l'accord collectif correspondant à la même période.<br> Art 25 de l'Annexe 12 ce coefficient est égal au rapport du nombre d'heures de travail effectué pendant les 12 derniers mois sur 1815. |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KCTRSP         |      <br>       |                                            <br>COEFFICIENT REDUCTEUR SJR                                            |                                                                                                                                                                                                                                                                                                                                               <br>                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         <br>KDDDFE         |   <br>ODDDDFE   |                                         <br>DATE DE DEBUT DE DIFFERE A8A10                                          |                                                                                                                                                                                                                                                                                                                    <br>Il s'agit de la date de début du différé des A8 et A10                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KDDPRC         |  <br>ODDDTDPR   |                                         <br>DATE DEBUT PERIODE DE REFERENCE                                         |                                                                                                                                                                                                                                                                                                       <br>Cette rubrique précise la date de début de la PRC (Période de référence calcul).                                                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KDDRA          |  <br>ODDDDPRA   |                                             <br>DATE DE DEBUT DE LA PRA                                             |                                                                                                                                                                                                                                                                                                          <br>Il s'agit de la date de début de la PRA (Période de Référence Affiliation)                                                                                                                                                                                                                                                                                                           |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KDFOD          |   <br>ODDDTFD   |                                            <br>DATE THEORIQUE FIN DROIT                                             |                                                                                                                                                                                                                                         <br>Date théorique de fin de droit pour l'allocataire actualisée au dernier calcul tenant compte du reliquat de droit et bornée par la date de retraite. Cette date n'est renseignée que pour le droit en cours.                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KDJRSJ         |  <br>ODDDTFPR   |                                          <br>DATE FIN PERIODE DE REFERENCE                                          |                                                                                                                                                                                                                                                        <br>C'est le dernier jour de la PRC (Période de Référence Calcul) ayant servi à la détermination du Salaire de Référence. Cette date sert de base pour les revalorisations du SJR.                                                                                                                                                                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KDMAI          |  <br>ODDDTMNT   |                                       <br>DATE DE MAINTIEN JUSQU'EN RETRAITE                                        |                                                                                                                                                                                                                                                                                                                    <br>Date d'enregistrement du maintien jusqu'à la retraite.                                                                                                                                                                                                                                                                                                                     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KDPMA          |   <br>ODDDTPP   |                                       <br>DATE DU 1ER PAIEMENT DANS LE DROIT                                        |                                                                                                                                                                                                                            <br>Date du premier versement en Assurance Chômage. Cette date n'est pas modifiée par une remise en cause issue du calcul. Plus concrètement, c'est la valeur que prend KDPOD (1er jour indemnisé) pour la première fois (date comptable).                                                                                                                                                                                                                             |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KDPOD          |  <br>ODDDTPJI   |                                      <br>DATE 1ER JOUR INDEMNISE DANS LE DROIT                                      |                                                                                                                                                                                                                                                            <br>Date de début d'indemnisation de l'allocataire. C'est la date du premier jour indemnisé de l'ouverture de droit. Elle est recalculée à chaque remise en cause du droit.                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KDRPRA         |      <br>       |                                       <br>DATE DU 1ER JOUR DU 1ER CONTRAT PRA                                       |                                                                                                                                                                                                                                                                                                                                               <br>                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         <br>KNCTS          |   <br>ODDNCTS   |                          <br>Numéro séquentiel des contrats de travail rattachés à une OD                           |                                                                                                                                                                                                                                                                              <br>Clef de jonction avec KNCTE (CDTNUM) du segment CONTRAT DE TRAVAIL (CDT)<br> Clef de jonction avec les segments suivants : CDT/ODD                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KNFILD         |   <br>ODDFILD   |                                      <br>CODE FILIERE INDEMNISATION THEORIQUE                                       |                                                                                                                                                                                                                                                                      <br>Code filière de l'article 27 de l'annexe au règlement à la Convention du 1/01/94 avant comparaison de capitaux. Filière relative au droit consommé.                                                                                                                                                                                                                                                                      | <br>Cf. KNFIL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
|         <br>KNJCPP         |      <br>       |                                        <br>NOMBRE DE JOURS FRANCHISE CONGES                                         |                                                                                                                                                                                                                                                                                                                                               <br>                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         <br>KNJECP         |      <br>       |                                <br>Nombre de jours d'écrêtement de la durée du droit                                |                                                                                                                                                                                                                                                                                                                                               <br>                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         <br>KPJDFP         |      <br>       |                                 <br>Nombre de jours de différé des annexes 8 et 10                                  |                                                                                                                                                                                                                                                                                                                                               <br>                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         <br>KPJDXP         |   <br>ODDDMAX   |                                       <br>DUREE MAXIMALE INDEMNISATION DROIT                                        |                                                                                                                                                                                                                                                                           <br>Durée maximale d'indemnisation du droit. Cette durée est exprimée en jours. Elle permet le suivi et l'analyse des droits en réadmission.                                                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KPMODP         |      <br>       |                             <br>DUREE MAXIMALE DE L'NDEMNISATION A L'OUVERRTUE DU DROIT                             |                                                                                                                                                                                                                                                                                                                                               <br>                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         <br>KQBFRP         |      <br>       |                                      <br>Salaire brut non plafonné sur la PRC                                       |                                                                                                                                                                                                                                                                                                                                               <br>                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
|         <br>KQCSJP         |   <br>ODDSJR    |                                               <br>MONTANT RETENU SJR                                                |                                                                                                                                                                                                                                                <br>Le montant du SJR retenu est le salaire journalier de référence plafonné et revalorisé. Il est égal au Salaire de référence divisé par le nombre de jours retenus pour la période de Référence.                                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KQDIFP         |  <br>ODDMTDIF   |                                          <br>MONTANT INDEMNITES ICCP ISLR                                           |                                                                                                                                                                                                                                                                <br>Il s'agit du montant des indemnités ICCP (Indemnités Compensatrices de Congés Payés) et ISLR (Indemnités Supra Légales Réglementaires) pour calcul du différé.                                                                                                                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KQICPP         |  <br>ODDMTICP   |                                             <br>MONTANT INDEMNITES ICCP                                             |                                                                                                                                                                                                                                                                                                                <br>Il s'agit du montant des indemnités ICCP pour calcul du différé                                                                                                                                                                                                                                                                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KQISLP         |  <br>ODDMTISL   |                                             <br>MONTANT INDEMNITES ISLR                                             |                                                                                                                                                                                                                                                                                                              <br>Il s'agit du montant des indemnités ISLR pour le calcul du différé                                                                                                                                                                                                                                                                                                               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KQSPRP         |      <br>       |                                     <br>SOMME DES SALAIRES RETENUE DANS LA PRA                                      |                                                                                                                                                                                                                                                                                                                                               <br>                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| <br>KROD1<br> <br>\[KROD\] |  <br>ODDIDENT   |                                       <br>IDENTIFIANT DE L'OUVERTURE DE DROIT                                       |                                                                                                                                                                     <br>Référence de l'OD portant le fait générateur. Il s'agit du droit courant, c'est à dire du droit ouvert.<br> Le droit ouvert peut ne pas être le droit consommé.<br> Clef de jonction avec KROD3 (ODDIDENT) du segment PERIODE JUSTIFICATION CONSTATNTE (PJC) - segment LN2P<br> Clef de jonction avec KROD1 (ODDIDENT) du segment DAL - segment LN1N                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|         <br>KROD2          |  <br>ODDRARET   | <br>Référence de l'OD portant le fait générateur (référence de l'OD retenue en cas de reprise d'un droit précédent) |                                                                                                                                                                                                                                          <br>Clef de jonction avec KROD1 (ODDIDENT) du segment DEMANDE D'ALLOCATION (DAL)<br> Clef de jonction avec KROD (ODIDENT) du segment RELIQUAT DROIT (RDD)<br> Clef de jonction avec les segments suivants : ODD                                                                                                                                                                                                                                          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
