---
title: "Les Mouvements de Main d'Oeuvre (MMO)"
---

La Dares fournit les données de Mouvements de Main-d'œuvre (MMO)[^1] tirées de la Déclaration sociale nominative (DSN), qui permet de suivre l'ensemble des contrats salariés des demandeurs d'emploi et bénéficiaires de minima sociaux. La DSN repose sur la transmission unique, mensuelle et dématérialisée des données issues de la paie et sur des signalements d'événements. Plus précisément, la DSN remplace depuis 2017 la déclaration annuelle de données sociales unifiée (DADS-U) dans la plupart des entreprises afin d'unifier les déclarations et démarches relatives à la gestion de la protection sociale des employés, autrefois adressées à une diversité d'acteurs (CPAM, Urssaf, AGIRC ARRCO, Organismes complémentaires, Pôle emploi, Centre des impôts, Caisses de régimes spéciaux...).

[^1]: Cette partie est issue de la documentation ForCE (Formation, Chômage Emploi), les données MMO transmises au CASD pour ces deux appariements étant identiques.

Le champ des contrats couverts par la DSN est progressivement élargi, ce qui crée une rupture de champ :

-   Tous les salariés du privé (à l'exception de certains salariés agricoles, voir ci-dessous) sont couverts par la DSN depuis janvier 2017 (exhaustif depuis 2018) et figurent dans le fichier statistique transmis ;

-   L'intégration des salariés de la fonction publique en DSN a été prévue en trois vagues : 1er janvier 2020, 1er janvier 2021 et 1er janvier 2022. Plus précisément, une grande partie de la Fonction Publique Territoriale a été intégrée en 2021 alors qu'il y a encore peu de déclarations de la Fonction Publique Hospitalière et de la Fonction Publique d'État. L'intégration pour le reste de la fonction publique est massive en 2022. En 2022, 67 000 Siret de l'ensemble de la fonction publique sur 70 000 (au moins 95 %) sont entrés en DSN. Le reste est attendu en janvier 2023 : 2 500 établissements sont concernés, dont près de 1 000 établissements avec un effectif nul. [L'intégration de la fonction publique concerne uniquement les contrats en cours et non ceux qui sont terminés : les données relatives aux contrats de la fonction publique ne sont donc pas exhaustives. L'exhaustivité ne peut être assurée que pour les contrats toujours actifs en 2022 ou ayant une date de début ultérieure. Les données MMO couvrant les contrats entre 2017 et 2021 intègrent donc les contrats de la fonction publique qui sont toujours en cours en 2022 et ayant une date de début antérieure au 31/12/2021. Les contrats terminés avant le 31/12/2021 ne sont pas intégrés ;]{.underline}

-   Une partie de l'emploi agricole n'est pas intégrée en DSN. Il s'agit des contrats déclarés à l'aide des « Titres emploi simplifié agricole » (Tesa), dispositif géré par la MSA (Mutualité Sociale Agricole : sécurité sociale des agriculteurs et des salariés agricoles) pour faciliter la déclaration des salariés en CDD et des travailleurs occasionnels des TPE rattachées au régime agricole. Le calendrier sous lequel les Tesa pourraient être intégrés en DSN n'est pas connu à ce jour ;

-   Pour les particuliers employeurs, pas de calendrier prévu pour leur entrée en DSN.

Plusieurs tables MMO sont transmises selon la période de référence considérée. [L'unité statistique des tables est celle du contrat]{.underline} : chaque table contient une ligne pour tout contrat actif au moins un jour sur la période de référence. Plusieurs lignes peuvent correspondre à un même individu si celui-ci a eu plusieurs contrats sur la période de référence. Les contrats sont qualifiés selon leur modalité active au dernier jour de la période de référence.

[Exemple]{.underline} : la table « 2017 » contient les contrats actifs au moins un jour sur l'année 2017, c'est-à-dire ayant une date de début antérieure au 1er janvier 2018 et une date de fin postérieure au 31 décembre 2016 ou manquante si le contrat est en cours. La PCS renseignée est la PCS du contrat au 31/12/2017.

Un contrat actif sur plusieurs périodes de référence (par exemple 2017 et 2018) peut être identifié via l'identifiant du contrat (L_CONTRAT_SQN). Sur une période donnée, les contrats dont l'identifiant L_CONTRAT_SQN est vide sont des contrats inactifs sur cette période (mais actifs sur une autre période).

[Exemple]{.underline} : un contrat actif sur les années 2017 et 2018 (date de début ≤ 31.12.2017 et 01.01.2018 ≤ date de fin ≤ 31.12.2018) sera présent dans toutes les tables mais identifiable via son identifiant L_CONTRAT_SQN dans les tables 2017 et 2018 uniquement.
