---
title: "Le Fichier National des Allocataires (FNA)"
---

Le **Fichier National des Allocataires de France Travail** suit les **trajectoires d'indemnisation** des personnes allocataires de l'assurance-chômage. Il contient notamment toutes les informations nécessaires pour calculer cette indemnisation : période d'affiliation, salaire journalier de référence, durée d'indemnisation potentielle...

## Champ

**Personnes** **indemnisables au moins 1 jour depuis le 1er janvier 2017**. Pour ces individus, MiDAS contient **tout l'historique de leur indemnisation** depuis 1993, ainsi que leurs périodes d'affiliation et d'activité réduite.

## Structure des tables

Dans le cadre de MiDAS, les données sélectionnées sont issues de 8 segments du FNA :

-   Le segment **« [Individu](IND/IND_presentation.qmd) » (IND, LN4A)** : table centrale qui fait la jonction avec les autres tables, au niveau de l'individu ;

-   Le segment **« [Contrat de travail](CDT/CDT_presentation.qmd) » (CDT, LN4E)** indique la nature du dernier contrat de travail avant l'ouverture du droit (fait générateur) et son motif de fin ;

-   Le segment **« [Période d'affiliation](PAF/PAF_presentation.qmd) » (PAF, LN2L)** : pour un droit, cette table contient l'ensemble des évènements (contrats de travail, périodes de formations, arrêts maladie...) connus d'un individu, indiqués par une date de début (KDDPE) et une date de fin (KDFPE). Si ces variables sont identiques à celles présentes dans CDT, elles ne renvoient pas nécessairement à un contrat car le « champ » de PAF est plus large que celui de CDT. L'ensemble des contrats ayant permis l'ouverture de droit peuvent être repérés grâce à KCFPL et sont exprimés en heures alors que les arrêts maladie sont exprimés en jours (KCAFF) ;

-   Le segment **« [Demande d'allocation](DAL/DAL_presentation.qmd) » (DAL, LN1N)** : table qui renseigne sur les demandes d'allocation (type de demande, nombre de jours de différés, demandes rejetées) rattachées aux droits ouverts. Cette table contient toutes les demandes, y compris celles qui n'ont pas débouché sur une ouverture de droit ;

-   Le segment **« [Ouverture de droit](ODD/ODD_presentation.qmd) » (ODD, LN1S)** : cette table fournit les caractéristiques du droit ouvert. Une ligne correspond à un droit. On distingue plusieurs situations :

    -   *L'ouverture et la fin de droit* : lorsque la demande allocation est acceptée, le demandeur d'emploi peut s'ouvrir un droit (KCNDDA = 01 dans la table DAL). Les paramètres de l'indemnisation associés au droit sont renseignés par les dates de PJC (KDDPJ et KDFPJ) ;

    -   La *reprise de droit*, qui n'entraîne pas de nouveau droit (pas de nouveau KROD, l'identifiant du droit) : elle peut être identifiée dans DAL (KCNDDA = 03) et dans PJC (KCOPP = 20) ;

    -   Le *rechargement de droit* (anciennement « réadmission »), entraîne un nouveau droit (une nouvelle ligne avec un nouveau KROD) : il peut être identifié dans DAL (KCDAL = 26 ; KCNDDA = 10), ODD (KCRRD) et dans PJC (KCOPP = 02).

-   Le segment **« [Période à justification constante](PJC/PJC_presentation.qmd) » (PJC, LN2P)** contient de nombreuses informations permettant de calculer le nombre d'indemnisables et d'indemnisés un mois donné (date de début et de fin de PJC, PJC payée ou non, motif d'ouverture et de fermeture de la PJC, allocation, SJR et montant d'allocation). Pour chaque droit, cette table contient une ligne par PJC, qui est la plus petite unité de temps qui découpe un droit. Le passage d'une PJC à une autre est dû au changement de type de PJC (KCPJC) : si la PJC n'est pas payée, on connaît le motif de son non paiement (KCMNI). Si celle-ci n'est ni payée ni consommé (KCPJC = 3), c'est qu'elle est reportée, en raison principalement de l'exercice d'une activité réduite ;

-   Le segment **« [Prime versée](PRM/PRM_presentation.qmd) » (PRM, LN3M)** contient les aides et primes versées aux allocataires de l'assurance-chômage ;

-   Le segment **« [Période d'activité réduite](PAR/PAR_presentation.qmd) » (PAR, LN2K)** renseigne sur l'activité réduite (nombre d'heures, salaire brut et périodes).

## Le "parcours de l'indemnisation" à France Travail

Un personne qui s'inscrit à France Travail apparaît dans la table DE du FHS. Ensuite, pour pouvoir être indemnisée :

-   Elle effectue une demande d'allocation (table DAL) qui peut être acceptée ou rejetée ;

-   La DAL est acceptée si la personne a suffisamment travaillé : la table CDT (contrat de travail) renseigne sur son dernier contrat ayant permis l'ouverture de droit. En complément, la table PAF (période d'affiliation) renseigne sur l'ensemble des évènements connus par la personne, ce qui inclut les contrats de travail (information à mettre en regard avec les MMO) mais aussi les périodes de formation et d'arrêt de travail ;

-   Une fois la DAL acceptée, la personne peut s'ouvrir un droit à l'assurance-chômage, dont les caractéristiques sont présentes au sein de la table ODD (ouverture de droit) ;

-   Pour chaque droit ouvert, est associée une ou plusieurs périodes à justification constante (PJC) pendant lesquelles les paramètres de l'indemnisation restent inchangés.

L'activité réduite : l'information sur les allocataires de l'assurance-chômage qui travaillent est renseignée dans le FHS (table E0) et dans le FNA (table PAR). Deux différences sont à noter entre ces deux tables :

-   Seule la table PAR renseigne sur le salaire brut perçu dans le cadre d'une activité réduite (variable KQBARP) ;

-   La table E0 ne contient que les heures d'activité réduite des personnes inscrites en catégories B ou C.
