---
title: "KCNPL"
---

Cette rubrique définit la nature d'une période du passé professionnel. Pour Athéna Est, cette rubrique est disponible pour les Annexes 2 et 8. Pour les Annexes, la nature de période se décompose en : "A" Valeur constante "X" Numéro de l'Annexe "99" Code numérique sur 2 positions qui correspond à la qualification de l'individu au niveau de l'annexe

**AGRI**. EXPLOITANT AGRICOLE

**AHC**. ACTIVITE HORS CHAMPS

**AIDH**. ASSISTANCE A UNE PERSONNE HANDICAPEE

**APETP**. ALLOC PARENTALE EDUCATION À TAUX PLEIN

**APETR**. ALLOC PARENTALE EDUCATION A TAUX REDUIT

**APPR**. PERIODE D'APPRENTISSAGE

**ART**. SITUATIONS PARTICULIERES DE L'ASS

**AT**. ACCIDENT DU TRAVAIL

**A1AM**. ACTIVITE SALARIEE ANNEXE 1 (ASS.MATERN.)

**A1BUC**. ACTIVITE SALARIEE ANNEXE 1 (BUCHERON)

**A1JOUR**. ACTIVITE SALARIEE ANNEXE 1 (JOURNALISTE)

**A1NAV**. ACTIVITE SALARIEE ANNEXE 1 (NAVIGANT)

**A1VRP**. ACTIVITE SALARIEE EN ANNEXE 1 (VRP)

**A10**. ACTIVITE SALARIEE EN ANNEXE 10

**A11**. ACTIVITE SALARIEE EN ANNEXE 11

**A12**. ACTIVITE SALARIEE EN ANNEXE 12

**A2C**. ACTIVITE SALARIEE EN A2 (MARIN COMMERCE)

**A2P01**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 01)

**A2P02**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 02)

**A2P03**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 03)

**A2P04**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 04)

**A2P05**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 05)

**A2P06**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 06)

**A2P07**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 07)

**A2P08**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 08)

**A2P09**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 09)

**A2P10**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 10)

**A2P11**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 11)

**A2P12**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 12)

**A2P13**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 13)

**A2P14**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 14)

**A2P15**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 15)

**A2P16**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 16)

**A2P17**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 17)

**A2P18**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 18)

**A2P19**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 19)

**A2P20**. ACTIVITE SALARIEE A2 (PECHEUR CATEG. 20)

**A3**. ACTIVITE SALARIEE EN ANNEXE 3

**A423**. ACTIV. SALARIEE EN ANNEXE 4 (INTERMIT.)

**A424**. ACTIV. SALARIEE EN ANNEXE 4 (INTERIM.)

**A5**. ACTIVITE SALARIEE EN ANNEXE 5

**A6**. ACTIVITE SALARIEE EN ANNEXE 6

**A7**. ACTIVITE SALARIEE EN ANNEXE 7

**A8**. ANNEXE 8

**A8B0**. AUDIO: REALISATEUR TELEVISION

**A8B1**. AUDIO: CONCEPTEUR REALISATEUR VIDEO

**A8B2**. AUDIO: CHEF DE PRODUCTION

**A8B3**. AUDIO: CHARGE DE PRODUCTION

**A8B4**. AUDIO: DIRECTEUR DE LA PHOTOGRAPHIE

**A8B5**. AUDIO: CHEF DECORATEUR

**A8B6**. AUDIO: CHEF OPERATEUR DE PRISE DE SON

**A8B7**. AUDIO: ASSISTANT REALISATION 1ER CATEG.

**A8B8**. AUDIO: ASSISTANT REALISATION 2EM CATEG.

**A8B9**. AUDIO: CHEF OPERATEUR DE PRISE DE VUES

**A8C0**. AUDIO: CADREUR

**A8C1**. AUDIO: CADREUR VIDEO

**A8C2**. AUDIO: DECORATEUR

**A8C3**. AUDIO: DECORATEUR ANIMATION

**A8C4**. AUDIO: DECORATEUR COSTUMIER

**A8C5**. AUDIO: DECORATEUR GRAPHISTE

**A8C6**. AUDIO: DECORATEUR SCULPTEUR

**A8C7**. AUDIO: DECORATEUR PEINTRE

**A8C8**. AUDIO: DESSINATEUR DE DECORATION

**A8C9**. AUDIO: PEINTRE DECORATEUR

**A8D0**. AUDIO: REGISSEUR D'EXTERIEUR

**A8D1**. AUDIO: ASSISTANT ASSEMBLIER

**A8D2**. AUDIO: ACCESSOIRISTE

**A8D3**. AUDIO: TAPISSIER DECORATEUR

**A8D4**. AUDIO: TAPISSIER

**A8D5**. AUDIO: TAPISSIER EN DECORATION

**A8D6**. AUDIO: DECORATEUR ENSEMBLIER

**A8D7**. AUDIO: ENSEMBLIER

**A8D8**. AUDIO: CHEF MAQUILLEUR POSTICHEUR

**A8D9**. AUDIO: OUVRIERS DE PLATEAU (COIFFEUR...)

**A8E0**. AUDIO: COIFFEUR PERRUQUIER

**A8E1**. AUDIO: CHEF MONTEUR DE FILMS

**A8E2**. AUDIO: ASSISTANT MONTEUR DE FILMS

**A8E3**. AUDIO: ADJOINT DE PRODUCTEUR

**A8E4**. AUDIO: AGENT SPECIALISE D'EMISSION

**A8E5**. AUDIO: DIRECTEUR DE CASTING

**A8E6**. AUDIO: CREATEUR DE COSTUMES

**A8E7**. AUDIO: STYLISTE

**A8E8**. AUDIO: COSTUMIER

**A8E9**. AUDIO: HABILLEUSE

**A8F0**. AUDIO: OPERATEUR DE PRISES DE VUES

**A8F1**. AUDIO: OPERATEUR BANC-TITRE

**A8F2**. AUDIO: OPERATEUR VIDEO

**A8F3**. AUDIO: AGENT DE PRISES DE VUES

**A8F4**. AUDIO: ASSISTANT VIDEO

**A8F5**. AUDIO: OPERATEUR PRISES DE VUES (PHOTO)

**A8F6**. AUDIO: OPERATEUR DE PRISES DE SON

**A8F7**. AUDIO: SYNTHETISEUR

**A8F8**. AUDIO: ASSISTANT DE REALISATION (SCRIPT)

**A8F9**. AUDIO: DESSINATEUR EN GENERIQUE

**A8G0**. AUDIO: DESSINATEUR BANC-TITRE

**A8G1**. AUDIO: GOUACHEUR

**A8G2**. AUDIO: DESSINATEUR HUMORISTIQUE

**A8G3**. AUDIO: DESSINATEUR D'ANIMATION

**A8G4**. AUDIO: DESSINATEUR ARTISTIQUE

**A8G5**. AUDIO: DESSINATEUR DESSIN ANIME

**A8G6**. AUDIO: TRACEUR

**A801**. OUVRIER: MACHINISTE, ELECTRICIEN

**A802**. OUVRIER: PEINTRE

**A803**. OUVRIER: MACON

**A804**. OUVRIER: MENUISIER

**A805**. OUVRIER: STAFFEUR

**A806**. OUVRIER: MENUISIER-TRACEUR

**A807**. OUVRIER: PEINTRE EN LETTRES FAUX BOIS

**A808**. OUVRIER: SERRURIER MECANICIEN

**A809**. OUVRIER: CONDUCTEUR DE GROUPE

**A810**. OUVRIER: TOUPILLEUR

**A811**. OUVRIER: MAQUETTISTE

**A812**. OUVRIER: SCULPTEUR DECORATEUR

**A813**. SSCHEF EQUIPE: MACHINISTE ELECTRICIEN

**A814**. SSCHEF EQUIPE: PEINTRE

**A815**. SSCHEF EQUIPE: MENUISIER STAFFEUR

**A816**. CHEF EQUIPE: MACHINISTE ELECTRICIEN

**A817**. CHEF EQUIPE: PEINTRE

**A818**. CHEF EQUIPE: MENUISIER, STAFFEUR

**A819**. CHEF SCULPTEUR DECORATEUR

**A820**. CHEF CONSTRUCTEUR

**A821**. TOURNAGE:OUVRIER: MACHINISTE ELECTRICIEN

**A822**. TOURNAGE:OUVRIER: CONDUCTEUR DE GROUPE

**A823**. TOURNAGE:SSCHEF EQUIPE: MACHINIST.ELECT.

**A824**. TOURNAGE:CHEF EQUIPE: MACHINISTE ELECTR.

**A830**. CINE: REALISATEUR

**A831**. CINE: DIRECTEUR DE PRODUCTION

**A832**. CINE: DIRECTEUR DE LA PHOTOGRAPHIE

**A833**. CINE: DECORATEUR-CHEF

**A834**. CINE: CHEF OPERATEUR DE SON

**A835**. CINE: ARTISTE DECORATEUR

**A836**. CINE: 1ER ASSISTANT REALISATEUR

**A837**. CINE: 2EME ASSISTANT REALISATEUR

**A838**. CINE: REGISSEUR GENERAL

**A839**. CINE: REGISSEUR ADJOINT

**A840**. CINE: CAMERAMAN

**A841**. CINE: DECORATEUR ADJOINT OU 1ER ASSISTAN

**A842**. CINE: 2EME ASSISTANT DECORATEUR

**A843**. CINE: PEINTRE D'ART, DECORATEUR EXECUTAN

**A844**. CINE: REGISSEUR D'EXTERIEUR

**A845**. CINE: ACCESSOIRISTE

**A846**. CINE: TAPISSIER

**A847**. CINE: TAPISSIERE

**A848**. CINE: ENSEMBLIER

**A849**. CINE: CHEF MAQUILLEUR POSTICHEUR

**A850**. CINE: MAQUILLEUR, COIFFEUR, PERRUQUIER

**A851**. CINE: COIFFEUR PERRUQUIER

**A852**. CINE: CHEF MONTEUR

**A853**. CINE: MONTEUR ADJOINT

**A854**. CINE: ADMINISTRATEUR DE PRODUCTION

**A855**. CINE: ADMINISTRATEUR ADJOINT COMPTABLE

**A856**. CINE: SECRETAIRE DE PRODUCTION

**A857**. CINE: CREATEUR DE COSTUMES

**A858**. CINE: CHEF COSTUMIER

**A859**. CINE: COSTUMIER

**A860**. CINE: HABILLEUSE

**A861**. CINE: 1ER ASSISTANT OPERATEUR

**A862**. CINE: 2EME ASSISTANT OPERATEUR

**A863**. CINE: PHOTOGRAPHE

**A864**. CINE: ASSISTANT DE SON INDEPENDANT

**A865**. CINE: SCRIPT GIRL

**A866**. CINE: RECORDER OU PERCHMAN

**A867**. ANN.8 STAGIAIRE

**A9EXPA**. ACTIVITE SALARIEE EN ANNEXE 9

**A9FACF**. ACTIVITE SALARIEE EN ANNEXE 9

**A9FRON**. ACTIVITE SALARIEE FRONTALIERE

**CCRE**. BENEFICIARE AIDE A CREATION ENTREPRISE

**CEE**. ACTIVITE SALARIEE EN CEE

**CHOM** .CHOMAGE CONSTATE AUTRE ASSÉDIC

**CIF**. CONGE INDIVIDUEL FORMATION

**CJETR**. PERIODE A L'ETRANGER SUITE A DEMISSION

**COLLAF**. EMPLOYE D'UNE COLLECTIV. LOCALE AFFILIEE

**COLLEC**. EMPLOYE D'UNE COLLECTIVITE LOCALE

**COMM**. ACTIVITE COMMERCANT OU ARTISAN

**CPAR**. CONGE PARENTAL

**DISPO**. FONCTIONNAIRE EN DISPONIBILITE

**D23**. ACTIVITE SALARIEE RELEVANT DE LA DEL 23.

**D35**. ACTIVITE SALARIEE RELEVANT DE LA DEL 35

**ELEC**. MANDAT ELECTIF POLITIQUE OU SYNDICAL

**ELIH5A**. ELI CATS DECRET, HANDICAPE DEPUIS 5 ANS

**ELI15C**. ELI CATS DECRET, 15 ANS A LA CHAINE

**ELI15E**. ELI CATS DECRET, 15 ANS EN EQUIPES

**ELI15S**. ELI CATS DECRET, 15 ANS CHAINES EQUIPES

**ELI200**. ELI CATS DECRET, 200 NUITS PENDANT 15 AN

**ETR**. ACTIVITE SALARIEE A L'ETRANGER

**ETUD**. ETUDES COMPLEMENTAIRES

**E301**. INDEMNISATION CEE

**E303**. INDEMNISATION CEE EXPORTATION DES DROITS

**FP**. STAGE HORS LIVRE IX

**FPART7**. STAGES CONDUISANT À UN NIV 3 ou 4

**FPL9**. STAGE LIVRE IX

**GDM**. ACTIVITE SALARIEE GENS DE MAISON (A11)

**INACT**. INACTIVITE

**INC**. INCARCERATION

**INDAA**. INDEMNISATION AUTRE ASSÉDIC

**INDAO**. INDEMNISATION AUTRE ORGANISME

**INDSP**. CHOMAGE INDEMNISE PAR LE SECTEUR PUBLIC

**INEAUT**. INELI CATS DECRET, AUTRE MOTIF

**INE1AE**. INELI CATS DECRET, MOINS D'1 AN ENTREPRI

**INE10S**. INELI CATS DECRET, MOINS DE 10 ANS SS

**INE15C**. INELI CATS DECRET, MOINS D'15 CHAINE

**INE15E**. INELI CATS DECRET, MOINS D'15 EQUIPE

**INV1**. INVALIDITE DE 1ère CATEGORIE

**INV2**. INVALIDITE DE 2ème CATEGORIE

**INV2NI**. INVALIDITE DE 2ème CATEGORIE N.INDEMNISE

**INV3**. INVALIDITE DE 3ème CATEGORIE

**INV3NI**. INVALIDITE DE 3ème CATEGORIE N.INDEMNISE

**L35112**. ACTIVITE SECTEUR PUBLIC

**MA**. MALADIE

**MAND**. ACTIVITE DE MANDATAIRE SOCIAL

**MANI**. MALADIE NON INDEMNISEE

**MAT**. MATERNITE

**MATNI**. MATERNITE NON INDEMNISEE

**PMC**. PER. D'APPLIC. MESURE CONSERVAT. PREAVIS

**PRESS**. OUVRIER DE LA PRESSE

**RG**. ACTIVITE REGIME GENERAL

**SAB**. CONGE SABBATIQUE

**SIVP**. STAGE D'INITIATION À LA VIE PROFESSIONNELLE

**SN**. SERVICE NATIONAL

**SNCF**. EMPLOYE SNCF

**TUC**. TRAVAUX D'UTILITE COLLECTIVE
