---
title: "Présentation de la table"
---

Le segment « Individu » (IND, LN4A) : table centrale qui fait la jonction avec les autres tables, au niveau de l'individu.

| \*\* <br>Nom Oracle (SAS) \*\* | \*\* <br>Nom Segment \*\* | \*\* <br>Libellé \*\* |                                                                         \*\* <br>Description \*\*                                                                         |                                                                                                                                                                                                      \*\* <br>Modalités \*\*                                                                                                                                                                                                       |
|:------------------------------:|:-------------------------:|:---------------------:|:-------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|           <br>KCALA            |        <br>INDALE         |        <br>ALE        | <br>Il s'agit de l'identifiant de l'ALE. Il est composé du :<br> - numéro de département de l'ALE (2 caractères)<br> - numéro de l'ALE dans le département (3 caractères) |                                                                                                                                                                                                                <br>                                                                                                                                                                                                                |
|           <br>KCNFA            |        <br>INDFORA        | <br>Niveau de diplôme |                                                                 <br>Niveau de formation générale atteint                                                                  | <br>AFS. Aucune formation scolaire<br> <br>CFG. CFG ou CEP<br> <br>CP4. Primaire à 4ème achevée<br> <br>C12. 2ème / 1ère achevée<br> <br>C3A. BEPC / 3ème achevée<br> <br>NV1. Certification de niveau 1 (BAC + 5 et plus)<br> <br>NV2. Certification de niveau 2 (BAC + 3 et + 4)<br> <br>NV3. Certification de niveau 3 (BAC + 2)<br> <br>NV4. Certification de niveau 4 (BAC)<br> <br>NV5. Certification de niveau 5 (CAP, BEP) |
|           <br>KCNFB            |        <br>INDFORB        | <br>Niveau de diplôme |                                                                <br>Niveau de formation spécifique atteint                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                    |
