---
title: "Dictionnaire des variables"
---

+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>Variables          | <br>Libellé                                                            | <br>Modalités                               | <br>Commentaires                                                                                                                                                     |
+========================+========================================================================+=============================================+======================================================================================================================================================================+
| <br>ID_DOSSIER         | <br> Idenfitiant IMILO                                                 |                                             |                                                                                                                                                                      |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>ScdDateBegId       | <br>Date de début de validité des informations contenues dans la ligne |                                             | <br>La date est une chaîne de caractère au format "dd/mm/YYYY"                                                                                                       |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>ScdDateEndId       | <br>Date de fin de validité des informations contenues dans la ligne   |                                             | <br>La date est une chaîne de caractère au format "dd/mm/YYYY"                                                                                                       |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>SCD_ACTIVE         | <br>Indicatrice de validité à date de la ligne                         | <br>'N' : la ligne n'est plus valide à date | <br>L'extraction étant faite au mois de février 2025, si une ligne a SCD_ACTIVE='O', cela signifie qu'en février 2025, il s'agissait de l'information la plus à jour |
|                        |                                                                        |                                             |                                                                                                                                                                      |
|                        |                                                                        | <br>'O' : la ligne est valide à date        |                                                                                                                                                                      |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>CD_SEXE            | <br> Code du sexe de la personne                                       | <br>"F" : femme                             |                                                                                                                                                                      |
|                        |                                                                        |                                             |                                                                                                                                                                      |
|                        |                                                                        | <br>"H" : homme                             |                                                                                                                                                                      |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>CD_ADR_REGION      | <br> Code INSEE de la région de résidence                              |                                             |                                                                                                                                                                      |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>CD_ADR_DEPARTEMENT | <br> Code INSEE du département de résidence                            |                                             |                                                                                                                                                                      |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>CD_ADR_COMMUNE     | <br> Code INSSE de la commune de résidence                             |                                             |                                                                                                                                                                      |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>DtNaissanceId      | <br> Date de naissance de la personne                                  |                                             | <br>La date est une chaîne de caractère au format "dd/mm/YYYY"                                                                                                       |
+------------------------+------------------------------------------------------------------------+---------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+