---
title: "Dictionnaire des variables"
editor: 
  markdown: 
    wrap: 72
---

| <br>Variables | <br>Libellé                                                                                       | <br>Modalités                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r>Commentaires                                                                                                                                                                     |
|---------------|---------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <br>AGE       | <br>Age du demandeur au 31/12 <br>de l'année d'inscription de <br>la demande associée             | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>En année                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| <br>ALE       | <br>Numéro de l'Agence Locale <br>pour l'Emploi d'inscription <br>du demandeur                    | <br>Numéro de l'ALE (unité locale <br>de Pôle emploi). Les deux premiers <br>caractères donnent le département.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>ANCIEN    | <br>Ancienneté dans la demande                                                                    | <br>En mois révolu au dernier jour <br>du mois de fermeture de la <br>demande. Si la demande est en <br>cours il s'agit de l'ancienneté <br>au dernier jour du fichier.                                                                                                                                                                                                                                                                                                                                                                                                                                                      | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>API       | <br>Allocation Parent Isolé                                                                       | <br>0. Non bénéficiaires de l'API<br> <br>1. Bénéficiaire de l'API (saisie manuelle)<br> <br>2. Bénéficiaire de l'API (information CNASEA)<br> <br>3. Demande API en cours d'instruction                                                                                                                                                                                                                                                                                                                                                                                                                                     | <br>Remplacé en 2009 par<br>le RSA                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| <br>AXETRAV   | <br>Axe de travail                                                                                | <br>P. Projet<br> <br>R. Recherche<br> <br>A. À a pprofondir<br> <br>E. Recherche d'emploi<br> <br>F. Freins périphériques à l'emploi<br> <br>M. Mobilité p rofessionnelle                                                                                                                                                                                                                                                                                                                                                                                                                                                   | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>CATREGR   | <br>Catégorie opérationnelle du <br>demandeur relative à la <br>dernière situation connue         | <br>1. Personnes immédiatement disponibles <br>et à la recherche d'un emploi sous CDI à temps <br>plein<br> <br>2. Personnes immédiatement disponibles <br>et à la recherche d'un emploi sous CDI à temps<br> partiel<br> <br>3. Personnes immédiatement disponibles <br>et à la recherche d'un emploi à durée limitée <br>(CDD, mission d'intérim, va cation...)<br> <br>4. Personnes à la recherche d'un emploi mais <br>non immédiatement disponibles (en formation, <br>en arrêt maladie, en congé maternité, en CRP...)<br> <br>5. Personnes pourvues d'un emploi, à la <br>recherche d'un autre emploi donc non <br    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >immédiatement disponibles. Figurent ici <br>les personnes en contrat emploi solidarité <br>(CES, CIE ou autres contrat <br>aidés...).                                                                                                                               | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>CEMPLOI   | <br>Composante emploi du demandeur <br>d'emploi                                                   | <br>CE1. DE positionné sur un métier en <br>tensi on/porteur<br> <br>CE2. DE non positionné sur un métier en <br>t ension/porteur                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>CONTRAT   | <br>Type de contrat recherché <br>par le demandeur (dernière <br>valeur connue sur la demande)    | <br>1. Contrat à durée in déterminée<br> <br>2. Contrat à durée déterminée ou temporaire<br> <br>3. Contrat saisonnier                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>CUCS      | <br>Demandeurs résidant en zone <br>CUCS (Contrat Urbain de Cohésion <br>Sociale)                 | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>A pris fin en 2014                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| <br>DATANN    | <br>Date d'annulation de la demande                                                               | <br>La demande est en cours à la date \< br\>statistique du fichier.<br> <br>Date exclusive : si DAT ANN=01/02/2010 , le <br>dernier jour d'inscription sur cette demande <br>est le 31/01/2010.                                                                                                                                                                                                                                                                                                                                                                                                                             | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>DATINS    | <br>Date d'effet d'inscription <br>de la demande                                                  | <br                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >L'inscription commence ce jour                                                                                                                                                                                                                                      | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>DATNAIS   | <br>Date de naissance (année <br>et mois)                                                         | <br>Mois de naissance (le jour exact n'est pas<br> renseigné, il est fixé conve ntionnellement <br>à 15)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>DATSINS   | <br>Date de saisie d'inscription <br>de la demande                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>DEPCOM    | <br>Commune de résidence <br>du demandeur                                                         | <br>En principe, c'est le Code Officiel <br                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >Géographique. Toutefois, il peut y avoir des <br>valeurs non-conformes. Les deux <br>premiers caractères donnent de département.                                                                                                                                    | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>DIPLOME   | <br>Diplôme obtenu par le <br>demandeur lors de son \< br\>inscription                            | <br>D. Diplômé<br> <br>N. Non Diplômé                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>EXPER     | <br>Expérience dans le ROME <br>demandé.                                                          | <br>Nombre expérience. Arrondi à l'ap préciation<br> du conseiller                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | <br>Il existe des cas où <br>le nombre d'année <b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r>d'expérience est supérieur <br>à l'âge du demandeur <br>d'emploi.                                                                                                                |
| <br>EXPEUNIT  | <br>Unité durée expérience dans <br>le ROME                                                       | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>MOBDIST   | <br>Mobilité du DE                                                                                | <br>Mobilité du DE vis-à-vis de l'emploi, en<br> minutes, heures, kilomètres ou FE selon la <br>valeur de la variable MOBUNIT. Il faut <br>l'utiliser avec la variable MOBUNIT pour <br>lui donner un sens.                                                                                                                                                                                                                                                                                                                                                                                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>MOBUNIT   | <br>Unité de la mobilité <br>du demandeur vis-à-vis de <br>l'emploi                               | <br>00. Non renseignée<br> <br>FE. France Entière<br> <br>H. Heure<br> <br>KM. Kilomètres<br> <br>MN. Minutes<br> <br>MT. Mobilité totale                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>MOTANN    | <br>Motif d'annulation de <br>la demande                                                          | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/MOTANN.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>MOTANN_a  | <br>Motif d'annulation de la <br>demande détaillé                                                 | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/MOTANN_a.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>MOTINS    | <br>Motif d'inscription de la <br>demande agrégé                                                  | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/MOTINS.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>MOTINS_A  | <br>Motif d'inscription de la <br>demande détaillé                                                | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/MOTINS_a.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NATION    | \< br\>Nationalité du demandeur <br>d'emploi                                                      | <br> Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/NATION.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NBAR78    | <br>Nombre de mois d'activité <br>réduite ≤ 78H                                                   | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NBAR79    | <br>Nombre de mois d'activité <br>réduite \> 78H                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NDEM      | <br>Numéro de la demande                                                                          | <br>Numéroté de la plus récente à la plus <br>ancienne (la demande n°1 est la demande <br>la plus récente à la date statistique du <br>FHS)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NIVFOR    | <br>Niveau de formation atteint <br>par le demandeur                                              | <br>000. Inconnu<br> <br>AFS. Aucune formation scolaire<br> <br>C12. Classes 2e et 1e (études générales)<br> <br>C3a. Bepc- classe 3e achevée<br> <br>CFG. Classes 6e 5e 4e<br> <br>Cp4. Certificat études primaires. CPP-CPA<br> <br>Nv1. Bac +5 et +<br> <br>Nv2. Bac +3 et +4<br> <br>Nv3. Bac +2<br> <br>Nv4. Bac <br> <br>Nv5. Cap / BEP                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NUMCDV    | <br>Référence contrat de ville                                                                    | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NUMCUCS   | <br>Numéro de la CUCS                                                                             | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NUMQPV    | <br>Référence QPV                                                                                 | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>NUMZUS    | <br>Numéro de la ZUS                                                                              | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>OBLIGEM1  | <br>Obligation d'emploi du <br>demandeur d'emploi 1                                               | <br> Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/OBLIGEM.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>OBLIGEM2  | <br>Obligation d'emploi du <br>demandeur d'emploi 2                                               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>OBLIGEM3  | <br>Obligation d'emploi du <br>demandeur d'emploi 3 (AAH)                                         | <br>0. Sans obligation d'emploi<br> <br>H. Allocation adulte handicape<br> <br>R. Allocation adulte handicape                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>OBLIGEMC  | <br>Obligation d'emploi du <br>demandeur d'emploi calculée                                        | <br>Idem OBLIGEM1 et OBLIGEM2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>PROJENTR  | <br>Projet entreprise                                                                             | <br>E. Projet envisagé<br> <br>V. Projet validé                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>QPV       | <br>Indicateur résidence QPV                                                                      | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>QUALIF    | <br                                                                                               
                                                                    >Qualification du demandeur                     | <br>0. Non précisé<br> <br>1. Manœuvres<br> <br>2. Ouvriers s pécialisés<br> <br>3. Ouvriers qualifiés (OP1-OP2)<br> <br>4. Ouvriers qualifiés (OP3-OHQ)<br> <br>5. Employés non qualifiés<br> <br>6. Employés qualifiés<br> <br>7. Techniciens-de ssinateurs<br> <br>8. Agents de maîtrise<br> <br>9. Cadres                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>REGION    | <br>Région                                                                                        | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/REGION.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>RMA       | \< br\>Éligibilité au revenu <br>minimum d'activité                                               | <br>1. Valeur de redressement (non r éférencée)<br> <br>2. Non bé néficiaire<br> <br>3. Valeur de redressement (vide)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>RMI       | <br>Code RMI du mois précédent <br>le mois stat ou code RSA du <br>mois stat                      | <br>1. RMI<br> <br>2. Non bé néficiaire<br> <br>3. Valeur de redressement (vide)<br> <br>4. RSA nouveau droit<br> <br>5. RSA ancien RMI/API                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>ROME      | <br>Code Rome du métier recherché                                                                 | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>ROMEAPL   | <br>Code appellation du ROME                                                                      | <br                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >L'appellation du ROME est sur 3 <br>positions et est associée à un code <br>ROME pour avoir le libellé correspondant <br>au métier. L'appellation du ROME seul <br>n'a aucune signification.                                                                        | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>ROMEASS   | <br>ROME Assedic recherché                                                                        | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>Variable inutilisable                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| <br>ROMEVAL   | <br>Code validation du ROME                                                                       | <br>1. Reserve ou alerte sur conduite à tenir<br> <br>2. Maitrise des CTB emp loi/métier<br> <br>3. Maitrise CTB e mploi/métier + évaluation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>RSQSTAT   | <br>Risque statistique du demandeur <br>d'emploi                                                  | <br>RS1. Risque faible de chômage de longue durée<br> <br>RS2. Risque modéré de chômage de longue durée<br> <br>RS3. Risque fort de chômage de longue durée                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>SALMT     | <br>Montant du salaire brut <br>demandé par le DE                                                 | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>Risques de valeurs <br>extrêmes liées <br>vra isemblablement <br>à une erreur d'unité                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| <br>SALUNIT   | <br>Salaire horaire, mensuel ou <br>annuel du DE                                                  | <br>0. Non renseigné<br> <br>A. Annuel <br> <br>C. Cachet<br> <br>H. Horaire<br> <br>M. Mensuel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| <br>SEXE      | <br>Sexe du demandeur d'emploi                                                                    | <br>1. Homme<br> <br>2. Femme                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>SITMAT    | <br>Situation de famille du <br>demandeur d'emploi                                                | <br>C. C élibataire<br> <br>D. Divorcé ou séparé<br> <br>M. Marié ou vie maritale<br> <br>V. Veuf                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>SITPAR    | <br>Situation particulière au <br>regard de l'emploi agrégée                                      | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/SITPAR.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>SITPAR_A  | <br>Situation particulière <br>au regard de l'emploi détaillée                                    | <br>Les modalités sont disponibles dans la <br>[section dédiée](FHS_DE_variables/SITPAR_a.qmd).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>STRSUIVP  | <br>Code de la structure principale <br>de suivi                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>La Structure Principale <br>est une Agence ou une <br>Équipe p rofessionnelle <b                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r>(sectorielle ou <br> géographique). La notion <br>de bassin est prise en <br>compte. Le référent <br>principal, pour le suivi <br>mensuel, est un agent de <br>cette structure.  |
| <br>TEMPS     | <br>Temps de travail de l'emploi <br>recherché                                                    | <br>1. Temps complet<br> <br>2. Temps partiel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>ZRR       | <br>Indicateur de résidence en <br>Zone de revitalisation rurale (ZRR)                            | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| <br>ZUS       | <br>Demandeurs en zone urbaine <br>sensible                                                       | <br>AT. DEMENAGEMENT DU DE<br> <br>IN. IDENTIFICATION ZUS NON REALISEE<br> <br>NT. ETAT INITIAL, DE NON TRAITE<br> <br>NZ. DE NE RESIDANT PAS EN ZUS<br> <br>ZU. DE RESIDANT EN ZUS                                                                                                                                                                                                                                                                                                                                                                                                                                          | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
