---
title: "Dictionnaire des variables"
---

| <br>Variables       | <br>Libellé                                         | <br>Description                                                                                                                                  | <br>Modalités                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
|---------------------|-----------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <br>PAFIDAFF KCPAF  | <br>IDENTIFIANT PERIODE AFFILIATION                 | <br>C'est l'identifiant de la période d'affiliation.<br> Clef de jonction avec KCPAF1 (CDTIDAFF) du segment CONTRAT TRAVAIL (CDT) - segment LN4E |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>PAFDAFFI KCAFF  | <br>CODES UNITE AFFILIATION RETENUES                | <br>Cette rubrique définit l'unité d'appréciation de l'affiliation.<br> Propriété présente dans les segments suivants : DAL/PAF                  | <br>A. Année<br> M. Mois<br> J. Jours<br> H. Heures<br> E. Jours d'Embarquement<br> V. Vacations (2 vacations = 1 Jour = 5.6h.)<br> C. Cachet (et cachets groupés pour SIGMA) 1 cachet isolé =12 heures<br> G. Cachet groupé (1 cachet groupé = 8 heures)<br> 8. Nombre d'heures d'affiliation calculée pour l'Annexe 5 et 12 à partir des salaires<br> 9. Nombre d'heures d'affiliation calculée pour l'Annexe 5 à partir des heures travaillées saisies au niveau des rémunérations<br> Z. Non concerné<br> X. Valeur hors table                                       |
| <br>PAFUAFFI KPAFFQ | <br>NOMBRES D'UNITES D'AFFILIATION                  | <br>Nombre unités de la période d'affiliation ouvrant le droit.                                                                                  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>PAFDTDEB KDDPE  | <br>DATE DEBUT PERIODE D'AFFILIATION                | <br>Date du premier jour de la période d'affiliation.                                                                                            | <br>Ces variables ont un champ plus large que celles situées dans la table CDT, puisqu'elles incluent l'ensemble des périodes d'affiliation, dont les contrats de travail, les formations et les arrêts de travail.                                                                                                                                                                                                                                                                                                                                                      |
| <br>PAFDTFIN KDFPE  | <br>DATE FIN PERIODE D'AFFILIATION                  | <br>Date du dernier jour de la période d'affiliation.                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>PAFALIQ KCFPL   | <br>FAMILLE PERIODE LIQUIDATION PASSE PROFESSIONNEL | <br>Il s'agit du code famille d'une période du passé professionnel.                                                                              | <br>01. Activité salariée relevant du champ d'application RAC<br> 02. Activité salariée hors champ d'application RAC mais avec système d'indemnisation similaire (secteur public)<br> 03. Activité non salariée exclue de tout RAC (artisan, agriculteur, commerçant,...)<br> 04. Période d'incapacité physique (maladie, maternité,...)<br> 05. Période de formation<br> 06. Période d'indemnisation hors Pôle emploi de traitement (suite à transfert)<br> 07. Activité salariée hors champ d'application RAC (secteur public auto-assurance)<br> 00. Autres activités |
