---
title: "Reproduction d'indicateurs cibles"
execute: 
  enabled: false
---

## Nombre d'indemnisés en fin de mois

Une personne indemnisée peut être repérée dans la table Période à Justification Constante (PJC) à l'aide des variables Date de début de PJC (**KDDPJ**), Date de fin de PJC (**KDFPJ**), et type de PJC (**KCPJC**). Une PJC est une période pendant laquelle le montant d'allocation versé est constant. La PJC peut être payée (codes KCPJC 1 et 4), non payée mais consommée (code KCPJC 2, en cas de sanctions par exemple), non payée et non consommée (code KCPJC 3, en cas de différé par exemple). L'ensemble des personnes indemnisées en fin de mois correspond donc à l'ensemble des allocataires qui ont une PJC payée en cours en fin de mois.

D'après la publication [Demandeurs d'emploi indemnisables : situation au 31 mars 2022](https://statistiques.pole-emploi.org/indem/indempub/215999) de Pôle Emploi, 3 070 000 allocataires sont inscrits à Pôle Emploi en décembre 2021.

Le programme permettant de reconstituer cet indicateur est le suivant :

```{r}
#Chargement du package dplyr
library(dplyr)


#Définition de la date de fin du mois dont on veut les inscrits en fin de mois
mois <- as.Date("2021-12-31")

#Utilisation de la table PJC pour repérer les indemnisés en fin de mois
indemnises <- PJC %>%
  filter(KDDPJ <= mois & KDFPJ >= mois & KCPJC %in% c(1,4)) %>%
  distinct(id_midas)
```
