---
title: "Dictionnaire des variables"
---

+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>Variables              | <br>Libellé                                                            | <br>Modalités                                     | <br>Commentaires                                                                                                                                                     |
+============================+========================================================================+===================================================+======================================================================================================================================================================+
| <br>ID_DOSSIER             | <br> Idenfitiant IMILO                                                 |                                                   |                                                                                                                                                                      |
+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>ID_DISPOSITIF_INSTANCE | <br> Identifiant d'un dispositif                                       |                                                   | <br>Si un jeune fait deux dispositifs différents, il y aura deux ID_DISPOSITIF_INSTANCE associés à un même ID_DOSSIER                                                |
+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>ScdDateBegId           | <br>Date de début de validité des informations contenues dans la ligne |                                                   | <br>La date est une chaîne de caractère au format "dd/mm/YYYY"                                                                                                       |
+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>ScdDateEndId           | <br>Date de fin de validité des informations contenues dans la ligne   |                                                   | <br>La date est une chaîne de caractère au format "dd/mm/YYYY"                                                                                                       |
+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>SCD_ACTIVE             | <br>Indicatrice de validité à date de la ligne                         | <br>'N' : la ligne n'est plus valide à date       | <br>L'extraction étant faite au mois de février 2025, si une ligne a SCD_ACTIVE='O', cela signifie qu'en février 2025, il s'agissait de l'information la plus à jour |
|                            |                                                                        |                                                   |                                                                                                                                                                      |
|                            |                                                                        | <br>'O' : la ligne est valide à date              |                                                                                                                                                                      |
+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>LB_DISPOSITIF          | <br> Libellé du dispositif que le jeune suit                           | <br>"Contrat d'Engagement Jeune", "PACEA" ou "GJ" |                                                                                                                                                                      |
+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>DtEntreeDispositifId   | <br> Date d'entrée dans le dispositif                                  |                                                   | <br> La date est une chaîne de caractère au format "dd/mm/YYYY"                                                                                                      |
+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>DtFin                  | <br> Date de sortie du dispositif                                      |                                                   | <br>La date est une chaîne de caractère au format "dd/mm/YYYY"                                                                                                       |
|                            |                                                                        |                                                   |                                                                                                                                                                      |
|                            |                                                                        |                                                   | <br> Si le dispositif est toujours en cours, on peut avoir NA s'il n'y a pas encore de date de fin prévue                                                            |
+----------------------------+------------------------------------------------------------------------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
