---
title: "Dictionnaire des variables"
---

| <br>Nom Oracle (SAS) | <br>Nom Segment |                                 <br>Libellé                                 |                                                                                                                                                                 <br>Description                                                                                                                                                                 |                                                                                                                                                                                                                                                                                                                                  <br>Modalités                                                                                                                                                                                                                                                                                                                                   |
|:---------:|:---------:|:---------:|:-------------:|:------------------------------:|
|      <br>KCFPP       |   <br>PJCCFER   |                           <br>CODE FERMETURE PJC                            |               <br>Code fermeture de la PJC pour motif fin de prise en charge. En cas de simultanéité d'apparition, la plus petite valeur sera privilégiée (cas de la fin d'ASC). Ce code est renseigné pour les trois types de PJC (KCPJC = '1', '2' ou '3'). Toute modification de cette valeur induit une rupture sur les PJC.                | <br>10. Fin de droit réglementaire :<br> <br>- Limite d'âge à 65 ans<br> <br>- Durée maximale atteinte<br> <br>- Nouveau droit sur même prise en charge (sauf ACA)<br> <br>- Date limite d'indemnisation<br> <br>12. Fin période AER <br> 15. Exclusion définitive DDTE ou Assédic (122 jours)<br> 16. Exclusion définitive DDTE (autre)<br> 20. radiation (reprise d'emploi, décès,...)<br> 30. Suspension Assédic (non réponse à enquête au 122e jour)<br> 40. Mise en attente de renseignements (ex: ressources RSN, déclaration DSM sauf attente de justificatif)<br> 99. Sans code fermeture (en cours d'indemnisation, exclusion temporaire,...)<br> XX. Valeur hors table |
|      <br>KCOPP       |   <br>PJCCOUV   |                           <br>CODE OUVERTURE PJC                            |                                                              <br>Motif d'ouverture de la PJC suite à une décision de liquidation. Ce code est renseigné pour les trois types de PJC (KCPJC = '1', '2' ou '3'). Toute modification de cette valeur induit une rupture sur les PJC.                                                               |                                <br>01. Admission en indemnisation<br> 02. Réadmission en indemnisation<br> 03. Admission au titre d'une aide<br> 10. Transfert de l'indemnisation<br> 20. Reprise de l'indemnisation après interruption du droit (sauf sur stage AFR ou RSP ou suite à stage AFR ou RSP)<br> 30. Point de départ dans l'application (migration)<br> 40. Révision du SJR/SJC suite à perte d'emploi conservé<br> 50. Ouverture poursuite indemnisation sur antécédent exécutable<br> 99. Sans objet (y compris pour une entrée AFR, ERF et RSP, et sur la reprise RAC/RSN qui suit le stage AFR ou RSP)<br> XX. Valeur hors table                                 |
|      <br>KCPJC       |   <br>PJCTYPE   |                            <br>CODE TYPE DE PJC                             |                                                                                                                              <br>Cette donnée permet de connaitre le type d'une Période à Justification Constante                                                                                                                               |                                                                                  <br>1. Période payée<br> 2. Période non payée consommée :<br> - exclusions temporaires DDTE<br> - PND périodes imputables<br> - dépassement ressources plafond<br> 3. Période non payée non consommée :<br> - Carence<br> - Différé<br> - Décalage<br> - Maladie<br> - Absence<br> - Périodes saisonnières<br> - PND périodes non imputables<br> - Suspensions non imputables<br> 4. PJC payées au titre des AIDES (associé aux périodes de versement de l'ADR06, ASCRE06 ou ARCE06)<br> X. VALEUR HORS TABLE                                                                                   |
|      <br>KCPJCC      |   <br>PJCTCAR   |                          <br>CODE TYPE PJC CARENCE                          |                                                                       <br>Cette rubrique définit le type de report. Toute modification de cette valeur induit une rupture sur les PJC. Ce code est renseigné pour les PJC de type '3' et les différés en cours de droit.                                                                        |                                                                                                                         <br>01. Carence Préavis Payé non effectué (non géré)<br> 02. CARENCE CONGES PAYES<br> 03. CARENCE indemnités supra légales de rupture (ISLR)<br> 04. DIFFERE D'INDEMNISATION<br> 10. CARENCE CONGES PAYES ANNEXE 4 (\<01/09/1992)<br> 20. CARENCE CONGES PAYES ANNEXE 8<br> 30. FRANCHISE ANNEXE 10 (non géré par AO)<br> 40. CARENCE DELIBERATION 15<br> 90. AUTRE TYPE DE CARENCE<br> 99. SANS OBJET<br> XX. VALEUR HORS TABLE                                                                                                                         |
|      <br>KDDPJ       |  <br>PJCDTDEB   |                             <br>DATE DEBUT PJC                              |                                                                                             <br>C'est la date du premier jour de la période à justification constante, pendant laquelle les éléments de justification du CALCUL restent inchangés.                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|      <br>KDFPJ       |  <br>PJCDTFIN   |                              <br>DATE FIN PJC                               |                                                                                             <br>C'est la date du dernier jour de la période à justification constante, pendant laquelle les éléments de justification du CALCUL restent inchangés.                                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|      <br>KNOPRP      |    <br>PJCRD    |                          <br>RANG DEGRESSIVITE PJC                          |                                                                              <br>Indique le rang de dégressivité en cours sur la PJC. Ce code est renseigné pour les PJC payées (KCPJC = '1'). Toute modification de cette valeur induit une rupture sur les PJC.                                                                               |                                                                                                                                                                     <br>00. Pas de dégressivité<br> 01. Taux de dégressivité 1<br> 02. Taux de dégressivité 2<br> 03. Taux de dégressivité 3<br> 04. Taux de dégressivité 4<br> 05. Taux de dégressivité 5<br> 06. Taux de dégressivité 6<br> 07. Taux de dégressivité 7<br> 08. Taux de dégressivité 8<br> 09. Taux de dégressivité 9<br> 99. Non déterminé                                                                                                                                                                     |
|      <br>KQBPJP      |   <br>PJCTAUX   |                      <br>MONTANT JOURNALIER ALLOCATION                      |                                                                                <br>Montant brut journalier de l'allocation. Cette rubrique est renseignée pour les PJC payées (KCPJC = '1'). Toute modification de cette valeur induit une rupture sur les PJC.                                                                                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|      <br>KQJSTP      |   <br>PJCMITH   | <br>MONTANT NET JOURNALIER VERSE ITH<br> (MONTANT JOUR. INDEM TRANS. HERB.) |                                                               <br>Montant net journalier versé au titre des ITH (Indemnités de Transport ou d'Hébergement. Ce code est renseigné pour les PJC payées de type '1'. Toute modification de cette valeur induit rupture sur les PJC.                                                                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|      <br>KQRSPP      |   <br>PJCSJRV   |             <br>MONTANT SALAIRE JOURNALIER REVALORISE PLAFONNE              |                                                                             <br>Montant SJR revalorisé plafonné. Cette rubrique est renseignée pour les PJC consommables (KCPJC = '1', ou '2'). Toute modification de cette valeur induit une rupture sur les PJC.                                                                              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|      <br>KROD3       |  <br>ODDIDENT   |                  <br>IDENTIFIANT DE L' OUVERTURE DE DROIT                   |                                                                                                         <br>Référence de l'OD portant le fait générateur.<br> Clef de jonction avec KROD (ODDIDENT) du segment DROIT ODD - segment LN1S                                                                                                         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|      <br>KTDGAP      |   <br>PJCCOEF   |                      <br>COEFFICIENT DEGRESSIVITE PJC                       | <br>Il s'agit du coefficient de dégressivité appliqué lors du calcul d'un montant journalier dans la Nième période d'une durée dégressive en AUD. Le coefficient appliqué est égal au coefficient de la première, multiplié par lui-même autant de fois qu'il y a de périodes. Cette rubrique est renseignée pour les PJC payées (KCPJC = '1'). |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
