---
title: "Dictionnaire des variables"
---

| <br>Nom Oracle (SAS) | <br>Nom segment |                   <br>Libellé                    |                                                                                                <br>Description                                                                                                 | <br>Modalités/commentaires                                       |
|:--------------------:|:---------------:|:------------------------------------------------:|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|------------------------------------------------------------------|
|      <br>KCAFF1      |  <br>DALUAFFI   |    <br>Code des unités d'affiliation retenues    |                                                                           <br>Unités (heures, jours, mois, années) de l'affiliation                                                                            | <br>                                                             |
|       <br>KCDA       |   <br>DALREF    |     <br>Référence de la demande d'allocation     |                                     <br>Cette rubrique identifie une demande d'allocation.<br> Clef de jonction avec KCDA1 (DALREF1) du segment CONTRAT DE TRAVAIL (CDT).                                      |                                                                  |
|      <br>KCPEC1      |  <br>PECIDENT   | <br>Identifiant de la prise en charge sur la DAL | <br>Identifiant de la prise en charge de l'individu. C'est la référence de la prise en charge associée à la demande d'allocation.<br> Clef de jonction avec KCPEC (PECIDENT) du segment PRISE EN CHARGE (PEC). | <br>Le segment PEC (Prise en charge) n'est pas inclus dans MiDAS |
|      <br>KDEPOT      |  <br>DALDTDEP   |           <br>Date de dépôt de la DAL            |                                                                                  <br>Date de dépôt de la demande d'allocation                                                                                  | <br>                                                             |
|      <br>KDFCTF      |   <br>DALDTRE   |       <br>Date retenue du fait générateur        |                                                               <br>Date de fin de contrat de travail qui a été retenue pour apprécier les droits                                                                | <br>                                                             |
|      <br>KPAFFP      |  <br>DALDAFFI   |        <br>Nombre d'unités d'affiliation         |                                                                        <br>Nombre d'unités de la période d'affiliation ouvrant le droit                                                                        | <br>                                                             |
|      <br>KPJSUP      |  <br>DALNBJDI   |          <br>Nombre de jours de différé          |                                                                         <br>Nombre de jours de suspension, de carence ou de formation                                                                          |                                                                  |
|      <br>KROD1       |  <br>ODDIDENT   |     <br>Identifiant ouverture de droit / DAL     |                                             <br>Référence de l'OD portant le fait générateur.<br> Clef de jonction avec KROD2 (ODDDRARET) du segment DROIT OD (OD)                                             |                                                                  |
