---
title: "Présentation de la table"
---

La Dares fournit les données de Mouvements de Main-d'œuvre (MMO)[^1] tirées de l'exploitation des déclarations sociales nominatives (DSN).

Plusieurs tables MMO sont transmises selon la période de référence considérée. [L'unité statistique des tables est celle du contrat]{.underline} : chaque table contient une ligne pour tout contrat actif au moins un jour sur la période de référence. Plusieurs lignes peuvent correspondre à un même individu si celui-ci a eu plusieurs contrats sur la période de référence. Les contrats sont qualifiés selon leur modalité active au dernier jour de la période de référence.

[Exemple]{.underline} : la table « 2017 » contient les contrats actifs au moins un jour sur l'année 2017, c'est-à-dire ayant une date de début antérieure au 1er janvier 2018 et une date de fin postérieure au 31 décembre 2016 ou manquante si le contrat est en cours. La PCS renseignée est la PCS du contrat au 31/12/2017.

Un contrat actif sur plusieurs périodes de référence (par exemple 2017 et 2018) peut être identifié via l'identifiant du contrat (L_CONTRAT_SQN). Sur une période donnée, les contrats dont l'identifiant L_CONTRAT_SQN est vide sont des contrats inactifs sur cette période (mais actifs sur une autre période).

[Exemple]{.underline} : un contrat actif sur les années 2017 et 2018 (date de début ≤ 31.12.2017 et 01.01.2018 ≤ date de fin ≤ 31.12.2018) sera présent dans toutes les tables mais identifiable via son identifiant L_CONTRAT_SQN dans les tables 2017 et 2018 uniquement.
