---
title: "Dictionnaire des variables"
---

| <br>Nom Oracle (SAS) |    <br>Nom Segment    |                         <br>Libellé                        |                                                                                             <br>Description                                                                                              |                <br>Modalités                |
|:----------:|:----------:|:----------:|:-----------------------:|:----------:|
|       <br>KCCT       | <br>CDTIDENT<br> <br> |           <br>Identifiant du contrat de travail            |          <br>C'est l'identifiant de l'objet contrat de travail.<br> <br>Clef de jonction avec KCCT1 (ODDID1) du segment DROIT ODD. Clef de jonction avec KCCT2 (ODDDID2) du segment DROIT ODD.           |                    <br>                     |
|      <br>KCDA1       |      <br>DALREF       |     <br>Référence de la DAL sur le contrat de travail      |                                  <br>Cette rubrique identifie une demande d'allocation.<br> Clef de jonction avec KCDA (DALREF) du segment DEMANDE D'ALLOCATION (DAL).                                   |                                             |
|      <br>KCEP2       |     <br>CDTNAFR2      |                        <br>Code NAF                        | <br>Cette rubrique caractérise la nature de l'activité économique de l'employeur.<br> Cette nouvelle NAF a été mise en place début 2008 et remplace l'ancienne NAF 2003 qui était codée sur 4 positions. | <br>[Codes NAF](https://www.codes-naf.com/) |
| <br>KCPAF \[KCPAF1\] |     <br>CDTIDAFF      | <br>Identifiant période d'affiliation / contrat de travail |                                <br>C'est l'identifiant de la période d'affiliation.<br> <br>Clef de jonction avec KCPAF (PAFIDAFF) du segment PÉRIODE D'AFFILIATION (PAF)                                |                    <br>                     |
|      <br>KDDPE       |     <br>CDTDTDEB      |          <br>Date de début du contrat de travail           |                                               <br>Date du premier jour du contrat de travail.<br> Propriété présente dans les segments suivants : CDT/PAF                                                |                                             |
|      <br>KDFPE       |     <br>CDTDTFIN      |           <br>Date de fin du contrat de travail            |                                               <br>Date du dernier jour du contrat de travail.<br> Propriété présente dans les segments suivants : CDT/PAF                                                |                                             |
|      <br>KDHTRP      |     <br>CDTHEBDS      |        <br>Durée hebdomadaire de travail du salarié        |                                               <br>Durée hebdomadaire habituelle du salarié dans l'entreprise au moment de la rupture du contrat de travail                                               |                    <br>                     |
|      <br>KNCTE       |      <br>CDTNUM       |              <br>Numéro du contrat de travail              |                                                                                                   <br>                                                                                                   |                    <br>                     |
|      <br>KPHENP      |     <br>CDTHEBDE      |   <br>Durée hebdomadaire de travail dans l'établissement   |                                                    <br>Horaire hebdomadaire habituel de l'établissement au moment de la rupture du contrat de travail                                                    |                    <br>                     |
