---
title: "Dictionnaire des variables"
---

| <br>Variable (identifiant rubrique DSN)    | <br>Description                                                                                  | <br>Modalités                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|-----------------|--------------------------|----------------------------------------------------|
| <br>IDSISMMO                               | <br>Identifiant du salarié, non signifiant                                                       | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>CP                                     | <br>Code postal de résidence de l'individu lors de la dernière déclaration reçue pour l'individu | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>annee_naissance                        | <br>Année de naissance                                                                           | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>mois_naissance                         | <br>Mois de naissance                                                                            | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>DebutCTT                               | <br>Date de début du contrat                                                                     | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>DerDSN                                 | <br>Dernière déclaration en DSN                                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>DispPolitiquePublique (S21.G00.40.008) | <br>Dispositif de politique publique au dernier jour de la période de référence                  | <br>21. CUI - Contrat Initiative Emploi<br> <br>41. CUI - Contrat d'Accompagnement dans l'Emploi<br> <br>42. CUI - Contrat d'accès à l'emploi - DOM<br> <br>50. Emploi d'avenir secteur marchand<br> <br>51. Emploi d'avenir secteur non marchand<br> <br>61. Contrat de Professionnalisation<br> <br>64. Contrat d'apprentissage entreprises artisanales ou de moins de 11 salariés (loi du 3 janvier 1979)<br> <br>65. Contrat d'apprentissage entreprises non inscrites au répertoire des métiers d'au moins 11 salariés (loi de 1987)<br> <br>66. Convention industrielle de formation par la recherche en entreprise (CIFRE)<br> <br>70. Contrat à durée déterminée pour les séniors<br> <br>71. Contrat à durée déterminée d'insertion<br> <br>80. Contrat de génération<br> <br>81. Contrat d'apprentissage secteur public (Loi de 1992)<br> <br>92. Stage de la formation professionnelle<br> <br>93. Période de mise en situation en milieu professionnel<br> <br>94. Contrat adulte relais<br> <br>99. Non concerné |
| <br>FinCTT (S21.G00.62.001)                | <br>Date de fin du contrat                                                                       | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>H_etab_sqn                             | <br>Identifiant SISMMO de l'établissement                                                        | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>Heures                                 | <br>Somme des heures travaillées au titre de l'année en cours (à venir)                          | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>Individu_DSN                           | <br>Correspond à l'identifiant pour chaque individu dans DSN                                     | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>L_contrat_sqn                          | <br>Identifiant SISMMO du contrat                                                                | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>Localité                               | <br>Commune de résidence de l'individu lors de la dernière déclaration reçue pour l'individu     | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>PcsEse (S21.G00.40.004)                | <br>PCS ESE au dernier jour de la période de référence                                           | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>PreDSN                                 | <br>Première déclaration en DSN                                                                  | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>Salaire_brut                           | <br>Somme des salaires bruts reçus au titre de l'année en cours (à venir)                        | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>Salaire_nets                           | <br>Somme des salaires nets reçus au titre de l'année en cours (à venir)                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>Siret_AF                               | <br>Siret de l'établissement d'affectation                                                       | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| <br>Siret_UT                               | <br>Siret de l'établissement utilisateur dans le cas des contrats intérimaires                   | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
