---
title: "Dictionnaires des variables"
---

+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable | Libellé                                           | Description/Modalités                                                                                                                                                                                                      |
+==========+===================================================+============================================================================================================================================================================================================================+
| NUMCAF   | NUMERO CAF                                        | Code caisse de la CAF sur 3 caractères (N° de département + N° ordre de la Caisse dans le département (rang))                                                                                                              |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| NORDALLC | NUMERO ORDRE ALLCAF                               |                                                                                                                                                                                                                            |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RSAVERS  | RSA VERSABLE                                      | 0\. Pas de RSA                                                                                                                                                                                                             |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | C. RSA droit commun                                                                                                                                                                                                        |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | E. RSA expérimental                                                                                                                                                                                                        |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | J. RSA jeune                                                                                                                                                                                                               |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | L. RSA droit local                                                                                                                                                                                                         |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | S. RSA droit commun suspendu                                                                                                                                                                                               |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | T. RSA droit local suspendu                                                                                                                                                                                                |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | U. RSA jeune suspendu                                                                                                                                                                                                      |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RSAMAJI  | RSA MAJORATION PARENT ISOLE VERSABLE              | 0\. Non concerné                                                                                                                                                                                                           |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. Droit versable                                                                                                                                                                                                         |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. Droit suspendu                                                                                                                                                                                                         |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MTRSAVER | MONTANT RSA VERSABLE                              | Montant total versable pour le RSA, parties socle et activité, pour le mois de référence. Montant restitué après application des éventuelles sanctions subsidiarité et/ou réductions PCD.                                  |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RSSITFAM | SITUATION FAMILLE RSA VERSABLE                    | 0\. Sans signification ou inconnue                                                                                                                                                                                         |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. Isolé homme                                                                                                                                                                                                            |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. Isolé femme                                                                                                                                                                                                            |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 3\. Couple                                                                                                                                                                                                                 |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RSENAUTC | NB ENFANTS AUTRES PERSONNES À CHARGE RSA VERSABLE | Nombre d'enfants et d'autres personnes à charge au sens du RSA. Significatif si RSA droit commun versable.                                                                                                                 |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RSOCCLOG | OCCUPATION LOGEMENT RSA VERSABLE                  | Les modalités sont disponibles dans la [section dédiée](allstat_minima_variables/rsocclog.html)                                                                                                                                                 |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| RESTRRSA | MT RESSOURCES BRUTES TRIMESTRIELLES RSA FOYER     | Montant de l'ensemble des revenus trimestriels des personnes du foyer présentes et à charge, pour le trimestre civil précédant le mois statistique traité, de la déclaration trimestrielle pour le RSA, sans les centimes. |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TRIMRSA  | TRIMESTRIALITE DROIT RSA                          | Trimestrialité du droit RSA par rapport au premier mois du trimestre de référence. Si l'allocataire a à la fois un droit RSA et un droit PPA, la trimestrialité est identique pour les deux prestations.                   |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PPAVERS  | PPA VERSABLE                                      | 0\. Pas de Prime d'Activité                                                                                                                                                                                                |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. Prime d'Activité non majorée 18-25 ans                                                                                                                                                                                 |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. Prime d'Activité non majorée 25 ans et +                                                                                                                                                                               |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 3\. Prime d'Activité majorée                                                                                                                                                                                               |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 4\. Prime d'Activité non majorée moins de 18 ans                                                                                                                                                                           |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MTPPAVER | MONTANT PPA VERSABLE                              | Montant du droit réel valorisé à la Prime d'Activité, versable sur le mois statistique de référence.                                                                                                                       |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PPASITFA | SITUATION FAMILIALE PPA VERSABLE                  | 0\. Sans signification ou inconnue                                                                                                                                                                                         |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. Isolé homme                                                                                                                                                                                                            |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. Isolé femme                                                                                                                                                                                                            |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 3\. Couple                                                                                                                                                                                                                 |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PANBENAU | NB ENFANTS AUTRES PERSONNES À CHARGE PPA VERSABLE | Nombre d'enfants et autres personnes à charge (hors conjoint) au sens de la Prime d'Activité, au dernier mois du trimestre de référence. Significatif si Prime d'Activité versable ou suspendue                            |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TRIMPPA  | TRIMESTRIALITE DROIT PPA                          | 0\. Pas de Prime d'Activité                                                                                                                                                                                                |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. premier mois du trimestre de droit jan/avr/jul/oct                                                                                                                                                                     |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. premier mois du trimestre de droit fev/mai/aou/nov                                                                                                                                                                     |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 3\. premier mois du trimestre de droit mar/jun/sep/dec                                                                                                                                                                     |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| AAHVERS  | AAH VERSABLE                                      | 0\. Pas d'allocation handicapé adulte                                                                                                                                                                                      |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. AAH pour handicapé ne travaillant pas en milieu protégé                                                                                                                                                                |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. AAH pour handicapé travaillant en ESAT                                                                                                                                                                                 |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 3\. AAH pour handicapé travaillant autre qu'en ESAT                                                                                                                                                                        |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| COMPLAAH | COMPLEMENT AAH VERSABLE                           | 0\. Prestation non versable                                                                                                                                                                                                |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. Prestation versable                                                                                                                                                                                                    |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. Majoration pour vie autonome                                                                                                                                                                                           |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 3\. Complément de ressources                                                                                                                                                                                               |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MTCAAHVE | MONTANT CAAH VERSABLE                             | Montant du Complément de l'Allocation aux Adultes Handicapés versable.                                                                                                                                                     |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CINCAAH  | CATEGORIE INCAPACITE AAH                          | 0\. Pas d'AAH                                                                                                                                                                                                              |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. Incapacité ≥ 80 %                                                                                                                                                                                                      |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. Incapacité entre 50 et 79 %                                                                                                                                                                                            |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 3\. Capacité inférieure à 50 %                                                                                                                                                                                             |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| PENAAHVE | PENSION AAH VERSABLE                              | 0\. Pas de pension AAH versable                                                                                                                                                                                            |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. Invalidité seule                                                                                                                                                                                                       |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. ASI (Allocation supplémentaire invalidité)                                                                                                                                                                             |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 3\. Vieillesse seule                                                                                                                                                                                                       |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 4\. ASPA (Allocation Solidarité Personnes Âgées)                                                                                                                                                                           |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 5\. Réversion seule                                                                                                                                                                                                        |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 6\. Réversion avec FNS avant 12/2012                                                                                                                                                                                       |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 7\. Rente AT                                                                                                                                                                                                               |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 8\. Autre pension ou cumul de pension                                                                                                                                                                                      |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 9\. Majoration conjoint à charge                                                                                                                                                                                           |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| AAHPERE  | PERIODICITE RESSOURCES AAH                        | 0\. Non concerné                                                                                                                                                                                                           |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 1\. Annuelle                                                                                                                                                                                                               |
|          |                                                   |                                                                                                                                                                                                                            |
|          |                                                   | 2\. Trimestrielle                                                                                                                                                                                                          |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| MTAAHVER | MONTANT AAH VERSABLE                              | Montant de droit valorisé pour l'AAH pour le mois de référence. Renseigné si AAH versable                                                                                                                                  |
+----------+---------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
