---
title: "La table Parcours du FHS"
---

| <br>Variables | <br>Libellé                                                    | <br>Modalités<br> <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>Commentaires                                                                                                          |
|---------------|----------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------|
| <br>MOTCHGT   | <br>Motif du changement de parcours                            | <br>01. Fin de parcours<br> <br>02. Situation personnelle du demandeur<br> <br>03. Modification du projet (Emploi, Formation)<br> <br>04. Accompagnement Recherche, Projet, Formation<br> <br>05. Environnement Socio-économique<br> <br>06. Erreur de saisie<br> <br>08. Fin de parcours suite à une réinscription \> 6 mois<br> <br>09. Population hors parcours<br> <br>11. Migration vers APP<br> <br>12. Migration vers ACC<br> <br>S0. Parcours avant octobre 2006                                                                                       | <br>Si non renseigné, c'est qu'il n'y a pas de changement de parcours.                                                    |
| <br>PARCOURS  | <br>Parcours du demandeur d'emploi                             | <br>ACE. Recherche accélérée (2006-2009)<br> <br>ACC. Parcours Accompagnement (2009-2013)<br> <br>ACO. Recherche accompagnée (2006-2009)<br> <br>ACT. Recherche active (2006-2009)<br> <br>APP. Parcours appui (2009-2013)<br> <br>APR. À approfondir (2013)<br> <br>ENT. Créateur d'entreprise (2006-2013)<br> <br>GLO. Accompagnement global (2013 10) en lien avec les conseils généraux<br> <br>GUI. Accompagnement guidé (2013)<br> <br>MVE. Mobilisation vers l'emploi (2006-2013)<br> <br>REN. Accompagnement renforcé (2013)<br> <br>SUI. Suivi (2013) | <br>Seuls les parcours « suivi », « guidé », « renforcé » et « global » existent aujourd'hui ; les autres sont obsolètes. |
| <br>PREMPAR   | <br>Premier parcours sur la demande pour le demandeur d'emploi | <br>0. Sur la demande, il s'agit du nième parcours du demandeur d'emploi (le parcours a alors commencé sur une autre demande)<br> <br>1. Sur la demande, il s'agit du premier parcours du demandeur d'emploi                                                                                                                                                                                                                                                                                                                                                   | <br>                                                                                                                      |
| <br>NOUVPAR   | <br>Nouveau parcours pour un demandeur d'emploi                | <br>0. Le parcours n'est pas nouveau au niveau de la demande (il est forcément nouveau sur une demande antérieure)<br> <br>1. Le parcours est nouveau au niveau de la demande (et donc du demandeur)                                                                                                                                                                                                                                                                                                                                                           | <br>                                                                                                                      |
| <br>NDEM      | <br>Identifiant de la demande d'emploi                         | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | <br>                                                                                                                      |
| <br>JOURDV    | <br>Date d'entrée dans le parcours                             | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | <br>                                                                                                                      |
| <br>JOURFV    | <br>Date de sortie du parcours                                 | <br>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | <br>                                                                                                                      |
| <br>NPAR      | <br>Numéro du parcours du demandeur d'emploi                   | <br>Le parcours 1 est le parcours connu le plus récent                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | <br>                                                                                                                      |
