---
title: "KCALF"
---

| <br>Code allocation FNA | <br>Allocation      | <br>Libellé de l'allocation                                                                                                        | <br>Type d'allocation | <br>Régime d'indemnisation                                         | <br>Statut des allocataires |
|-------------------------|---------------------|------------------------------------------------------------------------------------------------------------------------------------|-----------------------|--------------------------------------------------------------------|-----------------------------|
| <br> 0C                 | <br>ACFNE           | <br>Allocation Conventionnelle du FNE                                                                                              | <br>ASFNE             | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 0E                 | <br>FNE             | <br>FNE ancienne formule                                                                                                           | <br>ASFNE             | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 0S                 | <br>ASE             | <br>Allocation de Secours Exceptionnelle                                                                                           | <br>ASE               | <br>Régime de Solidarité                                           | <br>Chômeur indemnisé       |
| <br> 01                 | <br>AB              | <br>Allocation de Base                                                                                                             | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 02                 | <br>ASP             | <br>Allocation Spéciale Prestation                                                                                                 | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 03                 | <br>IF              | <br>Indemnité de Formation                                                                                                         | <br>IF                | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 04                 | <br>AF              | <br>Allocation Forfaitaire                                                                                                         | <br>AF                | <br>Régime de Solidarité                                           | <br>Chômeur indemnisé       |
| <br> 05                 | <br>FD              | <br>Fin de Droits                                                                                                                  | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 06                 | <br>GRL             | <br>Garantie de Ressources Licenciement                                                                                            | <br>GR                | <br>Régime des garanties de <br>Garanties de Ressources            | <br>Préretraité             |
| <br> 07                 | <br>GRD             | <br>Garantie de Ressources Démission                                                                                               | <br>GR                | <br>Régime des garanties de <br>Garanties de Ressources            | <br>Préretraité             |
| <br> 08                 | <br>GRE             | <br>Garantie de Ressources Économique                                                                                              | <br>GR                | <br>Régime des garanties de <br>Garanties de Ressources            | <br>Préretraité             |
| <br> 10                 | <br>ACS             | <br>Allocation Conventionnelle de <br>Solidarité                                                                                   | <br>ACS               | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 11                 | <br>APP             | <br>Allocation de Préretraite <br>Progressive (ex ACC)                                                                             | <br>PRP               | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 12                 | <br>GRL82           | <br>Garantie de Ressources <br>Licenciement 82                                                                                     | <br>GR                | <br>Régime des garanties de <br>Garanties de Ressources            | <br>Préretraité             |
| <br> 13                 | <br>GRD82           | <br>Garantie de Ressources Démission 82                                                                                            | <br>GR                | <br>Régime des garanties de <br>Garanties de Ressources            | <br>Préretraité             |
| <br> 14                 | <br>GRE82           | <br>Garantie de Ressources Économique 82                                                                                           | <br>GR                | <br>Régime des garanties de <br>Garanties de Ressources            | <br>Préretraité             |
| <br> 15                 | <br>AC-FNE          | <br>Allocation Conventionnelle du FNE 82                                                                                           | <br>ASFNE             | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 16                 | <br>ACS82           | <br>Allocation Conventionnelle de <br>Solidarité 82                                                                                | <br>ACS               | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 17                 | <br>AS-FNE MI-TEMPS | <br>Allocation Spéciale du FNE mi-temps                                                                                            | <br>PRP               | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 18                 | <br>PRP             | <br>Préretraite Progressive                                                                                                        | <br>PRP               | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 21                 | <br>AB84            | <br>Allocation de Base 84                                                                                                          | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 22                 | <br>ABE84           | <br>Allocation de Base Exceptionnelle 84                                                                                           | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 23                 | <br>AFD84           | <br>Allocation de Fin de Droits 84                                                                                                 | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 24                 | <br>AI84            | <br>Allocation d'Insertion 84                                                                                                      | <br>AI                | <br>Régime de Solidarité                                           | <br>Chômeur indemnisé       |
| <br> 25                 | <br>ASS84           | <br>Allocation Spécifique de <br>Solidarité 84                                                                                     | <br>ASS               | <br>Régime de Solidarité                                           | <br>Chômeur indemnisé       |
| <br> 26                 | <br>ACO84           | <br>Allocation Complémentaire 84                                                                                                   | <br>ACO               | <br>Régime Préretraite État                                        | <br>Préretraité             |
| <br> 27                 | <br>AB86            | <br>Allocation de Base 86                                                                                                          | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 28                 | <br>AFD86           | <br>Allocation de Fin de Droits 86                                                                                                 | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 29                 | <br>ASC             | <br>Allocation Spécifique de Conversion                                                                                            | <br>ASC               | <br>Régime des conventions de <br>conversion                       | <br>Stagiaire en formation  |
| <br> 30                 | <br>PIL-ASS         | <br>Programme d'Insertion Locale en ASS                                                                                            | <br>ASS               | <br>Régime de Solidarité                                           | <br>Stagiaire en formation  |
| <br> 31                 | <br>PIL-AFD1        | <br>Programme d'Insertion Locale en AFD <br>taux simple                                                                            | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 32                 | <br>PIL-AFD2        | <br>Programme d'Insertion Locale en AFD <br>taux majoré                                                                            | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 33                 | <br>AFR-AB          | <br>Allocation Formation Reclassement-<br>Taux AB                                                                                  | <br>AFR               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 34                 | <br>AFR-FD          | <br>Allocation Formation Reclassement-<br>Taux AFD                                                                                 | <br>AFR               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 35                 | <br>AFR-FF          | <br>Allocation Formation Reclassement-<br>Taux Forfaitaire                                                                         | <br>AFR               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 36                 | <br>FRE-AB          | <br>Formation Régime État-Taux AB                                                                                                  | <br>FRE               | <br>Régime de Solidarité                                           | <br>Stagiaire en formation  |
| <br> 37                 | <br>FRE-FF          | <br>Formation Régime État-Taux <br>Forfaitaire                                                                                     | <br>FRE               | <br>Régime de Solidarité                                           | <br>Stagiaire en formation  |
| <br> 39                 | <br>RSP             | <br>Régime Stagiaire Public                                                                                                        | <br>RSP               | <br>Régime des Stagiaires <br>du Public                            | <br>Stagiaire en formation  |
| <br> 40                 | <br>AUD             | <br>Allocation Unique Dégressive                                                                                                   | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 41                 | <br>AFFS            | <br>Allocation Formation de Fin <br>de Stage                                                                                       | <br>AFR               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 42                 | <br>ARPE            | <br>Allocation de Remplacement <br>pour l'Emploi                                                                                   | <br>ARPE              | <br>Régime du Fonds <br>d'intervention <br>Paritaire pour l'Emploi | <br>Préretraité             |
| <br> 43                 | <br>ACA             | <br>Allocation Chômeur Âgé                                                                                                         | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur Indemnisé       |
| <br> 44                 | <br>ASS97           | <br>Allocation de Solidarité <br>Spécifique 97                                                                                     | <br>ASS               | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br> 45                 | <br>ACCREASS        | <br>Aide aux Chômeurs Créateurs <br>d'Entreprise                                                                                   | <br>ASS               | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br> 47                 | <br>ARE2001         | <br>Allocation d'Aide au Retour <br>à l'Emploi 2001                                                                                | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur Indemnisé       |
| <br> 48                 | <br>AREF2001        | <br>Allocation d'Aide au Retour <br>à l'Emploi-Formation 2001                                                                      | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 49                 | <br>ARE-AFFS        | <br>ARE-Allocation Formation de <br>Fin de Stage                                                                                   | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>50                  | <br>AFF             | <br>Allocation de Fin de Formation                                                                                                 | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>51                  | <br>ASS-F           | <br>Allocation Spécifique de <br>Solidarité Formation                                                                              | <br>ASS               | <br>Régime de Solidarité                                           | <br>Stagiaire en formation  |
| <br>52                  | <br>AER             | <br>Allocation Équivalent Retraite                                                                                                 | <br>AER               | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br>53 (1)              | <br>AERC            | <br>Allocation Équivalent Retraite <br>de Complément                                                                               | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br> 54                 | <br>ARE2003         | <br>Allocation d'Aide au Retour <br>à l'Emploi 2003                                                                                | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur Indemnisé       |
| <br> 55                 | <br>AREF2003        | <br>Allocation d'Aide au Retour <br>à l'Emploi-Formation 2003                                                                      | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>56                  | <br>ASS2004         | <br>Allocation Spécifique de <br>Solidarité 2004                                                                                   | <br>ASS               | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br>57                  | <br>AFSP            | <br>Allocation du Fonds Spécifique <br>Provisoire                                                                                  | <br>FSP               | <br>Fonds Spécifique Provisoire                                    | <br>Chômeur Indemnisé       |
| <br>58                  | <br>AFSPF           | <br>Allocation du Fonds Spécifique <br>Provisoire Formation                                                                        | <br>FSP               | <br>Fonds Spécifique Provisoire                                    | <br>Stagiaire en formation  |
| <br>59                  | <br>AFT             | <br>Allocation du Fonds Transitoire                                                                                                | <br>FSP               | <br>Fonds Spécifique Provisoire                                    | <br>Chômeur Indemnisé       |
| <br>60                  | <br>AFTF            | <br>Allocation du Fonds Transitoire <br>Formation                                                                                  | <br>FSP               | <br>Fonds Spécifique Provisoire                                    | <br>Stagiaire en formation  |
| <br>61                  | <br>ASR             | <br>Allocation Spécifique de <br>Reclassement                                                                                      | <br>ASR               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>62                  | <br>ASR-ARE         | <br>Allocation Spécifique de <br>Reclassement - Taux ARE                                                                           | <br>ASR               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>63                  | <br>AF              | <br>Allocation forfaitaire<br>(suite à CNE)                                                                                        | <br>AF                | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br> 64                 | <br>ARE2006         | <br>Allocation d'Aide au Retour <br>à l'Emploi 2006                                                                                | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur Indemnisé       |
| <br> 65                 | <br>AREF2006        | <br>Allocation d'Aide au Retour <br>à l'Emploi-Formation 2006                                                                      | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>66 (1)              | <br>ADR06           | <br>Allocation Différentielle au <br>Reclassement 2006                                                                             | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>67 (1)              | <br>ASCRE06         | <br>Aide Spécifique Complémentaire <br>au Retour à l'Emploi 2006                                                                   | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>68 (1)              | <br>ARCE06          | <br>Aide à la Reprise ou à la <br>Création d'Entreprise 2006                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>69 (1)              | <br>ATP-FNE         | <br>Allocation de Transition <br>Professionnelle complémentaire                                                                    | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Stagiaire en formation  |
| <br> 70                 | <br>ATP             | <br>Allocation de Transition <br>Professionnelle                                                                                   | <br>ATP               | <br>Contrat de Transition <br>Professionnelle                      | <br>Stagiaire en formation  |
| <br>71                  | <br>AT              | <br>Alloc, transitoire du <br>Fonds de professionnalisation <br>et de solidarité                                                   | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Chômeur Indemnisé       |
| <br> 72                 | <br>AT-F            | <br>Alloc, transitoire du <br>Fonds de professionnalisation <br>et de solidarité <br>Formation                                     | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Stagiaire en formation  |
| <br>73                  | <br>ATAG1           | <br>Allocation Temporaire <br>d'Attente Groupe 1                                                                                   | <br>ATA               | <br>Régime de Solidarité                                           | <br>Chômeur indemnisé       |
| <br> 74                 | <br>ATAG2           | <br>Allocation Temporaire <br>d'Attente Groupe 2                                                                                   | <br>ATA               | <br>Régime de Solidarité                                           | <br>Chômeur indemnisé       |
| <br> 75                 | <br>APS             | <br>Allocation de <br>professionnalisation <br>et de Solidarité                                                                    | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Chômeur Indemnisé       |
| <br> 76                 | <br>APSF            | <br>Allocation de <br>professionnalisation <br>et de Solidarité Formation                                                          | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Stagiaire en formation  |
| <br> 77                 | <br>AFD             | <br>Allocation Fin de Droit A8 - A10                                                                                               | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Chômeur indemnisé       |
| <br> 78                 | <br>AFDF            | <br>Allocation Fin de Droit <br>Formation A8 - A10                                                                                 | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Stagiaire en formation  |
| <br>79 (1)              | <br>PFM             | <br>Prime Forfaitaire Mensuelle                                                                                                    | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Non concerné            |
| <br>80 (1)              | <br>ICO             | <br>Indemnité Complémentaire <br>(à l'Aref) accordée par l'OPACIF                                                                  | <br>Non concerné      | <br>OPACIF                                                         | <br>Stagiaire en formation  |
| <br> 81                 | <br>RFPE            | <br>Rémunération Formation <br>Pôle emploi                                                                                         | <br>RSP               | <br>Régime Pôle emploi                                             | <br>Stagiaire en formation  |
| <br> 82                 | <br>ARE2009         | <br>Allocation d'Aide au Retour <br>à l'Emploi 2009                                                                                | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br> 83                 | <br>AREF2009        | <br>Allocation d'Aide au Retour <br>à l'Emploi-Formation 2009                                                                      | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 84                 | <br>ASR2009         | <br>Allocation Spécifique de <br>Reclassement 2009                                                                                 | <br>ASR               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br> 85                 | <br>ASRARE09        | <br>Allocation Spécifique de <br>Reclassement 2009 - Taux ARE                                                                      | <br>ASR               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>86 (1)              | <br>ADR09           | <br>Aide Différentielle de <br>Reclassement 2009                                                                                   | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>87 (1)              | <br>ARCE09          | <br>Aide à la Reprise ou à la <br>Création d'Entreprise 2009                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>88 (1)              | <br>ATP09           | <br>Allocation de Transition <br>Professionnelle 2009 <br>Complémentaire (=\>SI3-2009)                                             | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>89 (1)              | <br>PSP             | <br>Prime Salariés Précaires 500€                                                                                                  | <br>Non concerné      | <br>Régime Pôle emploi                                             | <br>Non concerné            |
| <br>90 (1)              | <br>ASA             | <br>Allocation Supplémentaire <br>d'Attente                                                                                        | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Non concerné            |
| <br> 91                 | <br>ATP09ETA        | <br>Allocation de Transition <br>Professionnelle 2009 État                                                                         | <br>ATP               | <br>Contrat de Transition <br>Professionnelle                      | <br>Stagiaire en formation  |
| <br> 92                 | <br>AFDEF09         | <br>Allocation en Faveur des <br>Demandeurs d'Emploi en <br>Formation 2009                                                         | <br>AREF              | <br>Régime Pôle emploi                                             | <br>Stagiaire en formation  |
| <br>93                  | <br>AER2009         | <br>Allocation Équivalent <br>Retraite 2009                                                                                        | <br>AER               | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br>94 (1)              | <br>AER-C2009       | <br>Allocation Équivalent <br>Retraite 2009 de complément                                                                          | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Non concerné            |
| <br>95                  | <br>AFDEF10         | <br>Allocation en Faveur des <br>Demandeurs d'Emploi en <br>Formation 2010                                                         | <br>AREF              | <br>Régime Pôle emploi                                             | <br>Stagiaire en formation  |
| <br>96                  | <br>AEPE2010        | <br>Aide Exceptionnelle <br>pour l'Emploi 2010                                                                                     | <br>AEPE              | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br>97                  | <br>AER2010         | <br>Allocation Équivalent <br>Retraite 2010                                                                                        | <br>AER               | <br>Régime de Solidarité                                           | <br>Chômeur Indemnisé       |
| <br>98 (1)              | <br>AER-C2010       | <br>Allocation Equivalent <br>Retraite 2010<br>de complément                                                                       | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Non concerné            |
| <br>99                  | <br>RFF             | <br>Rémunération de Fin de <br>Formation 2011                                                                                      | <br>AREF              | <br>Régime Pôle emploi                                             | <br>Stagiaire en formation  |
| <br>AC                  | <br>ARE2011         | <br>Allocation d'Aide au Retour <br>à l'Emploi 2011                                                                                | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>AD                  | <br>AREF2011        | <br>Allocation d'Aide au Retour <br>à l'Emploi - Formation 2011                                                                    | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AE                  | <br>ARE-CG          | <br>Allocation d'Aide au Retour <br>à l'Emploi - Convention de <br>Gestion ONP\*                                                   | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>AF                  | <br>AREF-CG         | <br>Allocation d'Aide au retour <br>à l'Emploi - Formation - <br>Convention de Gestion ONP\*                                       | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AG (1)              | <br>ADR11           | <br>Aide Différentielle de <br>Reclassement 2011                                                                                   | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>AH (1)              | <br>ARCE11          | <br>Aide à la Reprise ou à la <br>Création d'Entreprise 2011                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>AI (1)              | <br>ADR-CG          | <br>Aide Différentielle de <br>Reclassement - Convention de <br>Gestion ONP\*                                                      | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>AJ (1)              | <br>ARCE-CG         | <br>Aide à la Reprise ou à la <br>Création d'Entreprise - <br>Convention de Gestion ONP\*                                          | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>AK                  | <br>ASP-ARE         | <br>Allocation de Sécurisation <br>\*Professionnelle - Taux ARE                                                                    | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AL                  | <br>ASP-AREF        | <br>Allocation de Sécurisation <br>Professionnelle en formation - <br>Taux ARE                                                     | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AM                  | <br>ASPRAC1         | <br>Allocation de Sécurisation <br>Professionnelle RAC 1                                                                           | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AN                  | <br>ASPRAC1F        | <br>Allocation de Sécurisation <br>Professionnelle RAC 1 Formation                                                                 | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AO                  | <br>ASPETAT         | <br>Allocation de Sécurisation <br>Professionnelle État                                                                            | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AP                  | <br>ASPETATF        | <br>Allocation de Sécurisation <br>Professionnelle État-Formation                                                                  | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AQ                  | <br>ASPRAC2         | <br>Allocation de Sécurisation <br>Professionnelle RAC 2                                                                           | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AR                  | <br>ASPRAC2F        | <br>Allocation de Sécurisation <br>Professionnelle RAC2 Formation                                                                  | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>AS (1)              | <br>IDR-CSP         | <br>Indemnité Différentielle <br>de Reclassement CSP                                                                               | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>AT                  | <br>ATS2011         | <br>Allocation Transitoire de <br>Solidarité 2011                                                                                  | <br>AER               | <br>Régime de solidarité                                           | <br>Chômeur indemnisé       |
| <br>AV (1)              | <br>ATS-C2011       | <br>Allocation Transitoire de <br>Solidarité 2011 de complément                                                                    | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Non concerné            |
| <br>AW (1)              | <br>DC              | <br>Allocation DECES                                                                                                               | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>AY                  | <br>RFF2012         | <br>Rémunération de Fin de <br>Formation 2012                                                                                      | <br>AREF              | <br>Pôle emploi                                                    | <br>Stagiaire en formation  |
| <br>AZ (1)              | <br>ARCE12          | <br>Aide à la Reprise ou à la <br>Création d'Entreprise 2012                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>BA (1)              | <br>ARCE12CG        | <br>Aide reprise/création <br>d'entreprise 2012 - <br>Convention de Gestion ONP\*                                                  | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>BB (2)              | <br>AREM            | <br>Allocation d'Aide au Retour <br>à l'Emploi - Mayotte                                                                           | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>BC (2)              | <br>AREFM           | <br>Allocation d'Aide au Retour <br>à l'Emploi - Formation - <br>Mayotte                                                           | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BD (2)              | <br>ASSM            | <br>Allocation de Solidarité <br>Spécifique - Mayotte                                                                              | <br>ASS               | <br>Régime de Solidarité                                           | <br>Chômeur indemnisé       |
| <br>BE                  | <br>ATS2013         | <br>Allocation Transitoire <br>de Solidarité 2013                                                                                  | <br>AER               | <br>Régime de solidarité                                           | <br>Chômeur indemnisé       |
| <br>BF (1)              | <br>ATS-C2013       | <br>Allocation Transitoire <br>de Solidarité 2013 de <br>complément                                                                | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Non concerné            |
| <br>BG                  | <br>RFF2013         | <br>Rémunération de Fin de <br>Formation 2013                                                                                      | <br>AREF              | <br>Régime Pôle emploi                                             | <br>Stagiaire en formation  |
| <br>BH (2)              | <br>AREMCG          | <br>Allocation d'Aide au Retour <br>à l'Emploi - Mayotte - <br>Convention de Gestion ONP                                           | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>BI (2)              | <br>AREFMCG         | <br>Allocation d'Aide au Retour <br>à l'Emploi - Formation -<br> Mayotte - Convention de <br>Gestion ONP                           | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BJ                  | <br>RFF2014         | <br>Rémunération de Fin de <br>Formation 2014                                                                                      | <br>AREF              | <br>Régime Pôle emploi                                             | <br>Stagiaire en formation  |
| <br>BK                  | <br>ARE2014         | <br>Allocation d'Aide au retour <br>à l'Emploi 2014                                                                                | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>BL (1)              | <br>DC2014          | <br>Allocation DECES 2014                                                                                                          | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>BM                  | <br>ARE-CG14        | <br>Allocation d'Aide au retour<br>à l'Emploi - Convention de <br>Gestion ONP\* 2014                                               | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>BN                  | <br>AREF14          | <br>Allocation d'Aide au retour <br>à l'Emploi- Formation 2014                                                                     | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BO                  | <br>AREF-CG14       | <br>Allocation d'Aide au retour <br>à l'Emploi - Formation- <br>Convention de Gestion ONP <br>2014                                 | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BP                  | <br>ARE14DS         | <br>Allocation d'Aide au Retour <br>à l'Emploi 2014 - Différé                                                                      | <br>DIS               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>BQ                  | <br>AREF14DS        | <br>Allocation d'Aide au Retour <br>à l'Emploi - Formation 2014 - <br>Différé                                                      | <br>DIS               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BR                  | <br>RFF2015         | <br>Rémunération de Fin de <br>Formation 2015                                                                                      | <br>AREF              | <br>Régime Pôle Emploi                                             | <br>Stagiaire en formation  |
| <br>BS                  | <br>ATS-R15         | <br>Allocation Transitoire de <br>Solidarité de Remplacement 2015                                                                  | <br>AER               | <br>Régime de solidarité                                           | <br>Chômeur indemnisé       |
| <br>BT (1)              | <br>ATS-C15         | <br>Allocation Transitoire de <br>Solidarité de Complément 2015                                                                    | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Non concerné            |
| <br>BU                  | <br>ASP15R2         | <br>ASP 2015 avec ancienneté <br>entre 1 et 2 ans RAC - hors <br>formation                                                         | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BV                  | <br>ASP15E2         | <br>ASP 2015 avec une ancienneté <br>entre 1 et 2 ans État - hors<br> formation                                                    | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BW                  | <br>ASP15R3         | <br>ASP 2015 avec une <br>ancienneté supérieure <br>à 2 ans hors formation                                                         | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BX (1)              | <br>ASP15DC         | <br>Allocation décès en cours <br>d'ASP 2015                                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>BY                  | <br>ASP15R1         | <br>ASP 2015 avec une <br>ancienneté inférieure <br>à 1 an hors formation                                                          | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>BZ                  | <br>ASP15R2F        | <br>ASP 2015 avec une ancienneté <br>entre 1 et 2 ans RAC - <br>formation                                                          | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CA                  | <br>ASP15E2F        | <br>ASP 2015 avec une <br>ancienneté entre 1 et <br>2 ans État - en formation                                                      | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CB                  | <br>ASP15R3F        | <br>ASP 2015 avec une <br>ancienneté supérieure <br>à 2 ans formation                                                              | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CC                  | <br>ASP15R1F        | <br>ASP 2015 avec une ancienneté <br>inférieure à 1 an formation                                                                   | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CD (1)              | <br>IDRCSP15        | <br>Indemnité Différentiel de <br>Reclassement CSP sur de <br>l'ASP 2015                                                           | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>CE (1)              | <br>CSPPR15         | <br>Prime ASP sans financement <br>partagé (entièrement RAC)                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>CF(1)               | <br>CSPPR15E        | <br>Prime ASP avec financement <br>partagé (part État)                                                                             | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>CG(1)               | <br>CSPPR15R        | <br>Prime ASP avec financement <br>partagé (part RAC)                                                                              | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>CH(1)               | <br>PTS15           | <br>Prime Transitoire de <br>Solidarité 2015                                                                                       | <br>Non concerné      | <br>Régime de Solidarité                                           | <br>Non concerné            |
| <br>CI                  | <br>RFF2016         | <br>Rémunération de Fin de <br>Formation 2016                                                                                      | <br>AREF              | <br>Régime Pôle Emploi                                             | <br>Stagiaire en formation  |
| <br>CJ (2)              | <br>AREM16          | <br>Allocation d'Aide au Retour <br>à l'Emploi - Mayotte 2016                                                                      | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>CK (2)              | <br>AREFM16         | <br>Allocation d'Aide au Retour <br>à l'Emploi - Formation - <br>Mayotte 2016                                                      | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CL (2)              | <br>AREMCG16        | <br>Allocation d'Aide au Retour <br>à l'Emploi - Mayotte - <br>Convention de Gestion - 2016                                        | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>CM (2)              | <br>AREFMCG16       | <br>Allocation d'Aide au Retour <br>à l'Emploi - Formation - <br>Mayotte - Convention de <br>Gestion 2016                          | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CN                  | <br>AREA816         | <br>Allocation d'Aide au Retour <br>à l'Emploi Intermittents <br>A8-A10 2016                                                       | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>CO                  | <br>AREFA816        | <br>Allocation d'Aide au Retour <br>à l'Emploi Formation <br>Intermittents A8-A10 2016                                             | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CP (1)              | <br>ARCEA816        | <br>Aide à la Reprise où à la <br>Création d'Entreprise <br>Intermittents A8-A10 2016                                              | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>CQ                  | <br>AREDS16         | <br>Allocation d'Aide au Retour <br>à l'Emploi 2016 - Différé                                                                      | <br>DIS               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>CR                  | <br>AREFDS16        | <br>Allocation d'Aide au Retour <br>à l'Emploi - Formation 2016 - <br>Différé                                                      | <br>DIS               | <br>Régime Assurance                                               | <br>Stagiaire en formation  |
| <br>CS (1)              | <br>DCA816          | <br>Allocation DECES A8-A10 2016                                                                                                   | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>CT                  | <br>ARER16          | <br>Allocation d'Aide au Retour <br>à l'Emploi de Rattrapage <br>Intermittents A8-A10 2016                                         | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>CU                  | <br>ARERF16         | <br>Allocation d'Aide au Retour <br>à l'Emploi de Rattrapage <br>Formation Intermittents <br>A8-A10 2016                           | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CV (1)              | <br>DCR16           | <br>Allocation DECES de Rattrapage <br>Intermittents A8-A10 2016                                                                   | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>CW(1)               | <br>AAH16           | <br>Avance allocation adultes <br>handicapés                                                                                       | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>CX                  | <br>RFF17           | <br>Rémunération de Fin de <br>Formation 2017                                                                                      | <br>AREF              | <br>Régime Pôle Emploi                                             | <br>Stagiaire en formation  |
| <br>CY                  | <br>AAP17           | <br>AAP are                                                                                                                        | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>CZ                  | <br>AAP17R          | <br>AAP droit commun <br>participation RAC                                                                                         | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DA                  | <br>AAP17E          | <br>AAP droit commun <br>participation État                                                                                        | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DB                  | <br>AAP17G          | <br>AAP are cg                                                                                                                     | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DC                  | <br>AAP17CG         | <br>AAP droit commun <br>participation CG                                                                                          | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DD                  | <br>AAP17GE         | <br>AAP droit commun <br>participation État                                                                                        | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DE                  | <br>AAP17F          | <br>AAP are formation                                                                                                              | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DF                  | <br>AAP17FR         | <br>AAP droit commun <br>participation RAC                                                                                         | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DG                  | <br>AAP17FE         | <br>AAP droit commun <br>participation État                                                                                        | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DH                  | <br>AAP17GF         | <br>AAP are CG formation                                                                                                           | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DI                  | <br>AAP17CGF        | <br>AAP droit commun <br>participation CG Form                                                                                     | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DJ                  | <br>AAP17GFE        | <br>AAP droit commun <br>participation État form                                                                                   | <br>AAP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DK(1)               | <br>AAP17DC         | <br>AAP 17 Allocation décès                                                                                                        | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>DL(1)               | <br>AAP17DCG        | <br>AAP 17 Allocation décès CG                                                                                                     | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>DM                  | <br>ARE2017         | <br>Are 2017                                                                                                                       | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>DN(1)               | <br>DC2017          | <br>Allocation décès 2017                                                                                                          | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>DO                  | <br>ARE-CG17        | <br>Are 2017 convention de <br>gestion                                                                                             | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>DP(1)               | <br>DCARECG17       | <br>Allocation décès 2017 <br>au titre de l'ARE17CG                                                                                | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>DQ                  | <br>AREF17          | <br>Are Formation 2017                                                                                                             | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DR                  | <br>AREFCG17        | <br>Are Formation conv <br>gestion 2017                                                                                            | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DS(1)               | <br>ARCECG17        | <br>Allocation reprise ou <br>création entreprise <br>convention de gestion 17                                                     | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>DT                  | <br>ARER17          | <br>Allocation d'aide au retour <br>à l'emploi A8-A10 versée <br>au cours de la clause <br>de rattrapage                           | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>DU                  | <br>ARERF17         | <br>Allocation d'aide <br>au retour à l'emploi <br>en cours de formation <br>A8-A10 versée au cours <br>de la clause de rattrapage | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>DV                  | <br>APS2017         | <br>Allocation de <br>professionnalisation <br>et de Solidarité 2017                                                               | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Chômeur Indemnisé       |
| <br>DW                  | <br>AFD2017         | <br>Allocation de fin de <br>droits 2017                                                                                           | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Chômeur indemnisé       |
| <br>DX                  | <br>APSF2017        | <br>APS formation 17                                                                                                               | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Stagiaire en formation  |
| <br>DY                  | <br>AFDF2017        | <br>AFD formation 17                                                                                                               | <br>FPS               | <br>Fonds de Professionnalisation <br>et de Solidarité             | <br>Stagiaire en formation  |
| <br>DZ                  | <br>RFF18           | <br>Rémunération de Fin de <br>Formation 2018                                                                                      | <br>AREF              | <br>Régime Pôle Emploi                                             | <br>Stagiaire en formation  |
| <br>EA                  | <br>ATI             | <br>Allocation des travailleurs <br>indépendants                                                                                   | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>EB                  | <br>ATIF            | <br>Allocation des travailleurs <br>indépendants -- Formation                                                                      | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>EC                  | <br>ADM             | <br>Allocation des démissionnaires <br>« pour projet de reconversion <br>professionnelle »                                         | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>ED(1)               | <br>ARCE17          | <br>Allocation reprise ou création <br>entreprise 17                                                                               | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>EE                  | <br>RFF19           | <br>Rémunération de Fin de <br>Formation 2019                                                                                      | <br>AREF              | <br>Régime Pôle Emploi                                             | <br>Stagiaire en formation  |
| <br>EF                  | <br>ARE2019         | <br>Are 2019                                                                                                                       | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>EG(1)               | <br>DC2019          | <br>Allocation décès 2019                                                                                                          | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>EH(1)               | <br>ARCE19          | <br>Allocation reprise ou création <br>entreprise 19                                                                               | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>EI                  | <br>ARE-CG19        | <br>Are 2019 convention de gestion                                                                                                 | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>EJ(1)               | <br>DCARECG19       | <br>Allocation décès 2019 au titre <br>de l'ARE19CG                                                                                | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>EK(1)               | <br>ARCECG19        | <br>Allocation reprise ou <br>création entreprise <br>convention de gestion 19                                                     | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>EL                  | <br>AREF19          | <br>Are Formation 2019                                                                                                             | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>EM                  | <br>AREFCG19        | <br>Are Formation conv gestion 2019                                                                                                | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>EN                  | <br>ARER19          | <br>Allocation d'aide au retour <br>à l'emploi A8-A10 versée au <br>cours de la clause de <br>rattrapage 2019                      | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>EO                  | <br>ARERF19         | <br>Allocation d'Aide au Retour <br>à l'Emploi de Rattrapage <br>Formation Intermittents <br>A8-A10 2019                           | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>EP                  | <br>ADM-F           | <br>Allocation pour les <br>démissionnaires en formation <br>pour « projet de <br>reconversion professionnelle »                   | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>EQ                  | <br>RFF2020         | <br>Rémunération de Fin de <br>Formation 2020                                                                                      | <br>AREF              | <br>Régime Pôle Emploi                                             | <br>Stagiaire en formation  |
| <br>ER                  | <br>RFF2021         | <br>Rémunération de Fin de <br>Formation 2021                                                                                      | <br>AREF              | <br>Régime Pôle Emploi                                             | <br>Stagiaire en formation  |
| <br>ES                  | <br>PEP20           | <br>PRIME PERMITTENTS                                                                                                              | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>PEP20                   |
| <br>ET                  | <br>AIJ20           | <br>PRIME JEUNES EN AIJ                                                                                                            | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>AIJ20                   |
| <br>EU                  | <br>AJD20           | <br>PRIME JEUNES DIPLOMES <br>EX-BOURSIER                                                                                          | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>AJD20                   |
| <br>EV                  | <br>AIJA20          | <br>PRIME JEUNES EN AIJ APEC                                                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>AIJA20                  |
| <br>EW                  | <br>ARE21           | <br>ARE 2021                                                                                                                       | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>EX                  | <br>AREF21          | <br>ARE FORMATION 2021                                                                                                             | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>EY                  | <br>ARE-CG21        | <br>ARE 2021 Convention de <br>Gestion                                                                                             | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>EZ                  | <br>AREFCG21        | <br>ARE FORMATION CONV <br>GESTION 2021                                                                                            | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>FA                  | <br>AFFORM          | <br>Aide forfaitaire à la <br>\*formation                                                                                          | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FB                  | <br>AGE             | <br>Aide à la garde d'enfant                                                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FC                  | <br>FSSAACRE        | <br>FSSA aide à la création ou <br>reprise d'entreprise                                                                            | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FD                  | <br>FSSAAMOB        | <br>FSSA aide à la mobilité <br>géographique                                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FE                  | <br>FSSAAFAM        | <br>FSSA aide aux familles                                                                                                         | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FF                  | <br>FSSAPREC        | <br>FSSA prime exceptionnelle de <br>reclassement                                                                                  | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FG                  | <br>ACEJ            | <br>Allocation Contrat<br>d'Engagement Jeune                                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FH                  | <br>RFF2022         | <br>Rémunération de Fin de <br>Formation 2022                                                                                      | <br>AREF              | <br>Régime Pôle Emploi                                             | <br>Stagiaire en formation  |
| <br>FI                  | <br>IINFL           | <br>Indemnité inflation                                                                                                            | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FJ                  | <br>DELD            | <br>Aide DELD (Demandeur <br>D'emploi Long Durée)                                                                                  | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FK                  | <br>APJE            | <br>Aide jeune 2022                                                                                                                | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non concerné            |
| <br>FL                  | <br>ARE21           | <br>ARE 2021                                                                                                                       | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FM                  | <br>ARER21          | <br>ARE 2021 DE RATTRAPAGE                                                                                                         | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FN                  | <br>ARE-CG21        | <br>ARE 2021 Convention de <br>Gestion                                                                                             | <br>AUD               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FO                  | <br>AREF21          | <br>ARE Formation 2021                                                                                                             | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>FP                  | <br>AREF21          | <br><br>ARE Formation 2021<br>de rattrapage                                                                                        | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FQ                  | <br>AREF21CG        | <br>ARE Formation 2021 <br>Convention de Gestion                                                                                   | <br>AREF              | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>FR                  | <br>ASP21S1         | <br>ASP spécifique ASP-S1                                                                                                          | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FS                  | <br>ASP21S2         | <br>ASP spécifique ASP-S2                                                                                                          | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FT                  | <br>ASP21R2         | <br>ASP Droit commun Part <br>Unédic 21                                                                                            | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FU                  | <br>ASP21E2         | <br>ASP Droit commun Part <br>État 21                                                                                              | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FV                  | <br>ASP21R3         | <br>ASP Droit commun 21                                                                                                            | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FW                  | <br>ASP21DC         | <br>Allocation décès CSP 21                                                                                                        | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>FX                  | <br>ASP21R1         | <br>ASP-R 21                                                                                                                       | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>FY                  | <br>IDRCSP21        | <br>IDR 21                                                                                                                         | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>FZ                  | <br>CSPPR21         | <br>Prime de reclassement <br>totalement Unédic 21                                                                                 | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>GA                  | <br>CSPPR21E        | <br>Prime de reclassement <br>Part Unédic 21                                                                                       | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>GB                  | <br>CSPPR21R        | <br>Prime de reclassement <br>Part État 21                                                                                         | <br>Non concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>GC                  | <br>ASP21S1F        | <br>ASP spécifique formation <br>ASP-S1                                                                                            | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>GD                  | <br>ASP21S2F        | <br>ASP spécifique formation <br>ASP-S2                                                                                            | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>GE                  | <br>ASP21R2F        | <br>ASP Droit commun formation <br>Part Unédic 21                                                                                  | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>GF                  | <br>ASP21E2F        | <br>ASP Droit commun formation <br>21 Part État 21                                                                                 | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>GG                  | <br>ASP21R3F        | <br>ASP Droit commun formation 21                                                                                                  | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>GH                  | <br>ASP21R1F        | <br>ASP-R Formation 21                                                                                                             | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>GI                  | <br>ATI22           | <br>Allocation Travailleur <br>Indépendant 2022                                                                                    | <br>ATI               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>GJ                  | <br>ATI22-F         | <br>Allocation de Formation <br>Travailleur Indépendant 2022                                                                       | <br>ATI               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>GK                  | <br>ARECSP21        | <br>ARE-CSP21                                                                                                                      | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Chômeur indemnisé       |
| <br>GL                  | <br>ARECS21F        | <br>ARE-CSP FORMATION 21                                                                                                           | <br>ASP               | <br>Régime Assurance Chômage                                       | <br>Stagiaire en formation  |
| <br>GM                  | <br>FSSAMASP        | <br>FSSA Aide au maintien de l'<br>allocation équivalente ASP                                                                      | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>GN                  | <br>FSSAMRAN        | <br>FSSA Aide au maintien de la <br>rémunération antérieure                                                                        | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>GO                  | <br>AES-S22         | <br>Aide Exceptionnelle de <br>Solidarité Socle 2022                                                                               | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>GP                  | <br>AES-E22         | <br>Aide Exceptionnelle de <br>Solidarité Enfant 2022                                                                              | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
| <br>GQ                  | <br>AREG            | <br>Aide Spécifique Régionale                                                                                                      | <br>Non Concerné      | <br>Régime Assurance Chômage                                       | <br>Non Concerné            |
