---
title: "Dictionnaire des données"
editor: 
  markdown: 
    wrap: 72
---

Le FHS contient plusieurs tables :

-   la table DE ;

-   la table D2 ;

-   la table P2 ;

-   la table E3 ;

-   la table E3cons ;

-   la table E0.

## La table DE

+----------------+----------------+----------------+----------------+
| -   \*Va       | **Libellé**    | -   \*Mo       | **C o m        |
|                |                |                | mentaires**    |
|    riables\*\* |                |    dalités\*\* |                |
+================+================+================+================+
| Age            | Age du         |                | En année       |
|                | demandeur au   |                |                |
|                | 31/12 de       |                |                |
|                | l'année d '    |                |                |
|                | inscription de |                |                |
|                | la demande     |                |                |
|                | associée       |                |                |
+----------------+----------------+----------------+----------------+
| ALE            | Numéro de      | Numéro de      |                |
|                | l'Agence       | l'ALE (unité   |                |
|                | Locale pour    | locale de Pôle |                |
|                | l'Emploi d '   | emploi). Les   |                |
|                | inscription du | deux premiers  |                |
|                | demandeur      | caractères     |                |
|                |                | donnent le     |                |
|                |                | département    |                |
+----------------+----------------+----------------+----------------+
| ANCIEN         | Ancienneté     | En mois révolu |                |
|                | dans la        | au dernier     |                |
|                | demande        | jour du mois   |                |
|                |                | de fermeture   |                |
|                |                | de la demande. |                |
|                |                | Si la demande  |                |
|                |                | est en cours   |                |
|                |                | il s'agit de l |                |
|                |                | 'ancienneté au |                |
|                |                | dernier jour   |                |
|                |                | du fichier.    |                |
+----------------+----------------+----------------+----------------+
| API            | Allocation     | 0\. Non b é    | Remplacé en    |
|                | parent isolé   | néficiaires de | 2009 par le    |
|                |                | l'API          | RSA            |
|                |                |                |                |
|                |                | 1\. B          |                |
|                |                | énéficiaire de |                |
|                |                | l'API (saisie  |                |
|                |                | manuelle)      |                |
|                |                |                |                |
|                |                | 2\. B          |                |
|                |                | énéficiaire de |                |
|                |                | l'API (        |                |
|                |                | information    |                |
|                |                | CNASEA)        |                |
|                |                |                |                |
|                |                | 3\. Demande    |                |
|                |                | API en cours d |                |
|                |                | ' instruction  |                |
+----------------+----------------+----------------+----------------+
| AXETRAV        | Axe de travail | P. Projet      |                |
|                |                |                |                |
|                |                | R.  Recherche  |                |
|                |                |                |                |
|                |                | A. À           |                |
|                |                | approfondir    |                |
|                |                |                |                |
|                |                | E.  Recherche  |                |
|                |                |     d'emploi   |                |
|                |                |                |                |
|                |                | F. Freins p é  |                |
|                |                | riphériques à  |                |
|                |                | l'emploi       |                |
|                |                |                |                |
|                |                | M. Mobilité p  |                |
|                |                | r o f          |                |
|                |                | essionnelle    |                |
+----------------+----------------+----------------+----------------+
| CATREGR        | Catégorie o p  | 1\. Personnes  |                |
|                | é rationnelle  | i m            |                |
|                | du demandeur   | médiatement    |                |
|                | relative à la  | disponibles et |                |
|                | dernière       | à la recherche |                |
|                | situation      | d'un emploi    |                |
|                | connue         | sous CDI à     |                |
|                |                | temps plein    |                |
|                |                |                |                |
|                |                | 2\. Personnes  |                |
|                |                | i m            |                |
|                |                | médiatement    |                |
|                |                | disponibles et |                |
|                |                | à la recherche |                |
|                |                | d'un emploi    |                |
|                |                | sous CDI à     |                |
|                |                | temps partiel  |                |
|                |                |                |                |
|                |                | 3\. Personnes  |                |
|                |                | i m            |                |
|                |                | médiatement    |                |
|                |                | disponibles et |                |
|                |                | à la recherche |                |
|                |                | d'un emploi à  |                |
|                |                | durée limitée  |                |
|                |                | (CDD, mission  |                |
|                |                | d'intérim, v   |                |
|                |                | acation...)    |                |
|                |                |                |                |
|                |                | 4\. Personnes  |                |
|                |                | à la recherche |                |
|                |                | d'un emploi    |                |
|                |                | mais non i m   |                |
|                |                | médiatement    |                |
|                |                | disponibles    |                |
|                |                | (en formation, |                |
|                |                | en arrêt       |                |
|                |                | maladie, en    |                |
|                |                | congé          |                |
|                |                | maternité, en  |                |
|                |                | CRP...)        |                |
|                |                |                |                |
|                |                | 5\. Personnes  |                |
|                |                | pourvues d'un  |                |
|                |                | emploi, à la   |                |
|                |                | recherche d'un |                |
|                |                | autre emploi   |                |
|                |                | donc non i m   |                |
|                |                | médiatement d  |                |
|                |                | isponibles.    |                |
|                |                | Figurent ici   |                |
|                |                | les personnes  |                |
|                |                | en contrat     |                |
|                |                | emploi so l i  |                |
|                |                | d arité (CES,  |                |
|                |                | CIE ou autres  |                |
|                |                | contrat        |                |
|                |                | aidés...).     |                |
+----------------+----------------+----------------+----------------+
| CEMPLOI        | Composante     | CE1. DE        |                |
|                | emploi du      | positionné sur |                |
|                | demandeur      | un métier en t |                |
|                | d'emploi       | e n s          |                |
|                |                | ion/porteur    |                |
|                |                |                |                |
|                |                | CE2. DE non    |                |
|                |                | positionné sur |                |
|                |                | un métier en t |                |
|                |                | e n s          |                |
|                |                | ion/porteur    |                |
+----------------+----------------+----------------+----------------+
| CONTRAT        | Type de        | 1\. Contrat à  |                |
|                | contrat        | durée i        |                |
|                | recherché par  | ndéterminée    |                |
|                | le demandeur   |                |                |
|                | (dernière      | 2\. Contrat à  |                |
|                | valeur connue  | durée          |                |
|                | sur la         | déterminée ou  |                |
|                | demande)       | temporaire     |                |
|                |                |                |                |
|                |                | 3\. Contrat    |                |
|                |                | saisonnier     |                |
+----------------+----------------+----------------+----------------+
| CUCS           | Demandeurs     |                | A pris fin en  |
|                | résidant en    |                | 2014           |
|                | zone CUCS      |                |                |
|                | (Contrat       |                |                |
|                | Urbain de      |                |                |
|                | Cohésion       |                |                |
|                | Sociale)       |                |                |
+----------------+----------------+----------------+----------------+
| DATANN         | Date d         | La demande est |                |
|                | 'annulation de | en cours à la  |                |
|                | la demande     | date           |                |
|                |                | statistique du |                |
|                |                | fichier.       |                |
|                |                |                |                |
|                |                | D ate          |                |
|                |                | exclusive      |                |
|                |                |                |                |
|                |                | : si DATA N N  |                |
|                |                | = 01/02/2010,  |                |
|                |                | le dernier     |                |
|                |                | jour           |                |
|                |                |                |                |
|                |                | d '            |                |
|                |                | inscription    |                |
|                |                | sur cette      |                |
|                |                | demande est le |                |
|                |                |                |                |
|                |                | 31/01/2010.    |                |
+----------------+----------------+----------------+----------------+
| DATINS         | Date d'effet d | L '            |                |
|                | ' inscription  | inscription    |                |
|                | de la demande  | commence ce    |                |
|                |                | jour           |                |
+----------------+----------------+----------------+----------------+
| DATNAIS        | Date de        | Mois de        |                |
|                | naissance      | naissance (le  |                |
|                | (année et      | jour exact     |                |
|                | mois)          | n'est pas      |                |
|                |                | renseigné, il  |                |
|                |                | est fixé conve |                |
|                |                | n t i          |                |
|                |                | onnellement à  |                |
|                |                | 15)            |                |
+----------------+----------------+----------------+----------------+
| DATSINS        | Date de saisie |                |                |
|                | d '            |                |                |
|                | inscription de |                |                |
|                | la demande     |                |                |
+----------------+----------------+----------------+----------------+
| DEPCOM         | Commune de     | En principe,   |                |
|                | résidence du   | c'est le Code  |                |
|                | demandeur      | Officiel G é   |                |
|                |                | ographique.    |                |
|                |                | Toutefois, il  |                |
|                |                | peut y avoir   |                |
|                |                | des valeurs n  |                |
|                |                | o n            |                |
|                |                | -conformes.    |                |
|                |                | Les deux       |                |
|                |                | premiers       |                |
|                |                | caractères     |                |
|                |                | donnent de     |                |
|                |                | département    |                |
+----------------+----------------+----------------+----------------+
| DIPLOME        | Diplôme obtenu | D. Diplômé     |                |
|                | par le         |                |                |
|                | demandeur lors | N. Non diplômé |                |
|                | de son         |                |                |
|                | inscription    |                |                |
+----------------+----------------+----------------+----------------+
| EXPER          | Expérience     | Nombre         | Il existe des  |
|                | dans le ROME   | expérience.    | cas où le      |
|                | demandé.       | Arrondi à l '  | nombre d'année |
|                |                | a ppréciation  | d 'expérience  |
|                |                | du conseiller  | est supérieur  |
|                |                |                | à l'âge du     |
|                |                |                | demandeur      |
|                |                |                | d'emploi       |
+----------------+----------------+----------------+----------------+
| EXPEUNIT       | Unité durée    |                |                |
|                | expérience     |                |                |
|                | dans le le     |                |                |
|                | ROME           |                |                |
+----------------+----------------+----------------+----------------+
| MOBDIST        | Mobilité du DE | Mobilité du DE |                |
|                |                | vis-à-vis de   |                |
|                |                | l'emploi, en   |                |
|                |                | minutes,       |                |
|                |                | heures,        |                |
|                |                | kilomètres ou  |                |
|                |                | FE selon la    |                |
|                |                | valeur de la   |                |
|                |                | variable       |                |
|                |                | MOBUNIT. Il    |                |
|                |                | faut           |                |
|                |                | l'utiliser     |                |
|                |                | avec la        |                |
|                |                | variable       |                |
|                |                | MOBUNIT pour   |                |
|                |                | lui donner un  |                |
|                |                | sens.          |                |
+----------------+----------------+----------------+----------------+
| MOBUNIT        | Unité de la    | 00\. Non       |                |
|                | mobilité du    | renseignée     |                |
|                | demandeur      |                |                |
|                | vis-à-vis de   | FE. France     |                |
|                | l'emploi       | Entière        |                |
|                |                |                |                |
|                |                | H. Heure       |                |
|                |                |                |                |
|                |                | KM. Kilomètres |                |
|                |                |                |                |
|                |                | MN. Minutes    |                |
|                |                |                |                |
|                |                | MT. Mobilité   |                |
|                |                | totale         |                |
+----------------+----------------+----------------+----------------+
| MOTANN         | Motif d        | ' '. Non       |                |
|                | 'annulation de | renseigné : la |                |
|                | la demande     | demande est en |                |
|                |                | cours.         |                |
|                |                |                |                |
|                |                | 01\. Reprise   |                |
|                |                | d'emploi, hors |                |
|                |                | contrat aidés  |                |
|                |                | et création d  |                |
|                |                | 'entreprise    |                |
|                |                |                |                |
|                |                | 02\. Entrée en |                |
|                |                | stage de       |                |
|                |                | formation      |                |
|                |                |                |                |
|                |                | 03\. Maladie,  |                |
|                |                | maternité,     |                |
|                |                | accident       |                |
|                |                | travail        |                |
|                |                |                |                |
|                |                | 04\. Dispense  |                |
|                |                | recherche      |                |
|                |                | d'emploi       |                |
|                |                |                |                |
|                |                | 05\. Retraite  |                |
|                |                |                |                |
|                |                | 06\.           |                |
|                |                | Changement     |                |
|                |                | d'ALE avec     |                |
|                |                | changement     |                |
|                |                | d'Assedic      |                |
|                |                |                |                |
|                |                | 07\. Service   |                |
|                |                | Militaire      |                |
|                |                |                |                |
|                |                | 08\. Autre     |                |
|                |                | arrêt de       |                |
|                |                | recherche      |                |
|                |                |                |                |
|                |                | 09\. Absence   |                |
|                |                | au contrôle    |                |
|                |                |                |                |
|                |                | 10\. Radiation |                |
|                |                | a d m          |                |
|                |                | inistrative    |                |
|                |                | pour non p     |                |
|                |                | résentation    |                |
|                |                | suite à une    |                |
|                |                | convocation    |                |
|                |                |                |                |
|                |                | 11\. Autres    |                |
|                |                | radiation a d  |                |
|                |                | m i            |                |
|                |                | nistratives :  |                |
|                |                | refus          |                |
|                |                | d'emploi, de   |                |
|                |                | formation,     |                |
|                |                | fausse d       |                |
|                |                | éclaration,    |                |
|                |                | manque d'actes |                |
|                |                | positifs de    |                |
|                |                | recherche      |                |
|                |                |                |                |
|                |                | 12\. Autre cas |                |
|                |                |                |                |
|                |                | 13\. Absence   |                |
|                |                | de mise à jour |                |
|                |                | du dossier     |                |
|                |                |                |                |
|                |                | 15\. Reprise   |                |
|                |                | d'emploi en    |                |
|                |                | contrat aidé   |                |
|                |                |                |                |
|                |                | 16\. Reprise   |                |
|                |                | d'emploi :     |                |
|                |                | création d     |                |
|                |                | 'entreprise    |                |
|                |                |                |                |
|                |                | 17\. Refus d ' |                |
|                |                | a c            |                |
|                |                | tualisation du |                |
|                |                | profil         |                |
|                |                |                |                |
|                |                | 18\. Refus     |                |
|                |                | d'une offre    |                |
|                |                | raisonnable    |                |
|                |                | d'emploi       |                |
|                |                |                |                |
|                |                | XX\. Non       |                |
|                |                | renseigné      |                |
|                |                | (codes non     |                |
|                |                | intégrés)      |                |
+----------------+----------------+----------------+----------------+
| MOTANN_a       | Motif d        | \*\*. Demande  |                |
|                | 'annulation de | annulée par le |                |
|                | la demande     | fh : aede ne   |                |
|                | détaillé       | transmet plus  |                |
|                |                | de dossier     |                |
|                |                | pour ce        |                |
|                |                | demandeur      |                |
|                |                | (voir          |                |
|                |                | description    |                |
|                |                | table de)      |                |
|                |                |                |                |
|                |                | 00\. Non       |                |
|                |                | précisé        |                |
|                |                |                |                |
|                |                | 01\. Refus de  |                |
|                |                | signature parp |                |
|                |                | pac            |                |
|                |                |                |                |
|                |                | 02\. Non p     |                |
|                |                | résentation a  |                |
|                |                | convocation    |                |
|                |                | CRP CTP        |                |
|                |                |                |                |
|                |                | 03\. Non pres. |                |
|                |                | A action r     |                |
|                |                | eclassement    |                |
|                |                | CRP            |                |
|                |                |                |                |
|                |                | 04\. Refus     |                |
|                |                | d'une offre    |                |
|                |                | emploi CRP CTP |                |
|                |                |                |                |
|                |                | 05\. Refus     |                |
|                |                | action r       |                |
|                |                | eclassement    |                |
|                |                | CRP            |                |
|                |                |                |                |
|                |                | 06\. Abandon   |                |
|                |                | action r       |                |
|                |                | eclassement    |                |
|                |                | crp            |                |
|                |                |                |                |
|                |                | 07\. Decl.     |                |
|                |                | Inexacte ou    |                |
|                |                | attest.        |                |
|                |                | Mensongere crp |                |
|                |                |                |                |
|                |                | 08\. Avis      |                |
|                |                | defav. Sur     |                |
|                |                | motif abs a    |                |
|                |                | 1er entretien  |                |
|                |                |                |                |
|                |                | 09\. Non       |                |
|                |                | présent à la   |                |
|                |                | convocation    |                |
|                |                | suite à        |                |
|                |                | l'absence au   |                |
|                |                | 1^er^          |                |
|                |                | entretien      |                |
|                |                |                |                |
|                |                | 10\. Entrée en |                |
|                |                | apr            |                |
|                |                |                |                |
|                |                | 11\. Reprise   |                |
|                |                | empl par       |                |
|                |                | propres moyen  |                |
|                |                |                |                |
|                |                | 12\. Reprise   |                |
|                |                | empl par       |                |
|                |                | propres moyen  |                |
|                |                |                |                |
|                |                | 13\. Reprise   |                |
|                |                | empl par       |                |
|                |                | propres moyen  |                |
|                |                |                |                |
|                |                | 14\. Reprise   |                |
|                |                | empl par       |                |
|                |                | propres moyen  |                |
|                |                |                |                |
|                |                | 15\. Reprise   |                |
|                |                | empl par       |                |
|                |                | propres moyen  |                |
|                |                |                |                |
|                |                | 16\. Création  |                |
|                |                | d 'entreprise  |                |
|                |                |                |                |
|                |                | 17\. Fin de    |                |
|                |                | convention de  |                |
|                |                | coopération    |                |
|                |                |                |                |
|                |                | 18\. Entrée en |                |
|                |                | CIE            |                |
|                |                |                |                |
|                |                | 19\. Entrée en |                |
|                |                | contrat        |                |
|                |                | d'accomp. Dans |                |
|                |                | l'emploi       |                |
|                |                |                |                |
|                |                | 20\. Entrée en |                |
|                |                | cev (emploi    |                |
|                |                | ville)         |                |
|                |                |                |                |
|                |                | 21\. Reprise   |                |
|                |                | empl par       |                |
|                |                | l'agence       |                |
|                |                |                |                |
|                |                | 22\. Reprise   |                |
|                |                | empl par       |                |
|                |                | l'agence       |                |
|                |                |                |                |
|                |                | 23\. Reprise   |                |
|                |                | empl par       |                |
|                |                | l'agence       |                |
|                |                |                |                |
|                |                | 24\. Reprise   |                |
|                |                | empl par       |                |
|                |                | l'agence       |                |
|                |                |                |                |
|                |                | 25\. Reprise   |                |
|                |                | empl par       |                |
|                |                | l'agence       |                |
|                |                |                |                |
|                |                | 26\. Entrée en |                |
|                |                | CES            |                |
|                |                |                |                |
|                |                | 28\. Reprise   |                |
|                |                | empl pour      |                |
|                |                | conv.          |                |
|                |                | Coopération    |                |
|                |                |                |                |
|                |                | 29\. Entrée en |                |
|                |                | RMA            |                |
|                |                |                |                |
|                |                | 30\. Entrée en |                |
|                |                | contrat        |                |
|                |                | d'avenir       |                |
|                |                |                |                |
|                |                | 31\. Entrée en |                |
|                |                | stage par ANPE |                |
|                |                |                |                |
|                |                | 32\. Entrée en |                |
|                |                | stage par      |                |
|                |                | prop.moyen     |                |
|                |                |                |                |
|                |                | 33\. Fin de    |                |
|                |                | CRP            |                |
|                |                |                |                |
|                |                | 34\. Entrée en |                |
|                |                | AFR            |                |
|                |                |                |                |
|                |                | 35\. Non c     |                |
|                |                | onfirmation de |                |
|                |                | l '            |                |
|                |                | inscription    |                |
|                |                | Assedic        |                |
|                |                |                |                |
|                |                | 36\. Absence   |                |
|                |                | du lieu de     |                |
|                |                | résidence \>   |                |
|                |                | 35 jours       |                |
|                |                |                |                |
|                |                | 37\. Fin de    |                |
|                |                | CTP            |                |
|                |                |                |                |
|                |                | 38\. Abandon   |                |
|                |                | volontaire     |                |
|                |                | (sortie        |                |
|                |                | anticipée) du  |                |
|                |                | CTP            |                |
|                |                |                |                |
|                |                | 39\. Entrée en |                |
|                |                | congé parental |                |
|                |                |                |                |
|                |                | 40\. Arrêt i   |                |
|                |                | nvolontaire de |                |
|                |                | stage (cat =   |                |
|                |                | 4)             |                |
|                |                |                |                |
|                |                | 41\. Fin de    |                |
|                |                | stage ou       |                |
|                |                | mesure (cat =  |                |
|                |                | 4)             |                |
|                |                |                |                |
|                |                | 42\. Abandon   |                |
|                |                | de stage ou    |                |
|                |                | mesure (cat =  |                |
|                |                | 4)             |                |
|                |                |                |                |
|                |                | 43\. Fin       |                |
|                |                | contrat        |                |
|                |                | temporaire ou  |                |
|                |                | cdd (cat = 5)  |                |
|                |                |                |                |
|                |                | 44\. Service   |                |
|                |                | militaire      |                |
|                |                |                |                |
|                |                | 45\. Maladie,  |                |
|                |                | maternité,     |                |
|                |                | accident       |                |
|                |                | travail        |                |
|                |                |                |                |
|                |                | 46\.           |                |
|                |                | Changement     |                |
|                |                | d'ale          |                |
|                |                |                |                |
|                |                | 47\. Titre de  |                |
|                |                | séjour non     |                |
|                |                | valide         |                |
|                |                |                |                |
|                |                | 48\. Retraite  |                |
|                |                |                |                |
|                |                | 49\. Autres    |                |
|                |                | cas            |                |
|                |                |                |                |
|                |                | 50\. Non p     |                |
|                |                | résentation    |                |
|                |                | suite à        |                |
|                |                | convocation au |                |
|                |                | 1er entretien  |                |
|                |                |                |                |
|                |                | 51\. Refus     |                |
|                |                | d'emploi :     |                |
|                |                | suspension 1   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 52\. Refus     |                |
|                |                | d'emploi :     |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 53\. Refus     |                |
|                |                | d'emploi :     |                |
|                |                | suspension 3   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 54\. Refus     |                |
|                |                | d'emploi :     |                |
|                |                | suspension 4   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 55\. Refus     |                |
|                |                | d'emploi :     |                |
|                |                | suspension 5   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 56\. Refus     |                |
|                |                | d'emploi :     |                |
|                |                | suspension 6   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 57\.           |                |
|                |                | Annulation     |                |
|                |                | suite saisine  |                |
|                |                | ddtefp         |                |
|                |                |                |                |
|                |                | 58\. Refus de  |                |
|                |                | 2 offres r     |                |
|                |                | aisonnables    |                |
|                |                | d'emploi       |                |
|                |                |                |                |
|                |                | 59\. Fin de    |                |
|                |                | CSP            |                |
|                |                |                |                |
|                |                | 60\. Non p     |                |
|                |                | résentation à  |                |
|                |                | une            |                |
|                |                | convocation    |                |
|                |                | pnae           |                |
|                |                |                |                |
|                |                | 61\. Refus de  |                |
|                |                | formation :    |                |
|                |                | suspension 1   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 62\. Refus de  |                |
|                |                | formation :    |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 63\. Refus de  |                |
|                |                | formation :    |                |
|                |                | suspension 3   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 64\. Refus de  |                |
|                |                | formation :    |                |
|                |                | suspension 4   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 65\. Refus de  |                |
|                |                | formation :    |                |
|                |                | suspension 5   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 66\. Refus de  |                |
|                |                | formation :    |                |
|                |                | suspension 6   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 70\.           |                |
|                |                | Déclaration    |                |
|                |                | inexacte :     |                |
|                |                | suspension 12  |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 71\. Autres    |                |
|                |                | cas d'arrêt de |                |
|                |                | recherche      |                |
|                |                | d'emploi       |                |
|                |                |                |                |
|                |                | 72\. Dispense  |                |
|                |                | recherche      |                |
|                |                | d'emploi       |                |
|                |                |                |                |
|                |                | 73\. Décès     |                |
|                |                |                |                |
|                |                | 74\. Fausse    |                |
|                |                | déclaration :  |                |
|                |                | suspension 6   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 75\. Fausse    |                |
|                |                | déclaration :  |                |
|                |                | suspension 7   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 76\. Fausse    |                |
|                |                | déclaration :  |                |
|                |                | suspension 8   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 77\. Fausse    |                |
|                |                | déclaration :  |                |
|                |                | suspension 9   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 78\. Fausse    |                |
|                |                | déclaration :  |                |
|                |                | suspension 10  |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 79\. Fausse    |                |
|                |                | déclaration :  |                |
|                |                | suspension 11  |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 80\. Obtention |                |
|                |                | du statut de   |                |
|                |                | réfugié        |                |
|                |                |                |                |
|                |                | 81\. I         |                |
|                |                | nsuffisance de |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 1   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 82\. I         |                |
|                |                | nsuffisance de |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 83\. I         |                |
|                |                | nsuffisance de |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 3   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 84\. I         |                |
|                |                | nsuffisance de |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 4   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 85\. I         |                |
|                |                | nsuffisance de |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 5   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 86\. I         |                |
|                |                | nsuffisance de |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 6   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 90\. Absence   |                |
|                |                | au contrôle    |                |
|                |                |                |                |
|                |                | 91\. Non       |                |
|                |                | réponse à      |                |
|                |                | convocation :  |                |
|                |                | suspension 1   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 92\. Non       |                |
|                |                | réponse à      |                |
|                |                | convocation :  |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 93\. Non       |                |
|                |                | réponse à      |                |
|                |                | convocation :  |                |
|                |                | suspension 3   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 94\. Non       |                |
|                |                | réponse à      |                |
|                |                | convocation :  |                |
|                |                | suspension 4   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 95\. Date de   |                |
|                |                | péremption     |                |
|                |                | atteinte (cat  |                |
|                |                | = 4 ou 5)      |                |
|                |                |                |                |
|                |                | 96\. Non       |                |
|                |                | réponse à      |                |
|                |                | convocation :  |                |
|                |                | suspension 5   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 97\. Non       |                |
|                |                | réponse à      |                |
|                |                | convocation :  |                |
|                |                | suspension 6   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | 98\. DSM       |                |
|                |                | illisible      |                |
|                |                |                |                |
|                |                | 5x. Refus      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
|                |                |                |                |
|                |                | 6x. Refus de   |                |
|                |                | formation :    |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
|                |                |                |                |
|                |                | 8x. I          |                |
|                |                | nsuffisance de |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
|                |                |                |                |
|                |                | A2.            |                |
|                |                | Déclaration    |                |
|                |                | inexacte       |                |
|                |                | d'activité     |                |
|                |                | brève :        |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | A3.            |                |
|                |                | Déclaration    |                |
|                |                | inexacte       |                |
|                |                | d'activité     |                |
|                |                | brève :        |                |
|                |                | suspension 3   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | A4.            |                |
|                |                | Déclaration    |                |
|                |                | inexacte       |                |
|                |                | d'activité     |                |
|                |                | brève :        |                |
|                |                | suspension 4   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | A5.            |                |
|                |                | Déclaration    |                |
|                |                | inexacte       |                |
|                |                | d'activité     |                |
|                |                | brève :        |                |
|                |                | suspension 5   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | A6.            |                |
|                |                | Déclaration    |                |
|                |                | inexacte       |                |
|                |                | d'activité     |                |
|                |                | brève :        |                |
|                |                | suspension 6   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | A7.            |                |
|                |                | Déclaration    |                |
|                |                | inexacte       |                |
|                |                | d'activité     |                |
|                |                | brève :        |                |
|                |                | suspension 7   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | A9.            |                |
|                |                | Déclaration    |                |
|                |                | inexacte       |                |
|                |                | d'activité     |                |
|                |                | brève :        |                |
|                |                | suspension 9   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | AC.            |                |
|                |                | Déclaration    |                |
|                |                | inexacte       |                |
|                |                | d'activité     |                |
|                |                | brève :        |                |
|                |                | suspension 12  |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | B1. Refus d'un |                |
|                |                | contrat d' a p |                |
|                |                | p rentissage:  |                |
|                |                | suspension 1   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | B2. Refus d'un |                |
|                |                | contrat d' a p |                |
|                |                | p rentissage:  |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | BX. Refus d'un |                |
|                |                | contrat d' a p |                |
|                |                | p rentissage:  |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
|                |                |                |                |
|                |                | C1. Refus      |                |
|                |                | action         |                |
|                |                | insertion      |                |
|                |                | suspension : 1 |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | C2. Refus      |                |
|                |                | action         |                |
|                |                | insertion      |                |
|                |                | suspension : 2 |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | C3. Refus      |                |
|                |                | action         |                |
|                |                | insertion      |                |
|                |                | suspension : 3 |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | C4. Refus      |                |
|                |                | action         |                |
|                |                | insertion      |                |
|                |                | suspension : 4 |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | C6. Refus      |                |
|                |                | action         |                |
|                |                | insertion      |                |
|                |                | suspension : 6 |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | CA. CDI (CUI)  |                |
|                |                |                |                |
|                |                | CB. CDD d'au   |                |
|                |                | moins 6 mois   |                |
|                |                | (CUI)          |                |
|                |                |                |                |
|                |                | CC\. Contrat   |                |
|                |                | travail        |                |
|                |                | temporaire     |                |
|                |                | d'au moins 6   |                |
|                |                | mois (CUI)     |                |
|                |                |                |                |
|                |                | CD\. Abandon   |                |
|                |                | CRP CTP CSP    |                |
|                |                |                |                |
|                |                | CE. Bascule    |                |
|                |                | CRP vers CTP   |                |
|                |                |                |                |
|                |                | CF. Entrée en  |                |
|                |                | CUI-CIE        |                |
|                |                |                |                |
|                |                | CG. Entrée en  |                |
|                |                | CUI-CIE        |                |
|                |                |                |                |
|                |                | CH. Reprise    |                |
|                |                | d'emploi i     |                |
|                |                | ncompatible    |                |
|                |                | avec le        |                |
|                |                | dispositif     |                |
|                |                | (CSP)          |                |
|                |                |                |                |
|                |                | CI\. Entrée en |                |
|                |                | emploi         |                |
|                |                | d'avenir       |                |
|                |                | marchand       |                |
|                |                |                |                |
|                |                | CJ. Entrée en  |                |
|                |                | emploi         |                |
|                |                | d'avenir non   |                |
|                |                | marchand       |                |
|                |                |                |                |
|                |                | CK. Entrée en  |                |
|                |                | emploi         |                |
|                |                | d'avenir       |                |
|                |                | professeur     |                |
|                |                |                |                |
|                |                | CX\. Refus     |                |
|                |                | action         |                |
|                |                | insertion :    |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
|                |                |                |                |
|                |                | D1. Refus      |                |
|                |                | contrat aidé : |                |
|                |                | suspension 1   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | D2. Refus      |                |
|                |                | contrat aidé : |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | D6. Refus      |                |
|                |                | contrat aidé : |                |
|                |                | suspension 6   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | DX\. Refus     |                |
|                |                | contrat aidé : |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
|                |                |                |                |
|                |                | E2. Refus      |                |
|                |                | visite         |                |
|                |                | médicale :     |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | E4. Refus      |                |
|                |                | visite         |                |
|                |                | médicale :     |                |
|                |                | suspension 4   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | G2. Refus d '  |                |
|                |                | élaboration    |                |
|                |                | PPAE :         |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | H2. Refus      |                |
|                |                | d'une offre    |                |
|                |                | raisonnable    |                |
|                |                | d'emploi :     |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | I1. Refus      |                |
|                |                | d'une action   |                |
|                |                | d'aide à la    |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 1   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | I2. Refus      |                |
|                |                | d'une action   |                |
|                |                | d'aide à la    |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 2   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | I3. Refus      |                |
|                |                | d'une action   |                |
|                |                | d'aide à la    |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 3   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | I4. Refus      |                |
|                |                | d'une action   |                |
|                |                | d'aide à la    |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 4   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | I5. Refus      |                |
|                |                | d'une action   |                |
|                |                | d'aide à la    |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 5   |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | IX\. Refus     |                |
|                |                | d'une action   |                |
|                |                | d'aide à la    |                |
|                |                | recherche      |                |
|                |                | d'emploi :     |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
|                |                |                |                |
|                |                | J2. Refus d    |                |
|                |                | 'actu          |                |
|                |                | alisation PPAE |                |
|                |                |                |                |
|                |                | : suspension 2 |                |
|                |                | mois           |                |
|                |                |                |                |
|                |                | KX. Refus      |                |
|                |                | contrat profes |                |
|                |                | s i o          |                |
|                |                | nnalisation :  |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
|                |                |                |                |
|                |                | L2. Refus      |                |
|                |                | contrat profes |                |
|                |                | s i o          |                |
|                |                | nnalisation :  |                |
|                |                | suspension 15  |                |
|                |                | jours          |                |
+----------------+----------------+----------------+----------------+
| MOTINS         | Motif d '      | 0\. Sans objet |                |
|                | inscription de | (catégorie 5)  |                |
|                | la demande     |                |                |
|                | agrégé         | 1\. L          |                |
|                |                | icenciement    |                |
|                |                | économique     |                |
|                |                |                |                |
|                |                | 2\. Autre l    |                |
|                |                | icenciement    |                |
|                |                |                |                |
|                |                | 3\. Démission  |                |
|                |                |                |                |
|                |                | 4\. Fin de     |                |
|                |                | contrat        |                |
|                |                |                |                |
|                |                | 5\. Fin de     |                |
|                |                | mission        |                |
|                |                | d'intérim      |                |
|                |                |                |                |
|                |                | 6\. Première   |                |
|                |                | entrée sur le  |                |
|                |                | marché du      |                |
|                |                | travail        |                |
|                |                |                |                |
|                |                | 7\. Reprise    |                |
|                |                | d'activité     |                |
|                |                | après une i    |                |
|                |                | nterruption \> |                |
|                |                | 6 mois         |                |
|                |                |                |                |
|                |                | 8\. Autres cas |                |
|                |                |                |                |
|                |                | 9\. Fin de     |                |
|                |                | convention de  |                |
|                |                | conversion     |                |
|                |                |                |                |
|                |                | A. Entrée en   |                |
|                |                | CRP            |                |
|                |                |                |                |
|                |                | B. Fin de CRP  |                |
|                |                |                |                |
|                |                | C. Rupture CNE |                |
|                |                | initiative     |                |
|                |                | employeur      |                |
|                |                |                |                |
|                |                | D. Rupture CNE |                |
|                |                | initiative     |                |
|                |                | salarié        |                |
|                |                |                |                |
|                |                | E. Sortie de   |                |
|                |                | stage          |                |
|                |                |                |                |
|                |                | F. Fin         |                |
|                |                | d'activité non |                |
|                |                | salariée       |                |
|                |                |                |                |
|                |                | G. Fin de      |                |
|                |                | maladie, de    |                |
|                |                | maternité      |                |
|                |                |                |                |
|                |                | H. Entrée en   |                |
|                |                | CTP            |                |
|                |                |                |                |
|                |                | I. Rupture c o |                |
|                |                | n v            |                |
|                |                | entionnelle du |                |
|                |                | CDI            |                |
|                |                |                |                |
|                |                | J. Entrée CTP  |                |
|                |                | (suite CRP)    |                |
|                |                |                |                |
|                |                | K. Entrée en   |                |
|                |                | CSP            |                |
|                |                |                |                |
|                |                | X. Non         |                |
|                |                | renseigné      |                |
|                |                |                |                |
|                |                | Z.  L          |                |
|                |                |                |                |
|                |                |    icenciement |                |
|                |                |                |                |
|                |                | économique PAP |                |
|                |                |                |                |
|                |                | anticipé       |                |
+----------------+----------------+----------------+----------------+
| MOTINS_A       | Motif d '      | 00\. Sans      |                |
|                | inscription de | objet          |                |
|                | la demande     | (catégorie 5)  |                |
|                | détaillé       |                |                |
|                |                | 11\. L         |                |
|                |                | icenciement    |                |
|                |                | économique     |                |
|                |                |                |                |
|                |                | 12\. Autre l   |                |
|                |                | icenciement    |                |
|                |                |                |                |
|                |                | 13\. Démission |                |
|                |                |                |                |
|                |                | 14\. Fin de    |                |
|                |                | contrat        |                |
|                |                |                |                |
|                |                | 15\. Fin de    |                |
|                |                | mission        |                |
|                |                | d'intérim      |                |
|                |                |                |                |
|                |                | 16\. Fin       |                |
|                |                | convention     |                |
|                |                | conversion     |                |
|                |                |                |                |
|                |                | 17\. L         |                |
|                |                | icenciement    |                |
|                |                | économique PAP |                |
|                |                | anticipé       |                |
|                |                |                |                |
|                |                | 18\. Fin de    |                |
|                |                | contrat emploi |                |
|                |                | jeune          |                |
|                |                |                |                |
|                |                | 19\. Autres    |                |
|                |                | cas            |                |
|                |                |                |                |
|                |                | 20\. Entrée en |                |
|                |                | CRP            |                |
|                |                |                |                |
|                |                | 21\. Première  |                |
|                |                | entrée marché  |                |
|                |                | du travail     |                |
|                |                |                |                |
|                |                | 22. Reprise    |                |
|                |                |                |                |
|                |                | activité après |                |
|                |                |                |                |
|                |                | i nterruption  |                |
|                |                | \> 6 mois      |                |
|                |                |                |                |
|                |                | 23\. Benef.    |                |
|                |                | Acti. Conv. Du |                |
|                |                | 3 fev. 9       |                |
|                |                |                |                |
|                |                | 24\. Primo     |                |
|                |                | arrivant       |                |
|                |                |                |                |
|                |                | 25\. Fin de    |                |
|                |                | CRP            |                |
|                |                |                |                |
|                |                | 26\. Rupture c |                |
|                |                | o n v          |                |
|                |                | entionnelle    |                |
|                |                | initiative     |                |
|                |                | employé        |                |
|                |                |                |                |
|                |                | 27\. Rupture c |                |
|                |                | o n v          |                |
|                |                | entionnelle    |                |
|                |                | initiative     |                |
|                |                | salarié        |                |
|                |                |                |                |
|                |                | 28\. Sortie de |                |
|                |                | stage          |                |
|                |                |                |                |
|                |                | 29\. Fin       |                |
|                |                | d'activité non |                |
|                |                | salariée       |                |
|                |                |                |                |
|                |                | 30\. Fin de    |                |
|                |                | maladie,       |                |
|                |                | maternité      |                |
|                |                |                |                |
|                |                | 31\. Entrée en |                |
|                |                | CTP            |                |
|                |                |                |                |
|                |                | 32\. Rupture c |                |
|                |                | o n v          |                |
|                |                | entionnelle du |                |
|                |                | CDI            |                |
|                |                |                |                |
|                |                | 33\. Entrée    |                |
|                |                | CTP (suite     |                |
|                |                | CRP)           |                |
|                |                |                |                |
|                |                | 34\. Entrée en |                |
|                |                | CSP            |                |
|                |                |                |                |
|                |                | 35\. Retour en |                |
|                |                | France         |                |
|                |                |                |                |
|                |                | 36\. Fin de    |                |
|                |                | détention      |                |
|                |                |                |                |
|                |                | 37\. Fin de    |                |
|                |                | période        |                |
|                |                | d'essai        |                |
|                |                |                |                |
|                |                | 38\. Fin de    |                |
|                |                | service        |                |
|                |                | civique        |                |
|                |                |                |                |
|                |                | 39\. Recherche |                |
|                |                | d'un autre     |                |
|                |                | emploi         |                |
+----------------+----------------+----------------+----------------+
| NATION         | Nationalité du | 1\. Français   |                |
|                | demandeur      |                |                |
|                | d'emploi       | 2\. Chypriotes |                |
|                |                | (partie        |                |
|                |                | grecque)       |                |
|                |                |                |                |
|                |                | 3\. Maltais    |                |
|                |                |                |                |
|                |                | 4\. Helvètes   |                |
|                |                |                |                |
|                |                | 5\.            |                |
|                |                | Autrichiens    |                |
|                |                |                |                |
|                |                | 6\. Finlandais |                |
|                |                |                |                |
|                |                | 7\. Suédois    |                |
|                |                |                |                |
|                |                | 8\. Norvégiens |                |
|                |                |                |                |
|                |                | 9\. Islandais  |                |
|                |                |                |                |
|                |                | 10\. Li e c h  |                |
|                |                | tensteinois    |                |
|                |                |                |                |
|                |                | 11\. Allemand  |                |
|                |                |                |                |
|                |                | 12\. Belges    |                |
|                |                |                |                |
|                |                | 13\.           |                |
|                |                | Hollandais     |                |
|                |                |                |                |
|                |                | 14\. Italiens  |                |
|                |                |                |                |
|                |                | 15\. L u x     |                |
|                |                | embourgeois    |                |
|                |                |                |                |
|                |                | 16\. B         |                |
|                |                | ritanniques    |                |
|                |                |                |                |
|                |                | 17\. Danois    |                |
|                |                |                |                |
|                |                | 18\. Irlandais |                |
|                |                |                |                |
|                |                | 19\. Grecs     |                |
|                |                |                |                |
|                |                | 21\. Espagnols |                |
|                |                |                |                |
|                |                | 22\. Portugais |                |
|                |                |                |                |
|                |                | 24\.           |                |
|                |                | Yougoslaves    |                |
|                |                |                |                |
|                |                | 25\. Polonais  |                |
|                |                |                |                |
|                |                | 26\. Turcs     |                |
|                |                |                |                |
|                |                | 27\. Croates   |                |
|                |                |                |                |
|                |                | 23\. EEE       |                |
|                |                | (européens     |                |
|                |                | espace         |                |
|                |                | économique)    |                |
|                |                |                |                |
|                |                | 29\. Autres    |                |
|                |                | européens      |                |
|                |                |                |                |
|                |                | 31\. Algériens |                |
|                |                |                |                |
|                |                | 32\. Marocains |                |
|                |                |                |                |
|                |                | 33\. Tunisiens |                |
|                |                |                |                |
|                |                | 42\.           |                |
|                |                | Camerounais    |                |
|                |                |                |                |
|                |                | 43\.           |                |
|                |                | Sénégalais     |                |
|                |                |                |                |
|                |                | 44\. Ivoiriens |                |
|                |                |                |                |
|                |                | 49\. Autres    |                |
|                |                | africains      |                |
|                |                |                |                |
|                |                | 51\.           |                |
|                |                | Vietnamiens    |                |
|                |                | laotiens       |                |
|                |                | cambodgiens    |                |
|                |                |                |                |
|                |                | 59\. Autres    |                |
|                |                | asiatiques     |                |
|                |                |                |                |
|                |                | 69\.           |                |
|                |                | Américains du  |                |
|                |                | Nord           |                |
|                |                |                |                |
|                |                | 79\.           |                |
|                |                | Américains du  |                |
|                |                | Sud            |                |
|                |                |                |                |
|                |                | 89\. Océaniens |                |
|                |                |                |                |
|                |                | 90\. Hongrois  |                |
|                |                |                |                |
|                |                | 91\.           |                |
|                |                | Lituaniens     |                |
|                |                |                |                |
|                |                | 92\. Estoniens |                |
|                |                |                |                |
|                |                | 93\. Lettons   |                |
|                |                |                |                |
|                |                | 94\. Tchèques  |                |
|                |                |                |                |
|                |                | 95\. Slovaques |                |
|                |                |                |                |
|                |                | 96\. Slovènes  |                |
|                |                |                |                |
|                |                | 97\. Bulgares  |                |
|                |                |                |                |
|                |                | 98\. Roumains  |                |
|                |                |                |                |
|                |                | 99\. Inconnue  |                |
+----------------+----------------+----------------+----------------+
| NBAR78         | Nombre de mois |                |                |
|                | d'activité     |                |                |
|                | réduite \<=    |                |                |
|                | 78H            |                |                |
+----------------+----------------+----------------+----------------+
| NBAR79         | Nombre de mois |                |                |
|                | d'activité     |                |                |
|                | réduite \> 78H |                |                |
+----------------+----------------+----------------+----------------+
| NDEM           | Numéro de la   | Numéroté de la |                |
|                | demande        | plus récente à |                |
|                |                | la plus        |                |
|                |                | ancienne (la   |                |
|                |                | demande n°1    |                |
|                |                | est la demande |                |
|                |                | la plus        |                |
|                |                | récente à la   |                |
|                |                | date           |                |
|                |                | statistique du |                |
|                |                | FHS)           |                |
+----------------+----------------+----------------+----------------+
| NIVFOR         | Niveau de      | 000\. Inconnu  |                |
|                | formation      |                |                |
|                | atteint par le | AFS. Aucune    |                |
|                | demandeur      | formation      |                |
|                |                | scolaire       |                |
|                |                |                |                |
|                |                | C12. Classes   |                |
|                |                | 2e et 1e       |                |
|                |                | (études        |                |
|                |                | générales)     |                |
|                |                |                |                |
|                |                | C3a.           |                |
|                |                | Bepc-classe 3e |                |
|                |                | achevée        |                |
|                |                |                |                |
|                |                | CFG. Classes   |                |
|                |                | 6e 5e 4e       |                |
|                |                |                |                |
|                |                | Cp4.           |                |
|                |                | Certificat     |                |
|                |                | études         |                |
|                |                | primaires.     |                |
|                |                | CPP-CPA        |                |
|                |                |                |                |
|                |                | Nv1. Bac+5 et  |                |
|                |                | +              |                |
|                |                |                |                |
|                |                | Nv2. Bac +3 et |                |
|                |                | +4             |                |
|                |                |                |                |
|                |                | Nv3. Bac +2    |                |
|                |                |                |                |
|                |                | Nv4. Bac       |                |
|                |                |                |                |
|                |                | Nv5. Cap / BEP |                |
+----------------+----------------+----------------+----------------+
| NUMCDV         | Référence      |                |                |
|                | contrat de     |                |                |
|                | ville          |                |                |
+----------------+----------------+----------------+----------------+
| NUMCUCS        | Numéro de la   |                |                |
|                | CUCS           |                |                |
+----------------+----------------+----------------+----------------+
| NUMQPV         | Référence QPV  |                |                |
+----------------+----------------+----------------+----------------+
| NUMZUS         | Numéro de la   |                |                |
|                | ZUS            |                |                |
+----------------+----------------+----------------+----------------+
| OBLIGEM1       | Obligation     | 0\. Sans       |                |
|                | d'emploi du    | obligation     |                |
|                | demandeur      | d'emploi       |                |
|                | d'emploi 1     |                |                |
|                |                | 1\. Orphelin   |                |
|                |                | de guerre      |                |
|                |                |                |                |
|                |                | 2\. Veuf (ve)  |                |
|                |                | de guerre ou   |                |
|                |                | conjoint de    |                |
|                |                | militaire      |                |
|                |                | invalide       |                |
|                |                |                |                |
|                |                | 3\. Pensionné  |                |
|                |                | de guerre      |                |
|                |                |                |                |
|                |                | 4\.            |                |
|                |                | Travailleur    |                |
|                |                | handicapé      |                |
|                |                | catégorie A    |                |
|                |                |                |                |
|                |                | 5\.            |                |
|                |                | Travailleur    |                |
|                |                | handicapé      |                |
|                |                | catégorie B    |                |
|                |                |                |                |
|                |                | 6\.            |                |
|                |                | Travailleur    |                |
|                |                | handicapé      |                |
|                |                | catégorie C    |                |
|                |                |                |                |
|                |                | 7\. En         |                |
|                |                | instance de    |                |
|                |                | décision CDA   |                |
|                |                | (Commission    |                |
|                |                | des droits et  |                |
|                |                | de l           |                |
|                |                | 'autonomie)    |                |
|                |                |                |                |
|                |                | 8\. Pension d  |                |
|                |                | 'invalidité    |                |
|                |                | s.s. Ou autre  |                |
|                |                |                |                |
|                |                | 9\. Rente      |                |
|                |                | accident du    |                |
|                |                | travail ou     |                |
|                |                | maladie p r o  |                |
|                |                | f essionnelle  |                |
|                |                | \>= 10%        |                |
|                |                |                |                |
|                |                | C. RGTH -- CRP |                |
|                |                |                |                |
|                |                | E. RGTH --     |                |
|                |                | ESAT           |                |
|                |                |                |                |
|                |                | H. Alloc       |                |
|                |                | adulte         |                |
|                |                | handicapé      |                |
|                |                | (manuel)       |                |
|                |                |                |                |
|                |                | I. Carte d     |                |
|                |                | 'invalidité    |                |
|                |                |                |                |
|                |                | M. RGTH --     |                |
|                |                | marché du      |                |
|                |                | travail        |                |
|                |                |                |                |
|                |                | R. Alloc       |                |
|                |                | adulte         |                |
|                |                | handicapé      |                |
|                |                | (auto)         |                |
+----------------+----------------+----------------+----------------+
| OBLIGEM2       | Obligation     | Idem OBLIGEM1  |                |
|                | d'emploi du    |                |                |
|                | demandeur      |                |                |
|                | d'emploi 2     |                |                |
+----------------+----------------+----------------+----------------+
| OBLIGEM3       | Obligation     | 0\. Sans       |                |
|                | d'emploi du    | obligation     |                |
|                | demandeur      | d'emploi       |                |
|                | d'emploi 3     |                |                |
|                | (AAH)          | H.  Allocation |                |
|                |                |     adulte     |                |
|                |                |                |                |
|                |                |     handicapé  |                |
|                |                |                |                |
|                |                | I.  Allocation |                |
|                |                |     adulte     |                |
|                |                |                |                |
|                |                |     handicapé  |                |
+----------------+----------------+----------------+----------------+
| OBLIGEMC       | Obligation     | Idem OBLIGEM1  |                |
|                | d'emploi du    |                |                |
|                | demandeur      |                |                |
|                | d'emploi       |                |                |
|                | calculée       |                |                |
+----------------+----------------+----------------+----------------+
| PROJENTR       | Projet d       | E. Projet      |                |
|                | 'entreprise    | envisagé       |                |
|                |                |                |                |
|                |                | V. Projet      |                |
|                |                | validé         |                |
+----------------+----------------+----------------+----------------+
| QPV            | Indicateur     |                |                |
|                | résidence QPV  |                |                |
+----------------+----------------+----------------+----------------+
| QUALIF         | Q u            | 0\. Non        |                |
|                | alification du | précisé        |                |
|                | demandeur      |                |                |
|                |                | 1\. Manœuvres  |                |
|                |                |                |                |
|                |                | 2\. Ouvriers   |                |
|                |                | spécialisés    |                |
|                |                |                |                |
|                |                | 3\. Ouvriers   |                |
|                |                | qualifiés      |                |
|                |                | (OP1-OP2)      |                |
|                |                |                |                |
|                |                | 4\. Ouvriers   |                |
|                |                | qualifiés      |                |
|                |                | (OP3-OHQ)      |                |
|                |                |                |                |
|                |                | 5\. Employés   |                |
|                |                | non qualifiés  |                |
|                |                |                |                |
|                |                | 6\. Employés   |                |
|                |                | qualifiés      |                |
|                |                |                |                |
|                |                | 7\. Technicien |                |
|                |                | s - d          |                |
|                |                | essinateurs    |                |
|                |                |                |                |
|                |                | 8\. Agents de  |                |
|                |                | maîtrise       |                |
|                |                |                |                |
|                |                | 9\. Cadres     |                |
+----------------+----------------+----------------+----------------+
| REGION         | Région         | 01\.           |                |
|                |                | Guadeloupe     |                |
|                |                |                |                |
|                |                | 02\.           |                |
|                |                | Martinique     |                |
|                |                |                |                |
|                |                | 03\. Guyane    |                |
|                |                |                |                |
|                |                | 04\. Réunion   |                |
|                |                |                |                |
|                |                | 06\. Mayotte   |                |
|                |                |                |                |
|                |                | 11\. Î l       |                |
|                |                | e-de-France    |                |
|                |                |                |                |
|                |                | 24\.           |                |
|                |                | Centre-Val de  |                |
|                |                | Loire          |                |
|                |                |                |                |
|                |                | 27\.           |                |
|                |                | Bourgogne - F  |                |
|                |                | r anche-Comté  |                |
|                |                |                |                |
|                |                | 28\. Normandie |                |
|                |                |                |                |
|                |                | 32\. N o       |                |
|                |                | rd-Pas-de-C a  |                |
|                |                | l a            |                |
|                |                | is-Picardie    |                |
|                |                |                |                |
|                |                | 44\. A lsac    |                |
|                |                | e - C          |                |
|                |                | hampagne-Ar d  |                |
|                |                | e n            |                |
|                |                | ne-Lorraine    |                |
|                |                |                |                |
|                |                | 52\. Pays de   |                |
|                |                | la Loire       |                |
|                |                |                |                |
|                |                | 53\. Bretagne  |                |
|                |                |                |                |
|                |                | 75\. Aqu itai  |                |
|                |                | n e -          |                |
|                |                | Limousin-Po i  |                |
|                |                | t o            |                |
|                |                | u-Charentes    |                |
|                |                |                |                |
|                |                | 76\. La ngue d |                |
|                |                | oc- R          |                |
|                |                | oussillon - M  |                |
|                |                | i di-Pyrénées  |                |
|                |                |                |                |
|                |                | 84\. Auverg n  |                |
|                |                | e -            |                |
|                |                | Rhône-Alpes    |                |
|                |                |                |                |
|                |                | 93\. Prove n c |                |
|                |                | e -Alpes-Côte  |                |
|                |                | d'Azur         |                |
|                |                |                |                |
|                |                | 94\. Corse     |                |
+----------------+----------------+----------------+----------------+
| RMA            | Éligibilité au | 1\. Valeur de  |                |
|                | revenu minimum | r edressement  |                |
|                | d'activité     | (non           |                |
|                |                | référencée)    |                |
|                |                |                |                |
|                |                | 2\. Non b      |                |
|                |                | énéficiaire    |                |
|                |                |                |                |
|                |                | 3\. Valeur de  |                |
|                |                | r edressement  |                |
|                |                | (vide)         |                |
+----------------+----------------+----------------+----------------+
| RMI            | Code RMI du    | 1\. RMI        |                |
|                | mois précédent |                |                |
|                | le mois stat   | 2\. Non b      |                |
|                | ou code RSA du | énéficiaire    |                |
|                | mois stat      |                |                |
|                |                | 3\. Valeur de  |                |
|                |                | r edressement  |                |
|                |                | (vide)         |                |
|                |                |                |                |
|                |                | 4\. RSA        |                |
|                |                | nouveau droit  |                |
|                |                |                |                |
|                |                | 5\. RSA ancien |                |
|                |                | RMI/API        |                |
+----------------+----------------+----------------+----------------+
| ROME           | Code ROME du   |                |                |
|                | métier         |                |                |
|                | recherché      |                |                |
+----------------+----------------+----------------+----------------+
| ROMEAPL        | Code           | L '            |                |
|                | appellation du | appellation du |                |
|                | ROME           | ROME est sur 3 |                |
|                |                | positions et   |                |
|                |                | est associée à |                |
|                |                | un code ROME   |                |
|                |                | pour avoir le  |                |
|                |                | libellé c o    |                |
|                |                | rrespondant au |                |
|                |                | métier. L '    |                |
|                |                | appellation du |                |
|                |                | ROME seul n'a  |                |
|                |                | aucune s i g   |                |
|                |                | nification.    |                |
+----------------+----------------+----------------+----------------+
| ROMEASS        | Rome Assedic   |                | Variable i     |
|                | recherché      |                | nutilisable    |
+----------------+----------------+----------------+----------------+
| ROMEVAL        | Code           | 1\. Réserve ou |                |
|                | validation du  | alerte sur     |                |
|                | ROME           | conduite à     |                |
|                |                | tenir          |                |
|                |                |                |                |
|                |                | 2\. Maîtrise   |                |
|                |                | des CTB e m    |                |
|                |                | ploi/métier    |                |
|                |                |                |                |
|                |                | 3\. Maitrise   |                |
|                |                | CTB e m p l    |                |
|                |                | oi/métier +    |                |
|                |                | évaluation     |                |
+----------------+----------------+----------------+----------------+
| RSQSTAT        | Risque         | RS1. Risque    |                |
|                | statistique du | faible de      |                |
|                | demandeur      | chômage de     |                |
|                | d'emploi       | longue durée   |                |
|                |                |                |                |
|                |                | RS2. Risque    |                |
|                |                | modéré de      |                |
|                |                | chômage de     |                |
|                |                | longue durée   |                |
|                |                |                |                |
|                |                | RS3. Risque    |                |
|                |                | fort de        |                |
|                |                | chômage de     |                |
|                |                | longue durée   |                |
+----------------+----------------+----------------+----------------+
| SALMT          | Montant du     |                | Risques de     |
|                | salaire brut   |                | valeurs        |
|                | demandé par le |                | extrêmes liées |
|                | DE             |                | vra i s e      |
|                |                |                | mblablement à  |
|                |                |                | une erreur     |
|                |                |                | d'unité        |
+----------------+----------------+----------------+----------------+
| SALUNIT        | Salaire        | 0\. Non        |                |
|                | horaire,       | renseigné      |                |
|                | mensuel ou     |                |                |
|                | annuel du DE   | A. Annuel      |                |
|                |                |                |                |
|                |                | C. Cachet      |                |
|                |                |                |                |
|                |                | H. Horaire     |                |
|                |                |                |                |
|                |                | M. Mensuel     |                |
+----------------+----------------+----------------+----------------+
| SEXE           | Sexe du        | 1\. Homme      |                |
|                | demandeur      |                |                |
|                | d'emploi       | 2\. Femme      |                |
+----------------+----------------+----------------+----------------+
| SITMAT         | Situation de   | C              |                |
|                | famille du     | .  Célibataire |                |
|                | demandeur      |                |                |
|                | d'emploi       | D. Divorcé ou  |                |
|                |                | séparé         |                |
|                |                |                |                |
|                |                | M. Marié ou    |                |
|                |                | vie maritale   |                |
|                |                |                |                |
|                |                | V. Veuf        |                |
+----------------+----------------+----------------+----------------+
| SITPAR         | Situation p    | 0\. Sans Objet |                |
|                | articulière au | (catégorie     |                |
|                | regard de      | 123678)        |                |
|                | l'emploi       |                |                |
|                | agrégée        | 1\. AFR        |                |
|                |                |                |                |
|                |                | 2\. CES        |                |
|                |                |                |                |
|                |                | 3\. Autres     |                |
|                |                |                |                |
|                |                | 4\. CAE        |                |
|                |                |                |                |
|                |                | 5\. CAV        |                |
|                |                |                |                |
|                |                | 6\. CEN        |                |
|                |                |                |                |
|                |                | 7\. CIE        |                |
|                |                |                |                |
|                |                | 8\. CRP        |                |
|                |                |                |                |
|                |                | 9\. Autres     |                |
|                |                | formations     |                |
|                |                |                |                |
|                |                | A. CTP         |                |
|                |                |                |                |
|                |                | B. APR         |                |
|                |                |                |                |
|                |                | C.             |                |
|                |                |                |                |
|                |                | X. Non         |                |
|                |                | renseigné      |                |
+----------------+----------------+----------------+----------------+
| SITPAR_A       |                | ADR. AIDE      |                |
|                |                | DIFFER. AU R   |                |
|                |                | ECLASSEMENT    |                |
|                |                |                |                |
|                |                | AIF. ACTION    |                |
|                |                | INSERTION ET   |                |
|                |                | FORMATION      |                |
|                |                |                |                |
|                |                | APR. ACTION P  |                |
|                |                | REPARATOIRE AU |                |
|                |                | RECRUT.        |                |
|                |                |                |                |
|                |                | ASE. AIDE      |                |
|                |                | SPEC. COMP.    |                |
|                |                | RETOUR EMPLOI  |                |
|                |                |                |                |
|                |                | ASI. DEMANDEUR |                |
|                |                | D'ASILE        |                |
|                |                |                |                |
|                |                | AUT. AUTRES    |                |
|                |                | FORMATION      |                |
|                |                |                |                |
|                |                | CAD. CONTRAT D |                |
|                |                | 'ADAPTATION    |                |
|                |                |                |                |
|                |                | CAE. CONTRAT   |                |
|                |                | D' A C C       |                |
|                |                | OMPAGNEMENT    |                |
|                |                | DANS L'EMPLOI  |                |
|                |                |                |                |
|                |                | CAV. CONTRAT   |                |
|                |                | D'AVENIR       |                |
|                |                |                |                |
|                |                | CEN. CREATION  |                |
|                |                | D 'ENTREPRISE  |                |
|                |                |                |                |
|                |                | CES. CONTRAT   |                |
|                |                | EMP L O I      |                |
|                |                | -SOLIDARITE    |                |
|                |                |                |                |
|                |                | CIE. CONTRAT   |                |
|                |                | INITIATIVE     |                |
|                |                | EMPLOI         |                |
|                |                |                |                |
|                |                | COR. CONTRAT D |                |
|                |                | ' ORIENTATION  |                |
|                |                |                |                |
|                |                | CPP. CONTRAT D |                |
|                |                | ' A P          |                |
|                |                | PRENTISSAGE    |                |
|                |                |                |                |
|                |                | CQU. CONTRAT   |                |
|                |                | DE Q U         |                |
|                |                | ALIFICATION    |                |
|                |                |                |                |
|                |                | CRE. CONTRAT   |                |
|                |                | DE RETOUR À    |                |
|                |                | L'EMPLOI       |                |
|                |                |                |                |
|                |                | CRP.           |                |
|                |                | CONVENTION DE  |                |
|                |                | R ECLASSEMENT  |                |
|                |                | P ERSONNALISE  |                |
|                |                |                |                |
|                |                | CSP. CONTRAT   |                |
|                |                | DE S           |                |
|                |                | ECURISATION P  |                |
|                |                | R OFESSIONNEL  |                |
|                |                |                |                |
|                |                | CTP. CONTRAT   |                |
|                |                | DE TRANSITION  |                |
|                |                | P R O F        |                |
|                |                | ESSIONNELLE    |                |
|                |                |                |                |
|                |                | CUM. CUI-CIE   |                |
|                |                |                |                |
|                |                | CUN. CUI-CAE   |                |
|                |                |                |                |
|                |                | DIV\. DIVERS   |                |
|                |                |                |                |
|                |                | EAM. EMPLOI    |                |
|                |                | D'AVENIR       |                |
|                |                | MARCHAND       |                |
|                |                |                |                |
|                |                | EAN. EMPLOI    |                |
|                |                | D'AVENIR NON   |                |
|                |                | MARCHAND       |                |
|                |                |                |                |
|                |                | EAP. EMPLOI    |                |
|                |                | D'AVENIR       |                |
|                |                | PROFESSEUR     |                |
|                |                |                |                |
|                |                | EPA. PERS.     |                |
|                |                | AVEC EMPL.     |                |
|                |                | TEMPS PARTIEL  |                |
|                |                |                |                |
|                |                | EPL. PERS.     |                |
|                |                | AVEC EMPL.     |                |
|                |                | TEMPS PLEIN    |                |
|                |                |                |                |
|                |                | FCA. STAGE     |                |
|                |                | F.N.E : CADRE  |                |
|                |                |                |                |
|                |                | FFI. STAGE     |                |
|                |                | F.N.E : FEMMES |                |
|                |                | ISOLEES        |                |
|                |                |                |                |
|                |                | PMJ. PERSONNE  |                |
|                |                | SOUS MAIN DE   |                |
|                |                | JUSTICE        |                |
|                |                |                |                |
|                |                | RMA. EN RMA    |                |
|                |                |                |                |
|                |                | SAE. STAGE     |                |
|                |                | ACCES A        |                |
|                |                | L'EMPLOI       |                |
|                |                |                |                |
|                |                | SAN. SANS      |                |
|                |                | OBJET          |                |
|                |                |                |                |
|                |                | SJE. STAGE     |                |
|                |                | JEUNES : 16 -  |                |
|                |                | 25 ANS         |                |
|                |                |                |                |
|                |                | SRP. STAGE     |                |
|                |                | REINSERTION    |                |
|                |                | PROFES.        |                |
+----------------+----------------+----------------+----------------+
| STRSUIVP       | Code de la     |                | La Structure   |
|                | structure      |                | Principale est |
|                | principale de  |                | une Agence ou  |
|                | suivi          |                | une Équipe p r |
|                |                |                | o f            |
|                |                |                | essionnelle (  |
|                |                |                | sectorielle ou |
|                |                |                | g é o          |
|                |                |                | graphique). La |
|                |                |                | notion de      |
|                |                |                | bassin est     |
|                |                |                | prise en       |
|                |                |                | compte. Le     |
|                |                |                | référent       |
|                |                |                | principal,     |
|                |                |                | pour le suivi  |
|                |                |                | mensuel, est   |
|                |                |                | un agent de    |
|                |                |                | cette          |
|                |                |                | structure.     |
+----------------+----------------+----------------+----------------+
| TEMPS          | Temps de       | 1\. Temps      |                |
|                | travail de     | complet        |                |
|                | l'emploi       |                |                |
|                | recherché      | 2\. Temps      |                |
|                |                | partiel        |                |
+----------------+----------------+----------------+----------------+
| ZRR            | Indicateur de  |                |                |
|                | résidence en   |                |                |
|                | Zone de r e v  |                |                |
|                | italisation    |                |                |
|                | rurale (ZRR)   |                |                |
+----------------+----------------+----------------+----------------+
| ZUS            | Demandeur en   |                |                |
|                | zone urbaine   |                |                |
|                | sensible       |                |                |
+----------------+----------------+----------------+----------------+

## La table D2

+-----------+-----------------+-----------------+-----------------+
| Variables | Libellé         | Modalités       | Commentaires    |
+===========+=================+=================+=================+
| D2STATUT  | Indicateur du   | C. Information  |                 |
|           | niveau de       | consolidée à 12 |                 |
|           | consolidation   | mois            |                 |
|           | de              |                 |                 |
|           | l'information   |                 |                 |
|           | portant sur l'i |                 |                 |
|           | ndemnisabilité  |                 |                 |
|           | du demandeur    |                 |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | P. Information  |                 |
|           |                 | consolidée à 3  |                 |
|           |                 | mois, dite      |                 |
|           |                 | provisoire      |                 |
+-----------+-----------------+-----------------+-----------------+
| FILINDEM  | Identifie les   | 1\. 122j d      |                 |
|           | conditions d    | 'indemnisation  |                 |
|           | 'indemnisation  | 27A             |                 |
|           | (durée, taux)   |                 |                 |
|           | en fonction des |                 |                 |
|           | conditions      |                 |                 |
|           | d'affiliation   |                 |                 |
|           | (durée,         |                 |                 |
|           | convention et   |                 |                 |
|           | âge à la        |                 |                 |
|           | rupture du      |                 |                 |
|           | contrat de      |                 |                 |
|           | travail)        |                 |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 2\. 182j d      |                 |
|           |                 | 'indemnisation  |                 |
|           |                 | 27B             |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 3\. 243j d      |                 |
|           |                 | 'indemnisation  |                 |
|           |                 | 27C moins de 50 |                 |
|           |                 | ans             |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 4\. 243j d      |                 |
|           |                 | 'indemnisation  |                 |
|           |                 | 27C 50 ans et   |                 |
|           |                 | plus            |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 5\. 426j d      |                 |
|           |                 | 'indemnisation  |                 |
|           |                 | 27D moins de 25 |                 |
|           |                 | ans             |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 6\. 426j d      |                 |
|           |                 | 'indemnisation  |                 |
|           |                 | 27D entre 25 et |                 |
|           |                 | 50 ans          |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 7\. 426j d      |                 |
|           |                 | 'indemnisation  |                 |
|           |                 | 27D 50 ans et   |                 |
|           |                 | plus            |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 8\. 821j d      |                 |
|           |                 | 'indemnisation  |                 |
|           |                 | 27E entre 50 et |                 |
|           |                 | 55 ans          |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 9\. 821j d      |                 |
|           |                 | 'indemnisation  |                 |
|           |                 | 27E 55 ans et   |                 |
|           |                 | plus            |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 99\. Sans objet |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | A-F. Filière    |                 |
|           |                 | ARE 2003        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | G.              |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | H.              |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | I.              |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | J.              |                 |
+-----------+-----------------+-----------------+-----------------+
| INDEM     | Code de         | 15\. AC-FNE     |                 |
|           | l'allocation du |                 |                 |
|           | demandeur       |                 |                 |
|           | indemnisable    |                 |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 18\. PRP        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 24\. AI84       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 25\. ASS84      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 26\. ACO84      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 33\. AFR-AB     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 34\. AFR-FD     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 35\. AFR-FF     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 39\. RSP        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 40\. AUD        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 41\. AFFS       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 43\. ACA        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 44\. ASS97      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 45\. ACCRE-ASS  |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 47\. ARE2001    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 48\. AREF2001   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 49\. ARE-AFFS   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 50\. AFF        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 51\. ASS-F      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 52\. AER        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 54\. ARE2003    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 55\. AREF2003   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 56\. ASS2004    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 57\. AFSP       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 58\. AFSP-F     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 59\. AFT        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 60\. AFT-F      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 61\. ASR        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 62\. ASR-ARE    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 63\. AF         |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 64\. ARE2006    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 65\. AREF2006   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 66\. ADR06      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 67\. ASCRE06    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 70\. ATP        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 71\. AT         |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 72\. AT-F       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 73\. ATAG1      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 74\. ATAG2      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 75\. APS        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 77\. AFD        |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 78\. AFDF       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 81\. RFPE       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 82\. ARE2009    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 83\. AREF2009   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 84\. ASR09      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 85\. ASRARE09   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 86\. ADR09      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 91\. TP09ETA    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 92\. AFDEF09    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 93\. AER2009    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 95\. AFDEF10    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 96\. AEPE2010   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 99\. RFF11      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AC. ARE2011     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AD. AREF2011    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AE. ARE-CG      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AF. AREF-CG     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AG. ADR11       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AI. ADR11-CG    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AK. ASP-ARE     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AL. ASP-AREF    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AM. ASPRAC1     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AN. ASPRACF     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AQ. ASPRAC2     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AR. ASPRAC2F    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AT. ATS11       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | AY. RFF12       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BE. ATS13       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BG. RFF13       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BJ. RFF14       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BK. ARE 2014    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BM. ARE-CG      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BN. AREF 2014   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BO. AREF-CG     |                 |
|           |                 | 2014            |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BP. ARE 2014    |                 |
|           |                 | DIFF            |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BQ. AREF 2014   |                 |
|           |                 | DIFF            |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BR. RFF 2015    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BU. ASP15E2     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BW. ASP15R3     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BY. ASP15R1     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | BZ. ASP15R2F    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CB. ASP15R3F    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CC\. ASP15R1F   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CI\. RFF16      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CJ. AREM16      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CK. ?           |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CL\. AREMCG16   |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CM\. ?          |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CN. AREA816     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CO. AREFA816    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CT. ARER16      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CX\. RFF17      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CY. AAP17       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | CZ. AAP17R      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | DM. ARE2017     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | DO. ARE-CG17    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | DQ. AREFCG17    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | DR. ARCE17      |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | DT. ?           |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | DV\. APS2017    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | DW. AFD2017     |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | DY. ?           |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | EF. ?           |                 |
+-----------+-----------------+-----------------+-----------------+
| JOURDV    | Jour de début   |                 |                 |
|           | de validité     |                 |                 |
+-----------+-----------------+-----------------+-----------------+
| JOURFV    | Jour de fin de  |                 |                 |
|           | validité        |                 |                 |
+-----------+-----------------+-----------------+-----------------+
| NDEM      | Numéro de la    |                 | Numéroté de la  |
|           | demande         |                 | plus récente à  |
|           |                 |                 | la plus         |
|           |                 |                 | ancienne (la    |
|           |                 |                 | demande n°1 est |
|           |                 |                 | la demande la   |
|           |                 |                 | plus récente à  |
|           |                 |                 | la date         |
|           |                 |                 | statistique du  |
|           |                 |                 | FHS)            |
+-----------+-----------------+-----------------+-----------------+
| ODDDMAX   | Durée maximale  |                 |                 |
|           | d               |                 |                 |
|           | 'indemnisation  |                 |                 |
+-----------+-----------------+-----------------+-----------------+
| REGIME    | Régime          | 0\. Indéterminé |                 |
|           | particulier     |                 |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 1\. Régime      |                 |
|           |                 | général         |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 2\.             |                 |
|           |                 | Intermittents   |                 |
|           |                 | du spectacle    |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 3\. Autres      |                 |
|           |                 | intermittents   |                 |
|           |                 | et intérimaires |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 4\. Autres      |                 |
|           |                 | régimes         |                 |
+-----------+-----------------+-----------------+-----------------+
| REGIND    | Régime d        |                 |                 |
|           | 'indemnisation  |                 |                 |
+-----------+-----------------+-----------------+-----------------+
| REGION    |                 |                 |                 |
+-----------+-----------------+-----------------+-----------------+
| TYPEPOP   | Type de         | 0\. Non         |                 |
|           | population      | renseigné       |                 |
+-----------+-----------------+-----------------+-----------------+
|           |                 | 1\. Ancien      |                 |
|           |                 | emploi jeune    |                 |
+-----------+-----------------+-----------------+-----------------+
