---
title: "Reproduction d'indicateurs cibles"
execute: 
  enabled: false
---

## Nombre d'inscrits en catégories A, B, C en fin de mois pour un mois donné

Pour calculer cet indicateur, les variables Date d'effet d'inscription de la demande (**DATINS**), Date d'annulation de la demande (**DATANN)** et Catégorie opérationnelle du demandeur d'emploi relative à la dernière situation connue (**CATREGR**) sont utilisées. Il faut noter que les modalités 1, 2 et 3 de CATREGR ne correspondent pas respectivement aux catégories d'inscription A, B et C statistiques, mais au type de contrat recherché. Néanmoins, l'ensemble des personnes pour lesquelles CATREGR vaut 1, 2 ou 3 est équivalent à l'ensemble des demandeurs d'emploi inscrits en catégorie A, B ou C, car ce sont les demandeurs d'emploi tenus à des actes positifs de recherche d'emploi, quelle que soit la durée d'activité réduite exercée au cours du mois.

Remarque : la chaîne de caractère fournie à la fonction as.Date doit être de la forme "AAAA-MM-JJ".

```{r}

#Chargement du package dplyr 
library(dplyr)

#Définition de la date de fin du mois dont on veut les inscrits en fin de mois
mois <- as.Date("2021-12-31")

#Utilisation de la table DE
inscrits <- DE %>%
  filter(DATINS <= mois & DATANN >= mois & CATREGR %in% c("1", "2", "3")) %>%
  distinct(id_midas)
```
