---
title: "Dictionnaire des variables"
---

+--------------------------------+--------------------------------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>Variables                  | <br>Libellé                                                                          | <br>Modalités                                                       | <br>Commentaires                                                                                                                                                            |
+================================+======================================================================================+=====================================================================+=============================================================================================================================================================================+
| <br>ID_DOSSIER                 | <br> Idenfitiant IMILO                                                               |                                                                     |                                                                                                                                                                             |
+--------------------------------+--------------------------------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>DtEvenementAccueilId       | <br>Date à laquelle le jeune a été accueilli pour la première fois en Mission Locale |                                                                     | <br>La date est une chaîne de caractère au format "dd/mm/YYYY"                                                                                                              |
+--------------------------------+--------------------------------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>LB_NIVEAU_SCOLAIRE_ACCUEIL | <br>Libellé du niveau scolaire à l'accueil en Mission Locale                         |                                                                     |                                                                                                                                                                             |
+--------------------------------+--------------------------------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>ID_NIVEAU_SCOLAIRE_ACCUEIL |                                                                                      |                                                                     |                                                                                                                                                                             |
+--------------------------------+--------------------------------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>LB_NIVEAU_VALIDE_ACCUEIL   | <br>Libellé du niveau de diplôme validé à l'acueil en Mission Locale                 | <br>"Niveau I" ou "Niveau II" ou "Niveau III" : "Diplôme supérieur" | <br>Il peut y avoir des modalités qui sortent du *pattern* "Niveau ..." mais ces autres modalités sont suffisamment compréhensibles pour les raccrocher à la bonne modalité |
|                                |                                                                                      |                                                                     |                                                                                                                                                                             |
|                                |                                                                                      | <br>"Niveau IV" : "Diplôme bac"                                     |                                                                                                                                                                             |
|                                |                                                                                      |                                                                     |                                                                                                                                                                             |
|                                |                                                                                      | <br>"Niveau V" : "Diplôme CAP, BEP"                                 |                                                                                                                                                                             |
|                                |                                                                                      |                                                                     |                                                                                                                                                                             |
|                                |                                                                                      | <br>"Niveau V bis" ou " Niveau VI" : "Diplôme inférieur"            |                                                                                                                                                                             |
|                                |                                                                                      |                                                                     |                                                                                                                                                                             |
|                                |                                                                                      | <br>"Sans certification validée" : "Sans diplôme"                   |                                                                                                                                                                             |
+--------------------------------+--------------------------------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>ID_NIVEAU_VALIDE_ACCUEIL   |                                                                                      |                                                                     |                                                                                                                                                                             |
+--------------------------------+--------------------------------------------------------------------------------------+---------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
