---
title: "Dictionnaire des variables"
---

| \*\* <br>Nom Oracle (SAS) \*\* | \*\* <br>Nom segment \*\* |         \*\* <br>Libellé \*\*          |                                                                                                                                            \*\* <br>Description \*\*                                                                                                                                            |
|:------------------------------:|:-------------------------:|:--------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|           <br>KDAASP           |        <br>PARANN         |         <br>Année d'imputation         |                                                                                                                          <br>Il s'agit de l'année d'imputation de l'activité réduite.                                                                                                                           |
|           <br>KDMAP            |        <br>PARMOIS        |         <br>Mois d'imputation          |                                                                                                                            <br>Il s'agit du mois d'imputation de l'activité réduite.                                                                                                                            |
|           <br>KPHARP           |        <br>PARNBH         | <br>Nombre d'heures d'activité réduite | <br>Cette rubrique décrit le nombre d'heures d'activité réduite à imputer sur un mois donné et déclarées au cours de ce même mois ou la valeur calculée à partir du nombre de cachets, isolés et groupés, déclarés au niveau des différentes périodes d'actualisation d'un mois donné pour les annexes 8 et 10. |
|           <br>KQBARP           |        <br>PARSAB         | <br>Salaire brut de l'activité réduite |                                                                                  <br>Il s'agit du salaire brut perçu dans le cadre de l'exercice d'une activité réduite, ce salaire devant être imputé sur un mois déterminé.                                                                                   |
