---
title: "SITPAR_a"
---

Situation particulière au regard de l\'emploi détaillée


ADR. Aide différentielle au reclassement

AIF. Action d\'insertion et de formation

APR. Action préalable au recrutement

ASE. Aide spécifique complémentaire retour à l\'emploi

ASI. Demandeur d\'asile

AUT. Autres formations

CAD. Contrat d\'adaptation

CAE. Contrat d\'accompagnement dans l\'emploi

CAV. Contrat d\'avenir

CEN. Création d\'entreprise

CES. Contrat emploi-solidarité

CIE. Contrat initiative emploi

CLO. Contrat local d\'orientation

COR. Contrat d\'orientation

CPP. Contrat d\'apprentissage

CQU. Contrat de qualification

CRE. Contrat de retour à l\'emploi

CRP. Convention de reclassement personnalisé

CSP. Contrat de sécurisation professionnelle

CTP. Contrat de transition professionnelle

CUM. Contrat unique d\'insertion marchand

CUN. Contrat unique d\'insertion non marchand

DDI. Individu en CDI et en cours d\'agrément IAE 

DIV\. Divers

EAM. Contrat d\'emploi avenir marchand

EAN. Contrat d\'emploi avenir non marchand

EAP. Contrat d\'emploi avenir professeur

EPA. Personne pourvue d\'un emploi à temps partiel

EPL. Personne pourvue d\'un emploi à temps plein

FCA. Stage FNE : cadres

FFI. Stage FNA : femmes isolées

IAE. Insertion par l\'activité économique

MAN. Stage de mise à niveau

MOD. Stage modulaire

MUE. Maintien de l\'indemnisation en Union Européenne

ND1. Individu non demandeur d\'emploi

PAP. Parcours d\'accompagnement personnalisé

PEF. Préavis effectué

PLI. Programme local d\'insertion des femmes

PMJ. Personne sous main de justice

PNE. Préavis non effectué

PRE. En préavis

RMA. Contrat RMA

SAE. Stage d\'accès à l\'emploi

SAN. Sans objet

SCI. Service civique

SJE. Stages jeunes : 16-25 ans

SRP. Stage de reclassement professionnel


